Repository kyma-project/control-plane, pull requests merged in 2020-11, with the labels that each got.

#305 KEB saves operation in initialisation step
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
  resources/kcp/values.yaml
Labels: area/control-plane

#304 Add possibility to pass seed specific audit log tenant
  components/provisioner/internal/gardener/shoot_reconciler.go
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement

#311 Upgrade apimachinery in KEB
  components/kyma-environment-broker/Gopkg.lock
  resources/kcp/values.yaml
Labels: area/security

#314 Upgrade apimachinery in e2e test
  tests/e2e/provisioning/Gopkg.lock
Labels: area/security

#312 Upgrade apimachinery in kubeconfig-service
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  resources/oidc-kubeconfig-service/values.yaml
Labels: area/security

#313 Upgrade apimachinery in subscription-cleanup-job
  components/subscription-cleanup-job/cmd/main.go
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
  components/subscription-cleanup-job/internal/job/cleaner.go
  components/subscription-cleanup-job/internal/job/cleaner_test.go
  resources/kcp/values.yaml
Labels: area/security

#317 Update the KCP docs
  docs/README.md
  docs/kyma-environment-broker/03-03-runtime-operations.md
Labels: area/documentation, bug

#318 Fix the TW alias in the documentation issue template
  .github/ISSUE_TEMPLATE/documentation-improvement.md
Labels: area/documentation, bug

#321 Improvements in handling TenantNotFound error
  components/provisioner/internal/director/directorclient_test.go
  components/provisioner/internal/operations/executor.go
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement

#338 KEB chart without overrides for SKRs
  resources/kcp/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
Labels: area/management-plane, bug

#286 Create operators ClusterRoleBindings before Kyma installation
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement

#336 Improve Service Catalog cleanup while deprovisioning
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/internal/installation/installation.go
  components/provisioner/internal/installation/resource_cleanup.go
  components/provisioner/internal/installation/resource_cleanup_test.go
  resources/kcp/values.yaml
Labels: area/control-plane

#352 Replace latest-published source flag with master source flag
  installation/cmd/run.sh
Labels: area/ci
