Repository kyma-project/control-plane, pull requests merged in 2020-07, with the labels that each got.

#10 Bump compass version to the latest
  installation/resources/COMPASS_VERSION
Labels: area/monitoring

#6 Fix KEB and Kubeconfig Service dependencies
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  components/kubeconfig-service/pkg/caller/caller.go
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
  components/kyma-environment-broker/internal/hyperscaler/account_provider.go
  components/kyma-environment-broker/internal/hyperscaler/account_provider_test.go
  components/kyma-environment-broker/internal/hyperscaler/automock/account_provider.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/audit_log_step.go
  components/kyma-environment-broker/internal/process/provisioning/audit_log_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/automock/provision_input_creator.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/ias_registration.go
  components/kyma-environment-broker/internal/process/provisioning/ias_registration_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/input/builder.go
  components/kyma-environment-broker/internal/process/provisioning/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/internal_eval_test.go
  components/kyma-environment-broker/internal/process/provisioning/lms_cert_step.go
  components/kyma-environment-broker/internal/process/provisioning/lms_cert_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides_test.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides_test.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  components/kyma-environment-broker/internal/provisioner/automock/client.go
  components/kyma-environment-broker/internal/provisioner/client.go
  components/kyma-environment-broker/internal/provisioner/client_test.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  components/kyma-environment-broker/internal/runtime/custom_disabler_example.go
  components/kyma-environment-broker/internal/runtime/custom_disabler_example_test.go
  components/kyma-environment-broker/internal/runtime/generic_component_disabler.go
Labels: WIP

#17 Add ability to disable Provisioning E2E tests
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/rbac.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: area/control-plane, enhancement

#24 Adjust installer memory limits
  installation/resources/COMPASS_VERSION
  installation/resources/installer.yaml
Labels: area/management-plane, bug

#20 Rebuild all components
  components/kubeconfig-service/Dockerfile
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.keb
  components/metris/Dockerfile
  components/provisioner/Dockerfile
  components/provisioner/Makefile
  components/provisioner/internal/api/mocks/Validator.go
  components/provisioner/internal/director/mocks/DirectorClient.go
  components/provisioner/internal/graphql/mocks/Client.go
  components/provisioner/internal/installation/mocks/Service.go
  components/provisioner/internal/oauth/mocks/Client.go
  components/provisioner/internal/provisioning/mocks/Provisioner.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/runtime/mocks/Configurator.go
  components/provisioner/internal/util/k8s/mocks/K8sClientProvider.go
  components/schema-migrator/Dockerfile
  components/schema-migrator/Makefile
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/templates/migrator-job.yaml
  resources/kcp/values.yaml
  resources/oidc-kubeconfig-service/values.yaml
  tests/e2e/provisioning/Dockerfile
  tests/provisioner-tests/Dockerfile
Labels: area/control-plane, enhancement

#25 Remove 2to3 from installer
  installation/resources/COMPASS_VERSION
  installation/resources/installer.yaml
Labels: area/management-plane, bug

#26 Bump Compass
  installation/resources/COMPASS_VERSION
Labels: area/management-plane, enhancement

#29 Bump compass version
  installation/resources/COMPASS_VERSION
Labels: area/management-plane, bug

#19 Add Auto Upgrade options to the Provisioners Gardener Config schema
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/util/pointers.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202007081031_add_maintenance_autoupdate.down.sql
  components/schema-migrator/migrations/provisioner/202007081031_add_maintenance_autoupdate.up.sql
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
Labels: area/management-plane, enhancement

#36 Change hardcoded occurrences of compass-system namespace in KEB
  components/kyma-environment-broker/README.md
  components/kyma-environment-broker/internal/director/config.go
  components/kyma-environment-broker/internal/director/oauth/client_test.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
  components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml
  docs/kyma-environment-broker/03-06-runtime-overrides.md
  resources/kcp/charts/kyma-environment-broker/templates/provisioning-runtime-overrides.yaml
  resources/kcp/values.yaml
  tests/e2e/provisioning/README.md
  tests/e2e/provisioning/internal/director/config.go
  tests/e2e/provisioning/internal/director/oauth/client_test.go
  tests/e2e/provisioning/test/test_suite.go
Labels: area/management-plane, bug

#39 Add AutoUpdates to RuntimeStatus query and enhance tests
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  resources/kcp/charts/provisioner/templates/tests/test-provisioner.yaml
  resources/kcp/values.yaml
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/test/provisioner/e2e_test.go
  tests/provisioner-tests/test/testkit/assertions/helpers.go
  tests/provisioner-tests/test/testkit/compass/provisioner/graphqlizer.go
  tests/provisioner-tests/test/testkit/compass/provisioner/query.go
  tests/provisioner-tests/test/testkit/inputs.go
  tests/provisioner-tests/test/testkit/util.go
Labels: area/control-plane, area/management-plane

#34 Enable TLS renegotiation for IAS HTTP client
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/httputil/client.go
  components/kyma-environment-broker/internal/ias/bundle.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: area/control-plane

#47 Update 08-04-instance-details.md
  docs/kyma-environment-broker/08-04-instance-details.md
Labels: area/documentation, bug

#37 Add Azure lite plan
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/plans_validator.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/hyperscaler/azure/env.go
  components/kyma-environment-broker/internal/hyperscaler/azure/env_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/input/builder.go
  components/kyma-environment-broker/internal/process/provisioning/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides_test.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  docs/kyma-environment-broker/03-06-runtime-overrides.md
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: area/control-plane

#48 Add possibility to set machine image
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202007101344_add_machine_image_for_gardener_config.down.sql
  components/schema-migrator/migrations/provisioner/202007101344_add_machine_image_for_gardener_config.up.sql
  resources/kcp/values.yaml
Labels: WIP, area/control-plane

#51 Fix link for OSB API
  docs/kyma-environment-broker/02-02-broker-endpoints.md
Labels: area/documentation

#49 Remote runtime configuration with DAPR concept
  docs/internal/investigations/dapr-remote-runtime-configuration/assets/concept.png
  docs/internal/investigations/dapr-remote-runtime-configuration/configuration_concept.md
Labels: area/control-plane

#50 Prepare Runtime Director PoC
  docs/internal/investigations/runtime-director-dapr/README.md
  docs/internal/investigations/runtime-director-dapr/chart/.helmignore
  docs/internal/investigations/runtime-director-dapr/chart/Chart.yaml
  docs/internal/investigations/runtime-director-dapr/chart/templates/_helpers.tpl
  docs/internal/investigations/runtime-director-dapr/chart/templates/configmap.yaml
  docs/internal/investigations/runtime-director-dapr/chart/templates/deployment.yaml
  docs/internal/investigations/runtime-director-dapr/chart/templates/service.yaml
  docs/internal/investigations/runtime-director-dapr/chart/templates/virtualservice.yaml
  docs/internal/investigations/runtime-director-dapr/chart/values.yaml
  docs/internal/investigations/runtime-director-dapr/component/.gitignore
  docs/internal/investigations/runtime-director-dapr/component/Dockerfile
  docs/internal/investigations/runtime-director-dapr/component/Makefile
  docs/internal/investigations/runtime-director-dapr/component/cmd/main.go
  docs/internal/investigations/runtime-director-dapr/component/go.mod
  docs/internal/investigations/runtime-director-dapr/component/go.sum
  docs/internal/investigations/runtime-director-dapr/component/hack/config.yaml
  docs/internal/investigations/runtime-director-dapr/component/internal/handler/handler.go
  docs/internal/investigations/runtime-director-dapr/component/internal/store/store.go
  docs/internal/investigations/runtime-director-dapr/component/pkg/apperror/apperror.go
  docs/internal/investigations/runtime-director-dapr/component/pkg/model/model.go
  docs/internal/investigations/runtime-director-dapr/deploy.sh
Labels: area/control-plane, enhancement

#59 Remove Config Map creation after runtime is provisioned
  components/provisioner/internal/runtime/configuration_test.go
  components/provisioner/internal/runtime/configurator.go
  resources/kcp/values.yaml
Labels: area/control-plane

#71 Cleanup Provisioner Dockerfile
  components/provisioner/Dockerfile
  resources/kcp/values.yaml
Labels: area/control-plane

#72 Describe Control Plane dependencies
  README.md
Labels: area/control-plane, area/documentation, enhancement

#61 Implement shared account pool
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/gardener/client.go
  components/kyma-environment-broker/internal/hyperscaler/account_pool.go
  components/kyma-environment-broker/internal/hyperscaler/account_pool_test.go
  components/kyma-environment-broker/internal/hyperscaler/account_provider.go
  components/kyma-environment-broker/internal/hyperscaler/account_provider_test.go
  components/kyma-environment-broker/internal/hyperscaler/automock/account_provider.go
  components/kyma-environment-broker/internal/hyperscaler/shared_pool.go
  components/kyma-environment-broker/internal/hyperscaler/shared_pool_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds_test.go
  docs/kyma-environment-broker/03-04-hyperscaler-account-pool.md
Labels: area/control-plane, enhancement

#28 Add UpgradeShoot() mutation
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/mocks/Validator.go
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/api/validator.go
  components/provisioner/internal/api/validator_test.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_new_version.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_new_version_test.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/mocks/Provisioner.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/util/pointers.go
  components/provisioner/internal/util/testkit/shoot.go
  components/provisioner/internal/util/testkit/worker.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202008061313_add_upgrade_shoot_for_operation_type.down.sql
  components/schema-migrator/migrations/provisioner/202008061313_add_upgrade_shoot_for_operation_type.up.sql
Labels: area/cluster, area/control-plane, enhancement

#66 Allow setting machine image without specified version
  components/provisioner/internal/api/validator.go
  components/provisioner/internal/api/validator_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/util/strings.go
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement

#40 Document Runtime Provisioner's upgradeShoot mutation
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-03-runtime-operation-status.md
  docs/provisioner/08-04-runtime-status.md
  docs/provisioner/08-05-deprovisioning.md
  docs/provisioner/08-06-upgrading-shoots.md
  docs/provisioner/provisioning-api.md
Labels: area/control-plane, area/documentation

#75 Fix AVS client authorization process
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/avs/client.go
  components/kyma-environment-broker/internal/avs/client_test.go
  components/kyma-environment-broker/internal/avs/delegator.go
  components/kyma-environment-broker/internal/avs/external_eval_assistant.go
  components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
  components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/internal_eval_test.go
  resources/kcp/values.yaml
Labels: area/management-plane

#68 Reorganize internal documents
  docs/internal/README.md
  docs/internal/investigations/assets/concept.png
  docs/internal/investigations/dapr-poc-scenario.md
  docs/internal/investigations/remote-kyma-runtime-configuration.md
  docs/internal/investigations/runtime-governor-concept.md
  docs/internal/investigations/runtime-governor-poc/README.md
  docs/internal/investigations/runtime-governor-poc/governor/README.md
  docs/internal/investigations/runtime-governor-poc/governor/chart/.helmignore
  docs/internal/investigations/runtime-governor-poc/governor/chart/Chart.yaml
  docs/internal/investigations/runtime-governor-poc/governor/chart/templates/_helpers.tpl
  docs/internal/investigations/runtime-governor-poc/governor/chart/templates/configmap.yaml
  docs/internal/investigations/runtime-governor-poc/governor/chart/templates/deployment.yaml
  docs/internal/investigations/runtime-governor-poc/governor/chart/templates/service.yaml
  docs/internal/investigations/runtime-governor-poc/governor/chart/templates/virtualservice.yaml
  docs/internal/investigations/runtime-governor-poc/governor/chart/values.yaml
  docs/internal/investigations/runtime-governor-poc/governor/component/.gitignore
  docs/internal/investigations/runtime-governor-poc/governor/component/Dockerfile
  docs/internal/investigations/runtime-governor-poc/governor/component/Makefile
  docs/internal/investigations/runtime-governor-poc/governor/component/cmd/main.go
  docs/internal/investigations/runtime-governor-poc/governor/component/go.mod
  docs/internal/investigations/runtime-governor-poc/governor/component/go.sum
  docs/internal/investigations/runtime-governor-poc/governor/component/hack/config.yaml
  docs/internal/investigations/runtime-governor-poc/governor/component/internal/handler/handler.go
  docs/internal/investigations/runtime-governor-poc/governor/component/internal/store/store.go
  docs/internal/investigations/runtime-governor-poc/governor/component/pkg/apperror/apperror.go
  docs/internal/investigations/runtime-governor-poc/governor/component/pkg/model/model.go
  docs/internal/investigations/runtime-governor-poc/governor/deploy.sh
  docs/internal/proposals/separate-compass.md
Labels: area/documentation, enhancement

#76 Keb one trial per globalaccount
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/storage/dbsession/factory.go
  components/kyma-environment-broker/internal/storage/dbsession/read.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/storage_test.go
Labels: area/management-plane

#94 Update upgradeShoot() mutation description
  docs/provisioner/provisioning-api.md
Labels: area/control-plane, area/documentation

#97 Default Kyma settings for Trial
  components/kyma-environment-broker/internal/process/provisioning/lms_cert_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides_test.go
Labels: area/control-plane

#83 Fix panic on Environments Cleanup job
  components/kyma-environment-broker/cmd/environmentscleanup/main.go
  components/kyma-environment-broker/internal/environmentscleanup/service.go
  components/kyma-environment-broker/internal/environmentscleanup/service_test.go
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement

#70 Remove Compass references from Provisioner component
  components/kyma-environment-broker/internal/environmentscleanup/service.go
  components/provisioner/README.md
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/gardener/annotations.go
  components/provisioner/internal/gardener/annotations_test.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/installation/resource_cleanup_test.go
  components/provisioner/internal/metrics/in_progress_operations_test.go
  components/provisioner/internal/metrics/metrics.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/oauth/client_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect_test.go
  components/provisioner/internal/runtime/configuration_test.go
  docs/provisioner/01-01-provisioner-overview.md
  docs/provisioner/08-02-provisioning-gardener.md
  resources/kcp/charts/provisioner/files/dashboard.json
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/values.yaml
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
  tests/provisioner-tests/scripts/run_localy.sh
  tests/provisioner-tests/test/provisioner/e2e_test.go
  tests/provisioner-tests/test/provisioner/upgrade_shoot_test.go
  tests/provisioner-tests/test/provisioner/upgrade_test.go
  tests/provisioner-tests/test/testkit/config.go
Labels: area/control-plane
