Repository kyma-project/control-plane, pull requests merged in 2020-09, with the labels that each got.

#177 Move APIRule to Oathkeeper Rule CR
  resources/kcp/charts/kyma-environment-broker/templates/api-rule.yaml
  resources/kcp/charts/kyma-environment-broker/templates/oathkeeper-rule.yaml
  resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement

#181 Add the documentation issue template
  .github/ISSUE_TEMPLATE/documentation-improvement.md
Labels: area/documentation, documentation, enhancement

#182 Adapting e2e upgrade test to be handled by KEB
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
  tests/e2e/provisioning/Gopkg.lock
  tests/e2e/provisioning/internal/provisioner/client.go
  tests/e2e/provisioning/internal/provisioner/components_provider.go
  tests/e2e/provisioning/internal/provisioner/graphqlizer.go
  tests/e2e/provisioning/internal/provisioner/query.go
  tests/e2e/provisioning/internal/provisioner/upgrade_client.go
  tests/e2e/provisioning/pkg/client/broker/model.go
  tests/e2e/provisioning/pkg/client/broker/upgrade_broker_client.go
  tests/e2e/provisioning/test/e2e_upgrade_test.go
  tests/e2e/provisioning/test/test_suite.go
  tests/e2e/provisioning/test/upgrade_test_suite.go
Labels: area/control-plane

#168 Upgrade Gardener to 1.10.1
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/fake/gardener_client.go
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/testdata/config.json
  components/provisioner/internal/api/testdata/crd/shoot.crd.yaml
  components/provisioner/internal/gardener/kubeconfig_provider.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/installation/resource_cleanup.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/oauth/client.go
  components/provisioner/internal/oauth/client_test.go
  components/provisioner/internal/operations/stages/deprovisioning/delete_cluster.go
  components/provisioner/internal/operations/stages/deprovisioning/delete_cluster_test.go
  components/provisioner/internal/operations/stages/deprovisioning/mocks/GardenerClient.go
  components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion.go
  components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion_test.go
  components/provisioner/internal/operations/stages/provisioning/mocks/GardenerClient.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain_test.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_new_version.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_new_version_test.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade_test.go
  components/provisioner/internal/persistence/testutils/database.go
  components/provisioner/internal/runtime/configuration_test.go
  components/provisioner/internal/runtime/configurator.go
  components/provisioner/internal/util/testkit/worker.go
  resources/kcp/values.yaml
  tests/provisioner-tests/go.mod
  tests/provisioner-tests/go.sum
  tests/provisioner-tests/test/provisioner/e2e_test.go
  tests/provisioner-tests/test/provisioner/main_test.go
  tests/provisioner-tests/test/provisioner/suite.go
  tests/provisioner-tests/test/provisioner/upgrade_shoot_test.go
  tests/provisioner-tests/test/provisioner/upgrade_test.go
  tests/provisioner-tests/test/testkit/compass/director/oauth/client.go
  tests/provisioner-tests/test/testkit/compass/director/oauth/client_test.go
  tests/provisioner-tests/test/testkit/control-plane/provisioner/client.go
  tests/provisioner-tests/test/testkit/control-plane/provisioner/graphqlizer.go
  tests/provisioner-tests/test/testkit/control-plane/provisioner/query.go
  tests/provisioner-tests/test/testkit/graphql/client.go
  tests/provisioner-tests/test/testkit/logger.go
Labels: area/control-plane, area/security

#199 Bump Provisioner and Provisioner Tests image
  resources/kcp/values.yaml
Labels: area/cluster, area/control-plane, area/quality, enhancement

#211 Keb upgrade test
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/orchestration_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/orchestration/kyma/manager.go
  components/kyma-environment-broker/internal/orchestration/kyma/manager_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/config.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
Labels: area/control-plane

#202 Replace x text with v033 version in Provisioner
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/values.yaml
  tests/provisioner-tests/go.mod
  tests/provisioner-tests/go.sum
Labels: area/control-plane

#220 Bump some libs in the Runtime Provisioner and the tests
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/values.yaml
  tests/provisioner-tests/go.mod
  tests/provisioner-tests/go.sum
Labels: area/control-plane

#225 Migrate KEB SingleStat grafana panels to Stat
  resources/kcp/charts/kyma-environment-broker/files/dashboard.json
Labels: area/control-plane, bug

#219 HAP returning secrets to the pool
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/common/hyperscaler/account_pool.go
  components/kyma-environment-broker/common/hyperscaler/account_pool_test.go
  components/kyma-environment-broker/common/hyperscaler/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/account_provider_test.go
  components/kyma-environment-broker/common/hyperscaler/automock/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/shared_pool.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go
  components/subscription-cleanup-job/Dockerfile
  components/subscription-cleanup-job/Makefile
  components/subscription-cleanup-job/cmd/main.go
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
  components/subscription-cleanup-job/internal/cloudprovider/azure.go
  components/subscription-cleanup-job/internal/cloudprovider/factory.go
  components/subscription-cleanup-job/internal/cloudprovider/gcp.go
  components/subscription-cleanup-job/internal/cloudprovider/mocks/ProviderFactory.go
  components/subscription-cleanup-job/internal/job/cleaner.go
  components/subscription-cleanup-job/internal/job/cleaner_test.go
  components/subscription-cleanup-job/internal/model/types.go
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement

#234 Change Runtime pagination to page and limit
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/common/pagination/pagination.go
  components/kyma-environment-broker/internal/runtime/handler.go
  components/kyma-environment-broker/internal/runtime/handler_test.go
  components/kyma-environment-broker/internal/runtime/model.go
  components/kyma-environment-broker/internal/storage/dbsession/factory.go
  components/kyma-environment-broker/internal/storage/dbsession/read.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/storage_test.go
  resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
  resources/kcp/values.yaml
Labels: area/control-plane
