Repository kyma-project/control-plane, pull requests merged in 2020-10, with the labels that each got.

#255 Upgrade 'etcd' in Provisioner
  components/provisioner/go.mod
  components/provisioner/go.sum
Labels: area/security, hacktoberfest-accepted

#262 Adapt CIS client ver1 to the new response format
  components/kyma-environment-broker/internal/cis/client_ver_1.go
  components/kyma-environment-broker/internal/cis/client_ver_1_test.go
  components/kyma-environment-broker/internal/cis/model.go
  resources/kcp/values.yaml
Labels: area/control-plane

#273 keb runtimes endpoint
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/orchestration/handlers/converter.go
  components/kyma-environment-broker/internal/orchestration/handlers/converter_test.go
  components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler_test.go
  components/kyma-environment-broker/internal/orchestration/kyma/manager.go
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/runtime/handler.go
  components/kyma-environment-broker/internal/runtime/handler_test.go
  components/kyma-environment-broker/internal/storage/dbsession/factory.go
  components/kyma-environment-broker/internal/storage/dbsession/read.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/storage_test.go
Labels: area/management-plane

#284 Add stalebot to the control-plane repo
  .github/stale.yml
Labels: enhancement

#295 Add retries to Director calls
  components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion.go
  components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain_test.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/runtime/configuration_test.go
  components/provisioner/internal/runtime/configurator.go
  components/provisioner/internal/util/retry.go
  components/provisioner/internal/util/retry_test.go
  components/provisioner/internal/util/wait.go
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement

#299 Fix k8s.io/apiserver version in metris
  components/metris/go.mod
  components/metris/go.sum
  components/metris/internal/gardener/handlers.go
  components/metris/internal/gardener/handlers_test.go
Labels: area/control-plane
