Repository kyma-project/control-plane, pull requests merged in 2020-08, with the labels that each got.

#103 Change step AVS owner in KEB documentation
  docs/kyma-environment-broker/03-03-runtime-provisioning-and-deprovisioning.md
Labels: area/control-plane, documentation

#96 Map Director error codes in Provisioner error responses
  components/provisioner/Dockerfile
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/apperrors/apperrors.go
  components/provisioner/internal/apperrors/presenter.go
  components/provisioner/internal/director/directorclient.go
  components/provisioner/internal/director/directorclient_test.go
  components/provisioner/internal/graphql/client.go
  components/provisioner/internal/graphql/gql_client_testkit.go
  components/provisioner/internal/graphql/mocks/Client.go
  components/provisioner/third_party/machinebox/graphql/LICENSE
  components/provisioner/third_party/machinebox/graphql/README.md
  components/provisioner/third_party/machinebox/graphql/graphql.go
  components/provisioner/third_party/machinebox/graphql/graphql_json_test.go
  components/provisioner/third_party/machinebox/graphql/graphql_multipart_test.go
Labels: area/control-plane, area/management-plane, enhancement

#110 Render kcp documentation under kyma-project.io/docs/control-plane pages
  .kyma-project-io/build-preview.sh
  .kyma-project-io/docs-keb.cag.yaml
  .kyma-project-io/docs-provisioner-cag.yaml
  CODEOWNERS
  README.md
  docs/internal/README.md
  docs/internal/proposals/hyperscaler-account-pool-api-design.md
  docs/internal/proposals/provisioning-api.md
  docs/kyma-environment-broker/01-01-overview.md
  docs/kyma-environment-broker/02-01-architecture.md
  docs/kyma-environment-broker/02-02-broker-endpoints.md
  docs/kyma-environment-broker/03-01-service-description.md
  docs/kyma-environment-broker/03-02-runtime-components.md
  docs/kyma-environment-broker/03-03-runtime-provisioning-and-deprovisioning.md
  docs/kyma-environment-broker/03-04-hyperscaler-account-pool.md
  docs/kyma-environment-broker/03-05-authorization.md
  docs/kyma-environment-broker/03-06-runtime-overrides.md
  docs/kyma-environment-broker/03-07-environments-cleanup.md
  docs/kyma-environment-broker/08-01-provisioning-kyma-environment.md
  docs/kyma-environment-broker/08-02-deprovisioning-kyma-environment.md
  docs/kyma-environment-broker/08-03-operation-status.md
  docs/kyma-environment-broker/08-04-instance-details.md
  docs/provisioner/01-01-provisioner-overview.md
  docs/provisioner/05-01-app-entry-parameters.md
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-05-deprovisioning.md
Labels: area/control-plane, area/documentation, enhancement

#126 Remove the fork from test dependencies
  resources/kcp/values.yaml
  tests/provisioner-tests/Gopkg.lock
  tests/provisioner-tests/Gopkg.toml
Labels: enhancement

#130 Add post-review of the internal docs
  docs/internal/README.md
  docs/internal/investigations/KCP-runtime-management.md
  docs/internal/investigations/provisioning-custom-configuration.md
  docs/internal/investigations/runtime-governor-concept.md
  docs/internal/investigations/runtime-governor-poc/README.md
  docs/internal/investigations/runtime-governor-poc/governor/README.md
Labels: area/documentation, enhancement

#147 Quick docu fix
  docs/internal/README.md
Labels: area/documentation, bug

#149 Link fix
  docs/internal/investigations/runtime-governor-poc/README.md
Labels: area/documentation, bug

#151 Fix commands in runtime governor POC
  docs/internal/investigations/runtime-governor-poc/README.md
  docs/internal/investigations/runtime-governor-poc/governor/chart/templates/configmap.yaml
  docs/internal/investigations/runtime-governor-poc/governor/chart/values.yaml
Labels: area/control-plane, area/documentation

#160 Fix components download URLs in KEB
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
  resources/kcp/values.yaml
  tests/e2e/provisioning/internal/provisioner/components_provider.go
Labels: area/control-plane

#131 Add functionality to delete orphan instances
  components/kyma-environment-broker/Dockerfile.sac
  components/kyma-environment-broker/Makefile
  components/kyma-environment-broker/cmd/accountcleanup/main.go
  components/kyma-environment-broker/cmd/environmentscleanup/main.go
  components/kyma-environment-broker/internal/broker/client.go
  components/kyma-environment-broker/internal/broker/client_test.go
  components/kyma-environment-broker/internal/cis/account_cleanup.go
  components/kyma-environment-broker/internal/cis/account_cleanup_test.go
  components/kyma-environment-broker/internal/cis/automock/BrokerClient.go
  components/kyma-environment-broker/internal/cis/automock/CisClient.go
  components/kyma-environment-broker/internal/cis/client.go
  components/kyma-environment-broker/internal/cis/client_test.go
  components/kyma-environment-broker/internal/cis/client_ver_1.go
  components/kyma-environment-broker/internal/cis/client_ver_1_test.go
  components/kyma-environment-broker/internal/cis/e2e/account_cleanup_test.go
  components/kyma-environment-broker/internal/cis/e2e/cis_fake_server.go
  components/kyma-environment-broker/internal/cis/e2e/fake_broker_client.go
  components/kyma-environment-broker/internal/cis/e2e/tests_utils.go
  components/kyma-environment-broker/internal/cis/model.go
  components/kyma-environment-broker/internal/storage/dbsession/factory.go
  components/kyma-environment-broker/internal/storage/dbsession/read.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/storage_test.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
  resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/oauth-client.yaml
  resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
  scripts/generic_make_go.mk
Labels: area/control-plane, enhancement
