Repository kyma-project/control-plane, pull requests merged in 2021-11, with the labels that each got.

#1036 Fix schceduling -> scheduling typo
  tools/cli/pkg/command/reconciliation_info.go
Labels: size/XS, lgtm

#1034 Fixing errors in swagger yaml
  resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
Labels: bug, hacktoberfest-accepted, size/M, lgtm

#1039 Keb provides global configuration for all components
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1009 Reconciler payload persistence (postgres)
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  components/kyma-environment-broker/internal/storage/dbmodel/runtime_state.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtimestate_test.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  components/kyma-environment-broker/internal/storage/postsql/write.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
  components/schema-migrator/migrations/kyma-environment-broker/202141251610_add_reconciler_input.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202141251610_add_reconciler_input.up.sql
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1024 Secure internal communication with mothership and component-reconcilers
  resources/kcp/charts/component-reconcilers/templates/authorization.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/monitoring.yaml
  resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
  resources/kcp/charts/mothership-reconciler/templates/authorization.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/serviceaccount.yaml
  resources/kcp/values.yaml
Labels: area/control-plane, size/M, lgtm

#1044 Add NO_INSTALL env variables to the Provisioner
  components/provisioner/internal/operations/queue/queues_constructor.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: bug, area/control-plane, size/S, lgtm

#1038 Add reconciler delete functionality
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1042 KCP CLI: use KEB runtime state
  components/kyma-environment-broker/internal/orchestration/runtime_lister.go
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/runtime/handler.go
  resources/kcp/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/runtime.go
Labels: size/M, lgtm

#980 Install btp-operator when credentials provided
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/testdata/additional-runtime-components.yaml
  components/kyma-environment-broker/cmd/broker/testdata/kyma-components.yaml
  components/kyma-environment-broker/cmd/broker/testdata/kyma-installer-cluster.yaml
  components/kyma-environment-broker/cmd/broker/testdata/managed-runtime-components.yaml
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/input/automock/optional_component_service.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/automock/provisioner_input_creator.go
  components/kyma-environment-broker/internal/process/provisioning/base_provision_test.go
  components/kyma-environment-broker/internal/process/provisioning/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/conditions.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
  components/kyma-environment-broker/internal/runtime/export_test.go
  components/kyma-environment-broker/internal/runtime/opt_components_service.go
  components/kyma-environment-broker/internal/runtime/provider_fake.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
  components/kyma-environment-broker/internal/servicemanager/factory_test.go
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#1030 provisioner - synced with PR970 for DNS config
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1048 Update reconciler image tag
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1047 Update statuses allowed to call mothership
  components/mothership/README.MD
  components/mothership/go.mod
  components/mothership/go.sum
  components/mothership/makefile
  components/mothership/pkg/client_gen.go
  components/mothership/pkg/provider.go
  components/mothership/pkg/provider_test.go
  components/mothership/pkg/types_gen.go
  components/reconciler/pkg/automock/client.go
  components/reconciler/pkg/types_gen.go
  tools/cli/pkg/command/reconciliations.go
Labels: size/XXL, lgtm

#1050 Allow disabling istio resources regarding reconcilers components
  resources/kcp/charts/component-reconcilers/templates/authorization.yaml
  resources/kcp/charts/mothership-reconciler/templates/authorization.yaml
  resources/kcp/charts/mothership-reconciler/templates/virtualservice.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1046 Fix Upgrade
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/builder_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1040 Update KMC machine configuration for GCP
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/pkg/process/event_stream.go
  components/kyma-metrics-collector/pkg/process/public_cloud_info.go
  components/kyma-metrics-collector/pkg/process/public_cloud_info_test.go
  components/kyma-metrics-collector/pkg/testing/fixtures/static_providers.json
  resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1051 Update reconciler to include nil state update fix
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1054 Include reconciler resource replace change
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1057 Fix boolean global overrides
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1052 Add makefile for reconciler
  CODEOWNERS
  README.md
  resources/kcp/templates/migrator-job.yaml
  resources/kcp/values.yaml
  tools/reconciler/Makefile
Labels: size/M, lgtm

#1055 Bump kyma version to 1.24.8
  installation/resources/KYMA_VERSION
Labels: size/XS, lgtm

#1053 Fix containerd security issue
  components/kyma-environment-broker/Makefile
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1061 Change Asia region for GCP plan in KEB
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema.json
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1064 Preserve pod-preset certs via custom reconciler
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1063 Request Email and OpenID scopes in oidc-login
  components/kubeconfig-service/pkg/transformer/kubeconfig.go
  components/kubeconfig-service/pkg/transformer/transformer_test.go
  components/kyma-environment-broker/internal/kubeconfig/builder_test.go
  components/kyma-environment-broker/internal/kubeconfig/kubeconfig.go
  resources/kcp/values.yaml
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/S, lgtm

#1065 Move test scripts for reconciler
  tools/reconciler/e2e-test/get-reconcile-status.sh
  tools/reconciler/e2e-test/reconcile-kyma.sh
  tools/reconciler/e2e-test/request-reconcile.sh
  tools/reconciler/e2e-test/template.json
Labels: size/L, lgtm

#1068 change the rescheduleDelay to 0
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1070 Sanitize origin in the kubeconfig handler
  components/kyma-environment-broker/internal/kubeconfig/handler.go
Labels: size/XS, lgtm

#1071 Bump cloudsql-proxy img to v1.27.0
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1074 Image Bump
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1075 Tidy go modules
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/L, lgtm

#1078 Bump reconciler to a3fbfa81
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1076 bump gogo/protobuf to v1.3.2
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1084 Fix golang-runtime security issues
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/Dockerfile.sac
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1056 Add stop command to CLI
  components/reconciler/README.MD
  components/reconciler/go.mod
  components/reconciler/go.sum
  components/reconciler/makefile
  components/reconciler/pkg/automock/client.go
  components/reconciler/pkg/client_gen.go
  components/reconciler/pkg/response.go
  components/reconciler/pkg/response_test.go
  components/reconciler/pkg/types_gen.go
  tools/cli/.gitignore
  tools/cli/Makefile
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/operation.go
  tools/cli/pkg/command/operation_stop.go
  tools/cli/pkg/command/operation_stop_test.go
  tools/cli/pkg/command/reconciliations.go
  tools/cli/pkg/command/reconciliations_disable.go
Labels: size/XXL, lgtm

#1090 Fix Operation Stop when reconciler returnrs 404
  tools/cli/pkg/command/operation_stop.go
  tools/cli/pkg/command/operation_stop_test.go
Labels: size/M, lgtm

#1091 Bump reconciler image version
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1088 KEB waits for reconciler deletion
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration_step_test.go
  components/kyma-environment-broker/internal/reconciler/contract.go
  components/kyma-environment-broker/internal/reconciler/fake.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1093 Bump subaccount cleanup job deps
  components/subscription-cleanup-job/Dockerfile
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1092 Bump GO version for KMC
  components/kyma-metrics-collector/Dockerfile
  components/kyma-metrics-collector/Makefile
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1097 Fix namespace resolution for interceptors
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1066 Add reconciliation status check to KEB's upgrade process
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/testdata/kyma-components.yaml
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/common/orchestration/strategies/parallel.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/check_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/create_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1099 Remove migrate binary from reconciler image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1100 Fix check cluster deregistration
  components/kyma-environment-broker/internal/error/not_found_error.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration_test.go
  components/kyma-environment-broker/internal/reconciler/client.go
Labels: size/M, lgtm

#1102 bump KEB
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1104 Bump reconciler and mothership images
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1103 Update gjson dependency
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1105 KEB resumes update operations
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1107 Upgrade reconciler image tag
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1108 Revert "KEB resumes update operations"
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1086 Refactor the KEB orchestration operations queuing logic
  components/kyma-environment-broker/common/orchestration/strategies/parallel.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1109 KEB resumes 16 update operations
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1112 Append overrides based on unique override key
  components/kyma-environment-broker/internal/process/input/input.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1113 Fix shadowed error when getting latest runtimeState in upgrade queue
  components/kyma-environment-broker/internal/process/upgrade_kyma/create_cluster_configuration.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1106 kubeconfig-service: Update Golang version and deps. Change owners to SRE
  CODEOWNERS
  components/kubeconfig-service/Dockerfile
  components/kubeconfig-service/Makefile
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XXL, lgtm

#1110 Add liveness and readiness checks to reconciler
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1117 Bump reconciler image - fix race condition while creating workspaces
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1124 KEB runtimes state: set to succeeded by default when operation state doesn't match
  components/kyma-environment-broker/internal/runtime/handler.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1128 Improve test coverage for appending overrides
  components/kyma-environment-broker/internal/process/input/input_test.go
Labels: size/L, lgtm

#1120 Bump to latest reconciler version
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1129 Fix image for subaccount cleaner job
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1123 Provide missing overrides for upgrade to 2.0
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/process/provisioning/ias_registration.go
  components/kyma-environment-broker/internal/process/provisioning/ias_registration_test.go
  components/kyma-environment-broker/internal/process/provisioning/ias_type_step.go
  components/kyma-environment-broker/internal/process/provisioning/ias_type_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/conditions.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/create_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/internal_eval.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/sm_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/sm_overrides_test.go
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1059 Enable auditlog for mothership-reconciler
  resources/kcp/charts/mothership-reconciler/templates/auditlog-config.yaml
  resources/kcp/charts/mothership-reconciler/templates/auditlog-pvc.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/mr-fluentbit-cm.yaml
  resources/kcp/values.yaml
  tools/reconciler/Makefile
Labels: size/L, lgtm

#1131 Bump Go version in Subscription Cleanup Job and Provisioner
  components/provisioner/Dockerfile
  components/subscription-cleanup-job/Dockerfile
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1133 Make operation succeeded if reconciler succeeced for upgrade
  components/kyma-environment-broker/internal/process/upgrade_kyma/check_cluster_configuration.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1132 Update reconciler images
  resources/kcp/values.yaml
Labels: area/eventing, size/XS, lgtm

#1130 Process cluster deregistration error status
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1114 Change the JSON output format for the `kcp rc info` method
  components/reconciler/go.mod
  components/reconciler/go.sum
  components/reconciler/makefile
  components/reconciler/pkg/automock/client.go
  components/reconciler/pkg/client_gen.go
  components/reconciler/pkg/types_gen.go
  tools/cli/go.sum
  tools/cli/pkg/command/reconciliation_info.go
  tools/cli/pkg/command/reconciliation_info_test.go
  tools/cli/pkg/command/reconciliations.go
  tools/cli/pkg/command/testdata/configVersionResponse.json
  tools/cli/pkg/command/testdata/reconciliationInfoResponse.json
Labels: size/XL, lgtm

#1136 Fix audit log storage class
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1137 Empty audit log storage class
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1138 bump reconciler and configure parallel install
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1139 Conditional storage class name
  resources/kcp/charts/mothership-reconciler/templates/auditlog-pvc.yaml
Labels: size/XS, lgtm

#1142 Load all not finished at startup
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1135 Fill KymaConfig after upgrade
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler.go
  components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1140 Remove central monitoring integration from KEB
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/monitoring/mocks/Client.go
  components/kyma-environment-broker/internal/monitoring/monitoring.go
  components/kyma-environment-broker/internal/process/deprovisioning/monitoring_uninstall.go
  components/kyma-environment-broker/internal/process/deprovisioning/monitoring_uninstall_test.go
  components/kyma-environment-broker/internal/process/provisioning/monitoring_integration.go
  components/kyma-environment-broker/internal/process/provisioning/monitoring_integration_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/monitoring_upgrade.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/monitoring_upgrade_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/monitoring.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#1141 Expose port 15020 on reconciler service resources
  resources/kcp/charts/component-reconcilers/charts/rma-component-reconciler/templates/service.yaml
  resources/kcp/charts/component-reconcilers/charts/rma-component-reconciler/values.yaml
  resources/kcp/charts/component-reconcilers/templates/service.yaml
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/templates/service.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/S, lgtm

#1126 Adjust azure_lite autoScalerMax settings
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema.json
  components/kyma-environment-broker/internal/provider/azure_provider.go
  docs/kyma-environment-broker/03-01-service-description.md
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1146 Version Bump
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#970 DNS config added for SKR custom domain support
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/gardener/config.go
  components/kyma-environment-broker/common/gardener/dns_values.go
  components/kyma-environment-broker/common/gardener/dns_values_test.go
  components/kyma-environment-broker/common/gardener/testdata/dns-values.yaml
  components/kyma-environment-broker/common/hyperscaler/automock/account_provider.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/environmentscleanup/automock/BrokerClient.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/automock/provisioner_input_creator.go
  components/kyma-environment-broker/internal/process/provisioning/automock/runtime_version_configurator_for_provisioning.go
  components/kyma-environment-broker/internal/process/provisioning/base_provision_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_step.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
  components/kyma-environment-broker/internal/provisioner/client_test.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1118 Add serviceMonitor for mothership-reconciler
  resources/kcp/charts/mothership-reconciler/templates/authorization.yaml
  resources/kcp/charts/mothership-reconciler/templates/policy.yaml
  resources/kcp/charts/mothership-reconciler/templates/service-monitor.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1143 rename main folder according to golang standards
  tools/cli/Makefile
  tools/cli/cmd/kcp/main.go
  tools/cli/go.sum
Labels: size/L, lgtm

#1134 Upgrade kubernetes version on UpgradeRuntime and UpgradeShoot mutations
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/gardener/kubernetes_version_provider.go
  components/provisioner/internal/gardener/kubernetes_version_provider_test.go
  components/provisioner/internal/gardener/mocks/ShootClient.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/mocks/KubernetesVersionProvider.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1147 Create new deprovisioning operation instead of retrying failed one
  components/kyma-environment-broker/internal/broker/instance_deprovision.go
  components/kyma-environment-broker/internal/broker/instance_deprovision_test.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1085 Finetune Alerting for KMC
  resources/kcp/charts/kyma-metrics-collector/prometheus/alerts.yaml
  resources/kcp/charts/kyma-metrics-collector/prometheus/alerts_test.yaml
Labels: size/XS, lgtm

#1150 Version Bump
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1149 Bump golang image version to 1.17.3
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/Dockerfile.sac
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1153 Bump reconciler to latest image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1115 Configurable profiler for KEB
  components/kyma-environment-broker/README.md
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/profiler-pvc.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1155 Version Bump
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1151 Kcp reconciliations commands lists items in historical order
  tools/cli/pkg/command/reconciliations.go
  tools/cli/pkg/command/reconciliations_test.go
Labels: bug, area/cli, size/M, lgtm
