Repository kyma-project/control-plane, pull requests merged in 2021-09, with the labels that each got.

#907 Configurable auto-update (maintenance) settings in KEB
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#897 Fine tune metrics
  components/kyma-metrics-collector/pkg/edp/client.go
  components/kyma-metrics-collector/pkg/keb/client.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#887 Make provisioning of clusters without installing Kyma possible
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/api/validator.go
  components/provisioner/internal/api/validator_test.go
  components/provisioner/internal/gardener/auditlogging.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/gardener/shoot_reconciler.go
  components/provisioner/internal/metrics/in_progress_operations.go
  components/provisioner/internal/metrics/in_progress_operations_test.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/provisioning/install_kyma_test.go
  components/provisioner/internal/operations/stages/upgrade/upgrade_kyma_test.go
  components/provisioner/internal/provider-config-migrator/migrator_db_integration_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/runtime/configuration_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202139061413_drop_not_null_constraint_active_kyma_config_id.down.sql
  components/schema-migrator/migrations/provisioner/202139061413_drop_not_null_constraint_active_kyma_config_id.up.sql
  components/schema-migrator/migrations/provisioner/202139121058_add_provisioning_no_install_operation.up.sql
  components/schema-migrator/migrations/provisioner/202139121059_add_provisioning_no_install_operation.down.sql
  resources/kcp/values.yaml
Labels: enhancement, area/control-plane, size/XXL, lgtm

#910 Update Runtime Provisioner's documentation
  components/provisioner/README.md
  docs/provisioner/01-01-provisioner-overview.md
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-03-runtime-operation-status.md
  docs/provisioner/08-04-runtime-status.md
  docs/provisioner/08-05-deprovisioning.md
  docs/provisioner/08-06-upgrading-shoots.md
Labels: area/control-plane, size/M, lgtm

#909 extending shoot spec with DNS & Cert extensions
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#914 Determine Kyma's major version
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#915 Modify openstack provider configuration for CCEE
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/provider/openstack_provider.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#916 Remove AWS AZs not supporting all required machine types in KEB
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#918 Add ralikio to CODEOWNERS
  CODEOWNERS
Labels: area/control-plane, size/S, lgtm

#919 New components list
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/input/automock/component_list_provider.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/builder_test.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
  components/kyma-environment-broker/internal/runtime/testdata/kyma-components.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#895 Add AWS Account Resources Cleaner
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
  components/subscription-cleanup-job/internal/cloudprovider/aws.go
  components/subscription-cleanup-job/internal/cloudprovider/factory.go
Labels: size/XXL, lgtm

#926 Fix aws trial
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/aws_provider_test.go
Labels: size/L, lgtm

#921 Adjust HA plans and AWS supported zones
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema.json
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/aws_provider_test.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#923 KEB new additional components
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
  components/kyma-environment-broker/internal/runtime/testdata/additional-runtime-components.yaml
  resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#929 Bump cloudsql-proxy image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#859 collect provision_duration metrics
  components/kyma-environment-broker/internal/metrics/metrics.go
  components/kyma-environment-broker/internal/metrics/operation_duration.go
  components/kyma-environment-broker/internal/process/events.go
  components/kyma-environment-broker/internal/process/provisioning/staged_manager.go
  components/kyma-environment-broker/internal/process/provisioning/staged_manager_test.go
Labels: size/M, lgtm

#930 Bump alpine version in KEB
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.sac
  components/schema-migrator/Dockerfile
  resources/kcp/values.yaml
  tests/e2e/provisioning/Dockerfile
Labels: size/S, lgtm

#920 Update endpoint for autoscaler options for KEB
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
  resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#894 feature: VictoriaMetrics integration as component
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/monitoring/mocks/Client.go
  components/kyma-environment-broker/internal/monitoring/monitoring.go
  components/kyma-environment-broker/internal/process/deprovisioning/monitoring_uninstall.go
  components/kyma-environment-broker/internal/process/deprovisioning/monitoring_uninstall_test.go
  components/kyma-environment-broker/internal/process/provisioning/monitoring_integration.go
  components/kyma-environment-broker/internal/process/provisioning/monitoring_integration_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/monitoring_upgrade.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/monitoring_upgrade_test.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/monitoring.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#933 fix payload in keb upgrade docs
  docs/kyma-environment-broker/08-05-orchestrate-kyma-upgrade.md
Labels: size/S, lgtm

#934 Fix KEB monitoring integration step issues
  components/kyma-environment-broker/internal/monitoring/monitoring.go
  components/kyma-environment-broker/internal/process/deprovisioning/monitoring_uninstall.go
  components/kyma-environment-broker/internal/process/provisioning/monitoring_integration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/monitoring_upgrade.go
  resources/kcp/charts/kyma-environment-broker/templates/monitoring.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm

#935 update base image to update go
  components/kyma-metrics-collector/Dockerfile
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#912 Keb preview steps
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster_test.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/automock/provisioner_input_creator.go
  components/kyma-environment-broker/internal/process/provisioning/base_provision_test.go
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration.go
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration_test.go
  components/kyma-environment-broker/internal/process/provisioning/conditions.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_step.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
  components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_test.go
  components/kyma-environment-broker/internal/process/provisioning/staged_manager.go
  components/kyma-environment-broker/internal/process/provisioning/staged_manager_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/conditions.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/get_kubeconfig_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/manager.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/manager_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  components/kyma-environment-broker/internal/reconciler/client.go
  components/kyma-environment-broker/internal/reconciler/client_int_test.go
  components/kyma-environment-broker/internal/reconciler/client_test.go
  components/kyma-environment-broker/internal/reconciler/contract.go
  components/kyma-environment-broker/internal/reconciler/fake.go
  components/kyma-environment-broker/internal/runtime/disabled_components.go
  docs/kyma-environment-broker/02-01-architecture.md
  docs/kyma-environment-broker/03-01-service-description.md
  docs/kyma-environment-broker/03-03-runtime-operations.md
  docs/kyma-environment-broker/assets/keb-architecture.svg
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XXL, lgtm

#939 Bump KEB (enable preview plan)
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#940 Change log level of Audit logging setup to warn
  components/provisioner/internal/gardener/shoot_reconciler.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#941 One KEB stage for provisioning steps
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
  components/kyma-environment-broker/internal/process/provisioning/staged_manager.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm

#938 Fix apk repository for curl
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.sac
  components/schema-migrator/Dockerfile
  resources/kcp/values.yaml
Labels: size/S, lgtm

#944 Bump Alpine in Provisioner
  components/provisioner/Dockerfile
  resources/kcp/values.yaml
Labels: area/control-plane, size/XS, lgtm

#943 Update plan schema in KEB
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/services.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#945 Add reconciler to control-plane
  resources/kcp/charts/component-reconcilers/Chart.yaml
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/charts/component-reconcilers/templates/rbac.yaml
  resources/kcp/charts/component-reconcilers/templates/service.yaml
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/.helmignore
  resources/kcp/charts/mothership-reconciler/Chart.yaml
  resources/kcp/charts/mothership-reconciler/files/reconciler.yaml
  resources/kcp/charts/mothership-reconciler/templates/_helpers.tpl
  resources/kcp/charts/mothership-reconciler/templates/cr-configmap.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/mr-encryption-key-secret.yaml
  resources/kcp/charts/mothership-reconciler/templates/mr-secret.yaml
  resources/kcp/charts/mothership-reconciler/templates/service.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/requirements.yaml
  resources/kcp/values.yaml
  tools/kcp-installer/kcp.Dockerfile
Labels: size/L, lgtm

#948 bump alpine to eu.gcr.io/kyma-project/external/alpine:3.14.2
  components/kubeconfig-service/Dockerfile
Labels: size/XS, lgtm

#947 Document KEB update parameters
  docs/kyma-environment-broker/03-01-service-description.md
Labels: size/M, lgtm
