Repository kyma-project/control-plane, pull requests merged in 2021-10, with the labels that each got.

#949 fix reco images
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#951 fix reco args
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#952 fix secret key
  resources/kcp/charts/mothership-reconciler/templates/mr-encryption-key-secret.yaml
Labels: size/XS, lgtm

#953 Add exposure class name to graphqlizer
  components/kyma-environment-broker/internal/provider/openstack_provider.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
Labels: size/L, lgtm

#950 Unit tests for update plans schema in KEB
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/testdata/update-aws-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-trial-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema.json
Labels: size/L, lgtm

#957 set keb value
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#955 update kubeconfig-service image after alpine bump
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XS, lgtm

#956 Remove code for governor PoC
  docs/internal/investigations/runtime-governor-poc/runtime/component/.gitignore
  docs/internal/investigations/runtime-governor-poc/runtime/component/Dockerfile
  docs/internal/investigations/runtime-governor-poc/runtime/component/cmd/main.go
  docs/internal/investigations/runtime-governor-poc/runtime/component/deploy.sh
  docs/internal/investigations/runtime-governor-poc/runtime/component/go.mod
  docs/internal/investigations/runtime-governor-poc/runtime/component/go.sum
  docs/internal/investigations/runtime-governor-poc/runtime/component/internal/dapr/client.go
  docs/internal/investigations/runtime-governor-poc/runtime/component/internal/kcp/client.go
Labels: size/XXL, lgtm

#959 Rename istio prereq to istio-configuration
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/values.yaml
Labels: area/control-plane, hacktoberfest-accepted, size/XS, lgtm

#963 Update reconciler chart after the refactor
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/files/reconciler.yaml
  resources/kcp/charts/mothership-reconciler/templates/_helpers.tpl
  resources/kcp/charts/mothership-reconciler/templates/cr-configmap.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: area/control-plane, hacktoberfest-accepted, size/M, lgtm

#964 Fix monitoring steps
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/process/deprovisioning/monitoring_uninstall.go
  components/kyma-environment-broker/internal/process/provisioning/monitoring_integration.go
  components/kyma-environment-broker/internal/process/provisioning/monitoring_integration_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/monitoring_upgrade.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/monitoring_upgrade_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#968 Default PlanID from instance details for update when request doesn't specify any
  components/kyma-environment-broker/internal/broker/instance_update.go
Labels: size/XS, lgtm

#962 Add OIDC params in schemas
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/appinfo/runtime_info.go
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/services.go
  components/kyma-environment-broker/internal/broker/services_test.go
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/azure-trial-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/free-aws-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/free-azure-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/openstack-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-ha-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-ha-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-trial-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-aws-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-oidc.json
  components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema-oidc.json
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#973 Keb component source for reconciler
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/reconciler/contract.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#975 Describe mapping between plan name and plan id for service plans
  docs/kyma-environment-broker/03-01-service-description.md
Labels: documentation, area/documentation, area/control-plane, size/S, lgtm

#866 Change StatusResponse struct to have targets and details info
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/orchestration_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/orchestration/dto.go
  components/kyma-environment-broker/internal/orchestration/config.go
  components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler_test.go
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#991 KEB does not retry cluster config creation
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#992 Adding e2e-provisioning-ha-aws.yaml and updateing values.yaml with ha_aws plan id
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-ha-aws.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#994 Fix nil pointer panic in orchestration manager
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#982 Remove unused Service Manager Offering steps in KEB
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/connectivity_deprovision.go
  components/kyma-environment-broker/internal/process/deprovisioning/connectivity_deprovision_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/connectivity_unbind.go
  components/kyma-environment-broker/internal/process/deprovisioning/connectivity_unbind_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/xsuaa_deprovision_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/xsuaa_deprovision_step_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/xsuaa_int_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/xsuaa_unbind_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/xsuaa_unbind_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/connectivity_bind.go
  components/kyma-environment-broker/internal/process/provisioning/connectivity_bind_test.go
  components/kyma-environment-broker/internal/process/provisioning/connectivity_provision.go
  components/kyma-environment-broker/internal/process/provisioning/connectivity_provision_test.go
  components/kyma-environment-broker/internal/process/provisioning/service_manager_offering_step.go
  components/kyma-environment-broker/internal/process/provisioning/service_manager_offering_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/service_manager_provisioner.go
  components/kyma-environment-broker/internal/process/provisioning/xsuaa_binding_step.go
  components/kyma-environment-broker/internal/process/provisioning/xsuaa_int_test.go
  components/kyma-environment-broker/internal/process/provisioning/xsuaa_provisioning_step.go
  components/kyma-environment-broker/internal/process/provisioning/xsuaa_provisioning_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/connectivity_bind.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/connectivity_bind_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/connectivity_provision.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/connectivity_provision_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/service_manager_offering_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/service_manager_offering_step_test.go
  components/kyma-environment-broker/internal/servicemanager/xsuaa/parameters.go
  components/kyma-environment-broker/internal/servicemanager/xsuaa/parameters_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#987 Reconciler payload persistence (memory)
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration_step_test.go
  components/kyma-environment-broker/internal/storage/dbmodel/runtime_state.go
  components/kyma-environment-broker/internal/storage/driver/memory/runtime_state.go
  components/kyma-environment-broker/internal/storage/driver/memory/runtime_state_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
  components/kyma-environment-broker/internal/storage/ext.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#998 Update reconciler chart
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#971 Implement commands which allow users to disable and enable reconciliation for a cluster
  .gitignore
  CODEOWNERS
  components/reconciler/README.MD
  components/reconciler/go.mod
  components/reconciler/go.sum
  components/reconciler/makefile
  components/reconciler/pkg/client_gen.go
  components/reconciler/pkg/provider.go
  components/reconciler/pkg/provider_test.go
  components/reconciler/pkg/types_gen.go
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/options.go
  tools/cli/pkg/command/reconciliations.go
  tools/cli/pkg/command/reconciliations_disable.go
  tools/cli/pkg/command/reconciliations_disable_test.go
  tools/cli/pkg/command/reconciliations_enable.go
  tools/cli/pkg/command/reconciliations_enable_test.go
  tools/cli/pkg/command/root.go
Labels: documentation, enhancement, area/control-plane, hacktoberfest-accepted, size/XXL, lgtm

#1003 DEfine lite plan for EDP
  components/kyma-environment-broker/internal/process/provisioning/edp_registration.go
  components/kyma-environment-broker/internal/process/provisioning/edp_registration_test.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1004 Update reconciler chart
  resources/kcp/values.yaml
Labels: size/XS, lgtm
