Repository kyma-project/control-plane, pull requests merged in 2021-04, with the labels that each got.

#626 Remove insensitive terms
  .github/pull-request-template.md
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  components/kyma-environment-broker/CODE_OF_CONDUCT.md
  components/kyma-environment-broker/CONTRIBUTING.md
  components/kyma-environment-broker/README.md
  components/provisioner/README.md
  docs/README.md
  docs/kyma-environment-broker/02-02-broker-endpoints.md
  docs/kyma-environment-broker/03-02-runtime-components.md
  docs/kyma-environment-broker/03-03-runtime-operations.md
  docs/kyma-environment-broker/03-08-kyma-versions.md
  docs/kyma-environment-broker/03-11-swagger.md
  docs/provisioner/01-01-provisioner-overview.md
  scripts/README.md
  tests/e2e/provisioning/README.md
Labels: area/documentation

#637 Delete KEBs fork from the e2e test
  resources/kcp/values.yaml
  tests/e2e/provisioning/Gopkg.lock
  tests/e2e/provisioning/Gopkg.toml
Labels: area/control-plane

#633 New way of setting audit logging tenant
  components/provisioner/internal/api/fake/seeds/gardener_client.go
  components/provisioner/internal/api/fake/shoots/gardener_client.go
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/testdata/config.json
  components/provisioner/internal/api/testdata/crd/seed.crd.yaml
  components/provisioner/internal/gardener/auditlogging.go
  components/provisioner/internal/gardener/auditlogging_test.go
  components/provisioner/internal/gardener/shoot_controller.go
  components/provisioner/internal/gardener/shoot_reconciler.go
  components/provisioner/internal/gardener/testdata/config.json
  resources/kcp/values.yaml
Labels: area/control-plane

#641 Add adjustment to the runtime name
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement

#650 Upgrade Alpine version in Runtime Provisioner
  components/provisioner/Dockerfile
  resources/kcp/values.yaml
Labels: area/control-plane, area/security

#652 Rename master to main
  docs/kyma-environment-broker/03-05-authorization.md
Labels: area/documentation

#664 Change master to main
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler_test.go
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
  components/provisioner/internal/installation/release/gcs_downloader.go
  components/provisioner/internal/installation/release/gcs_downloader_test.go
  docs/cli/commands/kcp_upgrade_kyma.md
  docs/kyma-environment-broker/03-08-kyma-versions.md
  installation/cmd/run.sh
  installation/resources/README.md
  installation/scripts/generate-installer-artifacts.sh
  resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
  tools/cli/pkg/command/upgrade_kyma.go
Labels: enhancement

#668 Remove LMS implementation
  components/kyma-environment-broker/README.md
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/lms/automock/tenant_creator.go
  components/kyma-environment-broker/internal/lms/client.go
  components/kyma-environment-broker/internal/lms/client_fake.go
  components/kyma-environment-broker/internal/lms/client_int_test.go
  components/kyma-environment-broker/internal/lms/client_test.go
  components/kyma-environment-broker/internal/lms/tenant.go
  components/kyma-environment-broker/internal/lms/tenant_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/audit_log_step.go
  components/kyma-environment-broker/internal/process/provisioning/audit_log_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/ems_provision_test.go
  components/kyma-environment-broker/internal/process/provisioning/lms_activation_step.go
  components/kyma-environment-broker/internal/process/provisioning/lms_activation_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/lms_cert_step.go
  components/kyma-environment-broker/internal/process/provisioning/lms_cert_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/lms_tenant_step.go
  components/kyma-environment-broker/internal/process/provisioning/lms_tenant_step_test.go
  components/kyma-environment-broker/internal/storage/dbmodel/lms.go
  components/kyma-environment-broker/internal/storage/driver/memory/lms_tenant.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/lms_tenant.go
  components/kyma-environment-broker/internal/storage/driver/postsql/lmstenant_test.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/init.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  components/kyma-environment-broker/internal/storage/postsql/write.go
  components/kyma-environment-broker/internal/storage/storage.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
  docs/kyma-environment-broker/03-01-service-description.md
  docs/kyma-environment-broker/03-03-runtime-operations.md
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: area/logging

#612 Cloud Connectivity Service Provisioning
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/connectivity_deprovision.go
  components/kyma-environment-broker/internal/process/deprovisioning/connectivity_deprovision_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/connectivity_unbind.go
  components/kyma-environment-broker/internal/process/deprovisioning/connectivity_unbind_test.go
  components/kyma-environment-broker/internal/process/provision_operation.go
  components/kyma-environment-broker/internal/process/provisioning/connectivity_bind.go
  components/kyma-environment-broker/internal/process/provisioning/connectivity_bind_test.go
  components/kyma-environment-broker/internal/process/provisioning/connectivity_provision.go
  components/kyma-environment-broker/internal/process/provisioning/connectivity_provision_test.go
  components/kyma-environment-broker/internal/process/provisioning/ems_provision.go
  components/kyma-environment-broker/internal/process/provisioning/service_manager_offering_step.go
  components/kyma-environment-broker/internal/process/provisioning/service_manager_provisioner.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/connectivity_bind.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/connectivity_bind_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/connectivity_provision.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/connectivity_provision_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/ems_provision.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/service_manager_offering_step.go
  components/kyma-environment-broker/internal/runtime/components/components.go
  components/kyma-environment-broker/internal/servicemanager/fake.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: enhancement

#692 Upgrade Provisioner image
  resources/kcp/values.yaml
Labels: area/control-plane

#691 Changed base image to distroless
  components/kyma-metrics-collector/Dockerfile
  resources/kcp/values.yaml
Labels: area/control-plane

#697 Bump Golang version in Provisioner
  components/provisioner/Dockerfile
  components/provisioner/Makefile
  components/provisioner/go.mod
  resources/kcp/values.yaml
Labels: area/control-plane

#698 Tuned readme for KMC
  components/kyma-metrics-collector/README.md
Labels: lgtm

#671 Add Azure HA plan
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/hyperscaler/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/azure/env.go
  components/kyma-environment-broker/common/hyperscaler/azure/env_test.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/plans_validator.go
  components/kyma-environment-broker/internal/broker/plans_validator_test.go
  components/kyma-environment-broker/internal/broker/services_test.go
  components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema.json
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/builder_test.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider_test.go
  components/kyma-environment-broker/internal/provider/common.go
  components/kyma-environment-broker/internal/runtime/disabled_components.go
  resources/kcp/charts/kyma-environment-broker/files/catalog.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: lgtm

#700 Fix subaccount cleaner job
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
Labels: lgtm, size/XS

#629 Cluster upgrade orchestration, part 3
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/runtime/handler.go
Labels: lgtm, size/M

#703 Keb more logs
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#702 Hydroform Version Bump
  components/provisioner/go.mod
Labels: lgtm, size/XS

#706 KEB do not finish pending provisioning operations
  components/kyma-environment-broker/internal/process/provisioning/manager.go
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#705 Add svc for kmc
  resources/kcp/charts/kyma-metrics-collector/templates/deployment.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/service.yaml
  resources/kcp/charts/kyma-metrics-collector/values.yaml
Labels: lgtm, size/S
