Repository kyma-project/control-plane, pull requests merged in 2021-06, with the labels that each got.

#773 Bump schema migrator base alpine image
  components/schema-migrator/Dockerfile
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#758 Added instanceID to cli
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/options.go
  tools/cli/pkg/command/orchestration.go
Labels: lgtm, size/L

#775 Use stored provider in KEB deprovisioning
  components/kyma-environment-broker/common/hyperscaler/account_provider.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  resources/kcp/values.yaml
Labels: lgtm, size/M

#776 Overrides version input
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
  components/kyma-environment-broker/internal/runtimeoverrides/runtimeoverrides.go
  resources/kcp/values.yaml
Labels: lgtm, size/L

#788 remove oidcClientSecret from required global options list
  tools/cli/pkg/command/options.go
  tools/cli/pkg/command/root.go
Labels: lgtm, size/XS

#787 Fix compass_keb_upgrade_cluster_result metric
  components/kyma-environment-broker/internal/metrics/operation_result.go
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#785 Enable OIDC authcode + PKCE flow in kubeconfig-service
  components/kubeconfig-service/pkg/endpoints/endpoint.go
  components/kubeconfig-service/pkg/env/env.go
  components/kubeconfig-service/pkg/transformer/kubeconfig.go
  components/kubeconfig-service/pkg/transformer/transformer.go
  components/kubeconfig-service/pkg/transformer/transformer_test.go
  resources/oidc-kubeconfig-service/templates/deployment.yaml
  resources/oidc-kubeconfig-service/values.yaml
Labels: lgtm, size/M

#786 Update KEB dependencies
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/hyperscaler/account_pool.go
  components/kyma-environment-broker/common/hyperscaler/account_pool_test.go
  components/kyma-environment-broker/common/hyperscaler/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/account_provider_test.go
  components/kyma-environment-broker/common/hyperscaler/shared_pool.go
  components/kyma-environment-broker/common/orchestration/resolver.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/environmentscleanup/automock/GardenerClient.go
  components/kyma-environment-broker/internal/environmentscleanup/service.go
  resources/kcp/values.yaml
Labels: lgtm, size/XL

#781 KEB Resolve user (email) of the runtime creator (#766) - normalization
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#783 Set Kyma service bindable field to false
  components/kyma-environment-broker/internal/broker/services.go
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#769 Self-service for configuring custom OIDC
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/util/testkit/shoot.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202131051400_oidc_config.down.sql
  components/schema-migrator/migrations/provisioner/202131051400_oidc_config.up.sql
  resources/kcp/values.yaml
Labels: lgtm, size/XL

#791 Update cloudsql-docker/gce-proxy to 1.23.0-alpine
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#800 Add kubeconfig path to VirtualService
  resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
Labels: lgtm, size/S

#801 Don't allow unavailable nodes during trial cluster upgrades
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/openstack_provider.go
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#802 Use secrets for auditlog
  components/kyma-environment-broker/internal/process/provisioning/audit_log_step.go
  components/kyma-environment-broker/internal/process/provisioning/audit_log_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/audit_log.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/audit_log_test.go
Labels: lgtm, size/M

#803 Bump KEB image
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#799 Self-service for overriding admin user
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/Factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement, lgtm, size/L

#779 Add oidc to provisioning params
  components/kyma-environment-broker/Makefile
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  docs/kyma-environment-broker/03-12-custom-oidc-configuration.md
  resources/kcp/values.yaml
Labels: lgtm, size/L

#782 update kyma_version to 1.22.1
  installation/resources/COMPASS_VERSION
  installation/resources/KYMA_VERSION
  installation/resources/installer-overrides-compass.yaml
  installation/scripts/testing.sh
Labels: lgtm, size/S

#806 Self service for overriding admin user
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#699 Provisioning AWS HA runtimes
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/avs/model.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/services_test.go
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/aws_provider_test.go
  components/kyma-environment-broker/internal/provider/common.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  components/kyma-environment-broker/internal/provisioner/query.go
  components/kyma-environment-broker/internal/runtime/disabled_components.go
  components/kyma-environment-broker/internal/servicemanager/xsuaa/parameters.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/model/infrastructure.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/provider-config-migrator/migrator.go
  components/provisioner/internal/provider-config-migrator/migrator_db_integration_test.go
  components/provisioner/internal/provider-config-migrator/migrator_test.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/util/json.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/provider_config_test.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  resources/kcp/charts/kyma-environment-broker/files/catalog.yaml
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
Labels: lgtm, size/XXL

#810 Hotfix AVS eval creation step in KEB
  components/kyma-environment-broker/internal/avs/model.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#811 Remove IsBEBEnabled flag
  components/kyma-environment-broker/internal/process/provisioning/ems_bind.go
  resources/kcp/values.yaml
Labels: area/control-plane, area/eventing, lgtm, size/XS

#812 Support client credential login in CLI; Support multiple OIDC clients on KEB endpoints
  resources/kcp/charts/kyma-environment-broker/templates/oathkeeper-rule.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  tools/cli/pkg/command/login.go
  tools/cli/pkg/command/options.go
  tools/cli/pkg/command/root.go
  tools/cli/pkg/credential/manager.go
Labels: lgtm, size/S

#814 Add sending ServicePlan parameter to the EDP step
  components/kyma-environment-broker/internal/edp/client.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration_test.go
  components/kyma-environment-broker/internal/process/provisioning/edp_registration.go
  components/kyma-environment-broker/internal/process/provisioning/edp_registration_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/M

#808 Change email to userid
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/model/kyma_config.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202131060900_rename_administrators_email.down.sql
  components/schema-migrator/migrations/provisioner/202131060900_rename_administrators_email.up.sql
  resources/kcp/values.yaml
Labels: lgtm, size/S

#815 Update the provisioning tutorial with multiple zones for AWS
  docs/provisioner/08-02-provisioning-gardener.md
Labels: area/control-plane, area/documentation, documentation, lgtm, size/S

#817 Remove artifacts downloader from Provisioner
  components/provisioner/cmd/main.go
  components/provisioner/internal/installation/release/gcs_downloader_test.go
  components/provisioner/internal/installation/release/github_downloader.go
  components/provisioner/internal/installation/release/github_downloader_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/L

#816 Bump alpine version in cloudsql proxy image
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#805 Return recoverable error when reconcile operation fails during provisioning
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#820 Add CORS headers to the kubeconfig endpoint
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/kubeconfig/builder.go
  components/kyma-environment-broker/internal/kubeconfig/handler.go
  components/kyma-environment-broker/internal/kubeconfig/handler_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: lgtm, size/L
