Repository kyma-project/control-plane, pull requests merged in 2021-07, with the labels that each got.

#804 change avs monitor naming convention on create
  components/kyma-environment-broker/internal/avs/model.go
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#809 Update KEB service description docs
  docs/kyma-environment-broker/03-01-service-description.md
Labels: lgtm, size/L

#823 Add auto generate property to KEB plans schemas
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-trial-schema.json
  components/kyma-environment-broker/internal/broker/testdata/free-aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/free-azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema.json
  components/kyma-environment-broker/internal/broker/testdata/openstack-schema.json
Labels: lgtm, size/L

#667 Metrics and Alerting for Metris
  components/kyma-metrics-collector/Makefile
  components/kyma-metrics-collector/README.md
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/pkg/edp/client.go
  components/kyma-metrics-collector/pkg/edp/client_test.go
  components/kyma-metrics-collector/pkg/edp/metrics.go
  components/kyma-metrics-collector/pkg/gardener/commons/metrics.go
  components/kyma-metrics-collector/pkg/gardener/secret/client.go
  components/kyma-metrics-collector/pkg/gardener/secret/client_test.go
  components/kyma-metrics-collector/pkg/gardener/shoot/client.go
  components/kyma-metrics-collector/pkg/gardener/shoot/client_test.go
  components/kyma-metrics-collector/pkg/keb/client.go
  components/kyma-metrics-collector/pkg/keb/client_test.go
  components/kyma-metrics-collector/pkg/keb/metrics.go
  components/kyma-metrics-collector/pkg/process/metrics.go
  components/kyma-metrics-collector/pkg/process/process.go
  components/kyma-metrics-collector/pkg/process/process_test.go
  components/kyma-metrics-collector/pkg/skr/commons/metrics.go
  components/kyma-metrics-collector/pkg/skr/node/client.go
  components/kyma-metrics-collector/pkg/skr/node/client_test.go
  components/kyma-metrics-collector/pkg/skr/pvc/client.go
  components/kyma-metrics-collector/pkg/skr/pvc/client_test.go
  components/kyma-metrics-collector/pkg/skr/svc/client.go
  components/kyma-metrics-collector/pkg/skr/svc/client_test.go
  resources/kcp/charts/kyma-metrics-collector/prometheus/alerts.yaml
  resources/kcp/charts/kyma-metrics-collector/prometheus/alerts_test.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/_helpers.tpl
  resources/kcp/charts/kyma-metrics-collector/templates/prometheusrule.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/service-monitor.yaml
  resources/kcp/charts/kyma-metrics-collector/values.yaml
  resources/kcp/values.yaml
Labels: lgtm, size/XL

#827 Change Azure HA AutoscalerMax parameter in docs
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
  docs/kyma-environment-broker/03-01-service-description.md
Labels: lgtm, size/S

#828 Define deprovisioning timeout in KEB
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: lgtm, size/M

#829 Make default trial provider in KEB configurable
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: lgtm, size/XS

#813 KEB OIDC default values
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/builder_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
  components/kyma-environment-broker/internal/runtime/oidc_values.go
  components/kyma-environment-broker/internal/runtime/oidc_values_test.go
  components/kyma-environment-broker/internal/runtime/testdata/oidc-values.yaml
  docs/kyma-environment-broker/03-12-custom-oidc-configuration.md
  resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: lgtm, size/XL

#830 Move freemium SKRs from production AVS group to trial AVS group
  components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/process/provisioning/external_eval_step.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#835 Fix OIDC mandatory fields validation
  components/kyma-environment-broker/internal/broker/instance_create.go
Labels: lgtm, size/XS

#789 Remove m4 machine type support
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
Labels: lgtm, size/XS

#841 Fix KEB freemium zones
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#843 Change log levels for recoverable errors
  components/provisioner/internal/operations/executor.go
  components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_installation.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#837 Cleanup code owners
  .kyma-project-io/build-preview.sh
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
  resources/kcp/OWNERS
Labels: lgtm, size/S

#844 Add async parameter to patch requests in e2e tests
  resources/kcp/values.yaml
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
Labels: lgtm, size/XS

#842 Reconfigure runtime (upsert secret) on Compass ConnectionFailed
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect_test.go
  components/provisioner/internal/runtime/configuration_test.go
  components/provisioner/internal/runtime/configurator.go
  resources/kcp/values.yaml
Labels: lgtm, size/L

#824 Add instanceID busola-migrator override
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/provisioning/busola_migrator_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/busola_migrator_overrides_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/busola_migrator_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/busola_migrator_overrides_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/ems_prov_int_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/L

#848 Bump Provisioner to the main version
  resources/kcp/values.yaml
Labels: area/control-plane, lgtm, size/XS

#855 Bump k8s to 1.19.12 and go.uuid to latest master in KEB
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: lgtm, size/M

#849 Add support for missing plans in KCP CLI
  tools/cli/pkg/command/options.go
Labels: lgtm, size/XS

#850 Remove async execution of suspension context update in e2e test
  resources/kcp/values.yaml
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
Labels: lgtm, size/M

#852 Fix for deprovisioning workflow
  components/kyma-metrics-collector/pkg/edp/client.go
  components/kyma-metrics-collector/pkg/keb/client.go
  components/kyma-metrics-collector/pkg/keb/client_test.go
  components/kyma-metrics-collector/pkg/process/process.go
  components/kyma-metrics-collector/pkg/process/process_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/L

#822 KEB: next-gen runtimes endpoint
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/common/orchestration/resolver.go
  components/kyma-environment-broker/common/orchestration/resolver_test.go
  components/kyma-environment-broker/common/runtime/client.go
  components/kyma-environment-broker/common/runtime/client_test.go
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/runtime/handler.go
  components/kyma-environment-broker/internal/runtime/handler_test.go
  components/kyma-environment-broker/internal/storage/dbmodel/instance.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  components/kyma-environment-broker/internal/storage/driver/memory/runtime_state.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/values.yaml
Labels: lgtm, size/XL

#857 Bump alpine to v3.14.0
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.sac
  resources/kcp/values.yaml
  tests/e2e/provisioning/Dockerfile
Labels: lgtm, size/S

#821 Randomize maintenance window for non-porduction clusters
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/M

#862 Update CODEOWNERS
  CODEOWNERS
Labels: lgtm, size/S

#870 Remove EMS related code
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/ems_deprovision.go
  components/kyma-environment-broker/internal/process/deprovisioning/ems_deprovision_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/ems_dprov_int_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/ems_unbind.go
  components/kyma-environment-broker/internal/process/deprovisioning/ems_unbind_test.go
  components/kyma-environment-broker/internal/process/provisioning/base_provision_test.go
  components/kyma-environment-broker/internal/process/provisioning/ems_bind.go
  components/kyma-environment-broker/internal/process/provisioning/ems_bind_test.go
  components/kyma-environment-broker/internal/process/provisioning/ems_prov_int_test.go
  components/kyma-environment-broker/internal/process/provisioning/ems_provision.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/ems_bind.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/ems_bind_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/ems_prov_int_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/ems_provision.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/ems_provision_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: area/control-plane, lgtm, size/XXL

#867 Add voigt and wozniakjan to all KEB related directories
  CODEOWNERS
Labels: lgtm, size/S

#871 Add freemium metrics
  components/kyma-environment-broker/internal/metrics/operations_collector.go
Labels: lgtm, size/XS

#853 Remove unused function from HAP
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/hyperscaler/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/account_provider_test.go
  components/kyma-environment-broker/common/hyperscaler/automock/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/azure/env.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds_test.go
  resources/kcp/values.yaml
  tests/e2e/provisioning/Gopkg.lock
  tests/e2e/provisioning/internal/hyperscaler/account_pool.go
  tests/e2e/provisioning/internal/hyperscaler/account_provider.go
  tests/e2e/provisioning/test/test_suite.go
Labels: area/control-plane, enhancement, lgtm, size/XL

#869 Add possibility to pass exposureClassName parameter
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/fake/shoots/gardener_client.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/util/testkit/shoot.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/README.md
  components/schema-migrator/migrations/provisioner/202138271041_add_exposure_class_name.down.sql
  components/schema-migrator/migrations/provisioner/202138271041_add_exposure_class_name.up.sql
  components/schema-migrator/migrations/provisioner/202201010000_return_to_standard_naming_convention.sql
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-06-upgrading-shoots.md
  resources/kcp/values.yaml
Labels: area/control-plane, enhancement, lgtm, size/L

#845 KEB runtime administrators list parameter
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/L

#832 Added versioning to E2E tests with new upgrade test template
  resources/kcp/charts/kyma-environment-broker/templates/tests/upg-tst-aws-prov.yaml
  resources/kcp/values.yaml
  tests/e2e/provisioning/test/e2e_upgrade_test.go
  tests/e2e/provisioning/test/test_suite.go
Labels: lgtm, size/L

#851 use plan_id as metric label instead of using plan_name in metric name
  components/kyma-environment-broker/internal/metrics/operations_collector.go
Labels: lgtm, size/M

#872 remove the compass-installer step in /cmd/run.sh
  installation/cmd/run.sh
Labels: lgtm, size/XS
