Repository kyma-project/control-plane, pull requests merged in 2021-02, with the labels that each got.

#475 Saving gardener shoot cluster seed to the database
  components/provisioner/internal/api/fake/gardener_client.go
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/testdata/config.json
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
Labels: area/control-plane, bug

#503 Tidy Provisioners go sum
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/values.yaml
Labels: area/control-plane

#509 Update documentation for the new EMS step
  docs/kyma-environment-broker/03-03-runtime-operations.md
Labels: area/control-plane, area/documentation, area/eventing

#516 Upgrade `golang.org/x/text` in `subscription-cleanup-job`
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
Labels: area/control-plane, area/security

#521 Bump image for 'subscription-cleanup-job'
  resources/kcp/values.yaml
Labels: area/control-plane, area/quality

#465 KEB: Implement CLS provisioning
  components/kyma-environment-broker/internal/cls/automock/instance_creator.go
  components/kyma-environment-broker/internal/cls/automock/provisioner_storage.go
  components/kyma-environment-broker/internal/cls/client.go
  components/kyma-environment-broker/internal/cls/client_test.go
  components/kyma-environment-broker/internal/cls/config.go
  components/kyma-environment-broker/internal/cls/config_test.go
  components/kyma-environment-broker/internal/cls/provisioner.go
  components/kyma-environment-broker/internal/cls/provisioner_test.go
  components/kyma-environment-broker/internal/cls/service_manager_utils.go
  components/kyma-environment-broker/internal/cls/service_manager_utils_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/automock/cls_provisioner.go
  components/kyma-environment-broker/internal/process/provisioning/cls_offering_step.go
  components/kyma-environment-broker/internal/process/provisioning/cls_offering_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/cls_provision_int_test.go
  components/kyma-environment-broker/internal/process/provisioning/cls_provision_step.go
  components/kyma-environment-broker/internal/process/provisioning/cls_provision_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/xsuaa_int_test.go
  components/kyma-environment-broker/internal/servicemanager/automock/client.go
  components/kyma-environment-broker/internal/servicemanager/factory.go
  components/kyma-environment-broker/internal/servicemanager/fake.go
  components/kyma-environment-broker/internal/storage/driver/memory/cls_instance.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/storage.go
Labels: area/logging, enhancement

#529 Upgrade k8s in subscription-cleanup-job and provisioner
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
  resources/kcp/values.yaml
Labels: area/control-plane, area/security

#534 Add the conflictStrategy field to the example schema in provisioning tutorials
  docs/provisioner/08-02-provisioning-gardener.md
Labels: area/documentation, documentation

#498 Add version parameters for Kyma Upgrade
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/common/orchestration/dto.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler.go
  components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
  resources/kcp/values.yaml
Labels: area/control-plane

#536 KEB: Implement CLS deprovisioning
  components/kyma-environment-broker/internal/cls/automock/deprovisioner_storage.go
  components/kyma-environment-broker/internal/cls/automock/instance_remover.go
  components/kyma-environment-broker/internal/cls/client.go
  components/kyma-environment-broker/internal/cls/client_test.go
  components/kyma-environment-broker/internal/cls/deprovisioner.go
  components/kyma-environment-broker/internal/cls/deprovisioner_test.go
  components/kyma-environment-broker/internal/cls/provisioner.go
  components/kyma-environment-broker/internal/cls/provisioner_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/automock/cls_deprovisioner.go
  components/kyma-environment-broker/internal/process/deprovisioning/cls_deprovision_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/cls_deprovision_step_int_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/cls_deprovision_step_test.go
  components/kyma-environment-broker/internal/servicemanager/fake.go
  components/kyma-environment-broker/internal/storage/driver/memory/cls_instance.go
  components/kyma-environment-broker/internal/storage/ext.go
Labels: area/logging, enhancement

#524 Add Openstack to supported providers
  components/provisioner/Makefile
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/api/testdata/config.json
  components/provisioner/internal/api/validator.go
  components/provisioner/internal/api/validator_test.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/model/infrastructure.go
  components/provisioner/internal/model/infrastructure/openstack/control_plane.go
  components/provisioner/internal/model/infrastructure/openstack/infrastructure.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/util/pointers.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/provider_config.go
  components/provisioner/pkg/gqlschema/provider_config_test.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202119021531_drop_not_null_volume_size_gb_and_disk_type.down.sql
  components/schema-migrator/migrations/provisioner/202119021531_drop_not_null_volume_size_gb_and_disk_type.up.sql
  resources/kcp/values.yaml
Labels: WIP, area/control-plane, enhancement
