Repository kyma-project/control-plane, pull requests merged in 2021-12, with the labels that each got.

#1161 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#1158 Update libraries in kmc
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1167 Upgrade to reconciler image feb4fbd7
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1152 Adjust AWS plans' machine types
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/services.go
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
  components/kyma-environment-broker/internal/provider/aws_provider.go
  docs/kyma-environment-broker/03-01-service-description.md
  resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1166 Add persisting cluster config in fake reconciler
  components/kyma-environment-broker/internal/reconciler/fake.go
Labels: size/S, lgtm

#1165 Do not allow to update an instance if the instance is failed or is being deprovisioned
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1169 changed reconciler image format in values.yaml
  resources/kcp/charts/component-reconcilers/charts/rma-component-reconciler/templates/deployment.yaml
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1172 Remove hardcoded 24 hours orchestration reschedule delay
  components/kyma-environment-broker/common/orchestration/strategies/parallel.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1168 Align GCP plan values with the published schema
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1177 Update images for reconciliation components
  resources/kcp/values.yaml
Labels: area/control-plane, size/XS, lgtm

#1162 Fix KEB update operation success description
  components/kyma-environment-broker/internal/process/update/manager.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1180 Add kwiatekus to the CODEOWNERS
  CODEOWNERS
Labels: enhancement, area/serverless, size/XS, lgtm

#1174 Remove check dashboard URL step
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/process/provisioning/check_dashboard_url_step.go
  components/kyma-environment-broker/internal/process/provisioning/check_dashboard_url_step_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1182 Add liveness and readiness probes to rma-reconciler
  resources/kcp/charts/component-reconcilers/charts/rma-component-reconciler/templates/deployment.yaml
Labels: size/XS, lgtm

#1116 Add GCPPlanID to metrics supportedPlansIDs
  components/kyma-environment-broker/internal/metrics/operations_collector.go
  resources/kcp/charts/kyma-environment-broker/files/dashboard.json
Labels: size/XS, lgtm

#825 KEB service catalog migration
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/testdata/additional-runtime-components.yaml
  components/kyma-environment-broker/cmd/broker/testdata/kyma-components.yaml
  components/kyma-environment-broker/cmd/broker/testdata/managed-runtime-components.yaml
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/instance_update_test.go
  components/kyma-environment-broker/internal/component_input_helpers.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides_test.go
  components/kyma-environment-broker/internal/process/update/apply_reconciler_configuration.go
  components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/update/conditions.go
  components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/update/init_kyma_step.go
  components/kyma-environment-broker/internal/process/update/initialisation_step.go
  components/kyma-environment-broker/internal/process/update/initialisation_step_test.go
  components/kyma-environment-broker/internal/process/update/manager.go
  components/kyma-environment-broker/internal/process/update/manager_test.go
  components/kyma-environment-broker/internal/process/update/sc_migration.go
  components/kyma-environment-broker/internal/process/update/sc_migration_check_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion_test.go
  components/kyma-environment-broker/internal/storage/driver/memory/runtime_state.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#1181 Bump reconciler images to 0b69711d
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1186 fix links in KCP docs README
  docs/README.md
Labels: size/S, lgtm

#1187 Update runc dependency and golang image
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/Dockerfile.sac
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1188 remove postgresql.persistence.enabled=false
  tools/reconciler/Makefile
Labels: size/S, lgtm

#1193 revert change
  tools/reconciler/Makefile
Labels: size/S, lgtm

#1190 Expose kyma version on runtimes endpoint
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/runtime/handler.go
  resources/kcp/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/runtime.go
Labels: size/M, lgtm

#1192 Fix helm template
  resources/kcp/values.yaml
  tools/reconciler/Makefile
Labels: size/XS, lgtm

#1164 Return reconciliation runs from precise timebox
  tools/cli/pkg/command/reconciliations.go
  tools/cli/pkg/command/reconciliations_test.go
  tools/cli/pkg/timestamp/timestamp.go
  tools/cli/pkg/timestamp/timestamp_test.go
Labels: size/L, lgtm

#1199 Configurable deployment strategy for mothership-reconciler
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/S, lgtm

#1200 Bump reconciler images to tag `8f7ef39c`
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1202 Fix determining current Kyma version by operations
  components/kyma-environment-broker/internal/runtime/handler.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1205 Bump reconciler component
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1206 Explicitly fail KEB update operations on irrecoverable errors
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/update/apply_reconciler_configuration.go
  components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/update/sc_migration.go
  components/kyma-environment-broker/internal/process/update/sc_migration_check_step.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1207 Check reconciler status in update queue only when required
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/update/apply_reconciler_configuration.go
  components/kyma-environment-broker/internal/process/update/conditions.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1184 Encrypt BTP Operator ERS credentials
  components/kyma-environment-broker/internal/storage/driver/postsql/ext.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/storage/encrypt.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1208 Change subscription cleanup schedule to daily
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
Labels: size/XS, lgtm

#1210 Strip namespace from templates of selected kinds
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1211 Remove crabtree from codeowners
  CODEOWNERS
Labels: size/S, lgtm

#1213 Bump to reconciler image 943e0e86
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1215 Change default Azure region to eastus
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider_test.go
Labels: size/XS, lgtm

#1217 Disable sc-migration component for upgrade queue on kyma2
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1216 Update reconciler images
  resources/kcp/values.yaml
Labels: area/eventing, size/XS, lgtm

#1214 KEB takes updateAt/modifiedAt field for runtime status from last operation
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/appinfo/runtime_info.go
  components/kyma-environment-broker/internal/appinfo/runtime_info_test.go
  components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_with_deprovision_operation.golden.json
  components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_with_provision_and_deprovision_operations.golden.json
  components/kyma-environment-broker/internal/appinfo/testdata/TestRuntimeInfoHandlerSuccess/instances_with_provision_operation.golden.json
  components/kyma-environment-broker/internal/runtime/handler.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1219 Bump reconciler images to bb1616d4
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1198 Allow Provisioner to update tenant
  components/provisioner/cmd/main.go
  components/provisioner/go.sum
  components/provisioner/internal/api/mocks/TenantUpdater.go
  components/provisioner/internal/api/mocks/Validator.go
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/api/tenant_updater.go
  components/provisioner/internal/api/tenant_updater_test.go
  components/provisioner/internal/api/validator.go
  components/provisioner/internal/api/validator_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1218 KCP CLI: username is not allowed to be set by USERNAME environment variable
  tools/cli/pkg/command/options.go
Labels: size/XS, lgtm

#1224 Bump to reconciler image 1ff7cd81
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1225 Update filters in reconciliations help
  tools/cli/pkg/command/reconciliations.go
Labels: size/XS, lgtm

#1226 add jellyfish team to code owners
  CODEOWNERS
Labels: size/S, lgtm

#1179 1814 support move of subaccounts
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/instance_update_test.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/storage/dbmodel/instance.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  components/kyma-environment-broker/internal/storage/postsql/write.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
  components/schema-migrator/migrations/kyma-environment-broker/202112071502_add_instance_subscriptionGAID.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202112071502_add_instance_subscriptionGAID.up.sql
Labels: size/L, lgtm

#1223 Return 404 when instance does not exist
  components/kyma-environment-broker/cmd/broker/last_operation_test.go
  components/kyma-environment-broker/internal/broker/instance_last_operation.go
  resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1228 Hotfix for PR1179
  components/schema-migrator/migrations/kyma-environment-broker/202143071502_add_instance_subscriptionGAID.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202143071502_add_instance_subscriptionGAID.up.sql
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1231 KEB DB tests use SQL statements defined in the schema migrator instead of test_utils
  components/kyma-environment-broker/internal/cis/e2e/tests_utils.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
Labels: size/L, lgtm

#1220 Switch to AWS m5 machines
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  docs/kyma-environment-broker/03-01-service-description.md
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1227 Remove console approvers from OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS, lgtm

#1236 use old version
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1239 fix format
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1235 workaround: disable dashboard-checker in e2e tests for kyma 2.0
  resources/kcp/values.yaml
  tests/e2e/provisioning/test/e2e_provisioning_test.go
  tests/e2e/provisioning/test/e2e_suspension_test.go
Labels: size/S, lgtm

#1237 Delete cluster config on reconciliation timeout
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration.go
  components/kyma-environment-broker/internal/reconciler/client.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1242 Update links and diagrams in KEB
  docs/kyma-control-plane/01-01-overview.md
  docs/kyma-environment-broker/01-01-overview.md
  docs/kyma-environment-broker/02-01-architecture.md
  docs/kyma-environment-broker/02-02-broker-endpoints.md
  docs/kyma-environment-broker/03-01-service-description.md
  docs/kyma-environment-broker/03-02-runtime-components.md
  docs/kyma-environment-broker/03-03-runtime-operations.md
  docs/kyma-environment-broker/03-04-hyperscaler-account-pool.md
  docs/kyma-environment-broker/03-05-authorization.md
  docs/kyma-environment-broker/03-06-runtime-overrides.md
  docs/kyma-environment-broker/03-07-environments-cleanup.md
  docs/kyma-environment-broker/03-08-kyma-versions.md
  docs/kyma-environment-broker/03-09-subaccount-cleanup-cronjob.md
  docs/kyma-environment-broker/03-10-orchestration.md
  docs/kyma-environment-broker/03-11-swagger.md
  docs/kyma-environment-broker/03-12-custom-oidc-configuration.md
  docs/kyma-environment-broker/03-13-custom-administrators.md
  docs/kyma-environment-broker/08-01-provisioning-kyma-environment.md
  docs/kyma-environment-broker/08-02-deprovisioning-kyma-environment.md
  docs/kyma-environment-broker/08-03-operation-status.md
  docs/kyma-environment-broker/08-04-instance-details.md
  docs/kyma-environment-broker/08-05-orchestrate-kyma-upgrade.md
  docs/kyma-environment-broker/08-06-orchestration-status.md
  docs/kyma-environment-broker/assets/hap-flow.svg
  docs/kyma-environment-broker/assets/keb-architecture.svg
  docs/kyma-environment-broker/assets/runtime-components.svg
Labels: bug, area/documentation, size/L, lgtm
