Repository kyma-project/control-plane, pull requests merged in 2021-08, with the labels that each got.

#861 upgrade kyma_version to 1.23.1
  installation/resources/KYMA_VERSION
Labels: lgtm, size/XS

#868 Add Connectivity Service service manager step to provisioning steps
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/values.yaml
Labels: area/control-plane, bug, lgtm, size/S

#878 KEB fix UpgradeShoot GraphQL template
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#880 Set default OIDC values in update request
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/L

#883 Modified config map name
  resources/kcp/charts/kyma-environment-broker/templates/tests/upg-tst-aws-prov.yaml
Labels: size/XS, lgtm

#882 Use sm creds for configured subaccount
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/servicemanager/config.go
  components/kyma-environment-broker/internal/servicemanager/factory.go
  components/kyma-environment-broker/internal/servicemanager/factory_test.go
  components/kyma-environment-broker/internal/servicemanager/fake.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#884 Set upgrade test to false in test definition
  resources/kcp/charts/kyma-environment-broker/templates/tests/upg-tst-aws-prov.yaml
Labels: size/XS, lgtm

#886 Fix UpgradeShootInput to always contain admins list
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#885 Administrators parameter doc
  docs/kyma-environment-broker/03-13-custom-administrators.md
Labels: size/M, lgtm

#874 Sync the node autoscale params during KEB cluster upgrade
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/builder_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  components/kyma-environment-broker/internal/provisioner/client_test.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#891 Modified wrongly given cleanup testdefinition name
  resources/kcp/charts/kyma-environment-broker/templates/tests/upg-tst-aws-prov.yaml
Labels: size/XS, lgtm

#889 Add ebensom to code owners of KEB and e2e provisioning tests
  CODEOWNERS
Labels: size/S, lgtm

#892 Replace apimachinery in Provisioner
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/values.yaml
Labels: area/control-plane, size/M, lgtm

#834 [US-933] Support "day" input for KEB maintenance windows
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/orchestration/dto.go
  components/kyma-environment-broker/common/orchestration/ext.go
  components/kyma-environment-broker/common/orchestration/resolver.go
  components/kyma-environment-broker/common/orchestration/strategies/parallel.go
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#893 Allow configuring shoot upgrade timeout (default 90 mins)
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#877 upgrade kymaVersion to 1.24.0 in resources/KYMA_VERSION
  components/provisioner/README.md
  installation/resources/KYMA_VERSION
  installation/resources/installer-overrides-kyma.yaml
  resources/kcp/charts/provisioner/templates/deployment.yaml
Labels: size/XS, lgtm

#896 Fix OIDC param in the returned kubeconfig
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/kubeconfig/builder.go
  components/kyma-environment-broker/internal/kubeconfig/builder_test.go
  components/kyma-environment-broker/internal/provisioner/query.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#879 Use planID as template variable in KEB dashboard
  resources/kcp/charts/kyma-environment-broker/files/dashboard.json
Labels: size/XXL, lgtm

#901 Update description of KMC
  components/kyma-metrics-collector/README.md
Labels: size/S, lgtm

#899 add new previewPlanID
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion_test.go
  docs/kyma-environment-broker/03-08-kyma-versions.md
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#904 KEB input creator for preview plan
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/automock/provisioner_input_creator.go
  components/kyma-environment-broker/internal/process/provisioning/base_provision_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
Labels: size/L, lgtm
