Repository kyma-project/control-plane, pull requests merged in 2021-05, with the labels that each got.

#707 Remove AWS us-west-1b Availability Zone
  components/kyma-environment-broker/internal/provider/aws_provider.go
Labels: lgtm, size/XS

#696 Freemium
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/hyperscaler/account_provider.go
  components/kyma-environment-broker/internal/appinfo/runtime_info.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/plans_validator.go
  components/kyma-environment-broker/internal/broker/plans_validator_test.go
  components/kyma-environment-broker/internal/broker/services.go
  components/kyma-environment-broker/internal/broker/services_test.go
  components/kyma-environment-broker/internal/broker/testdata/free-aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/free-azure-schema.json
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/middleware/export.go
  components/kyma-environment-broker/internal/middleware/provider.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/builder_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/freemium_input.go
  components/kyma-environment-broker/internal/provider/freemium_input_test.go
  components/kyma-environment-broker/internal/runtime/disabled_components.go
  resources/kcp/charts/kyma-environment-broker/files/catalog.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: lgtm, size/XL

#660 Runtime deprovisioning test
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  resources/kcp/values.yaml
Labels: lgtm, size/L

#711 add AWSPlanID for metrics
  components/kyma-environment-broker/internal/metrics/operations_collector.go
Labels: lgtm, size/XS

#710 Adjust azure_lite plan schema
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema.json
  resources/kcp/values.yaml
Labels: lgtm, size/S

#713 Set cloud provider type in AVS evaluation names correctly
  components/kyma-environment-broker/internal/avs/model.go
  resources/kcp/values.yaml
Labels: lgtm, size/M

#716 Recreate AVS evaluations during unsuspension
  components/kyma-environment-broker/internal/avs/delegator.go
  components/kyma-environment-broker/internal/avs/eval_assistant.go
  components/kyma-environment-broker/internal/avs/external_eval_assistant.go
  components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#663 Keb split provisioning initialisation
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/director/fake.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/check_dashboard_url_step.go
  components/kyma-environment-broker/internal/process/provisioning/check_dashboard_url_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/check_runtime_step.go
  components/kyma-environment-broker/internal/process/provisioning/check_runtime_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/external_eval_step.go
  components/kyma-environment-broker/internal/process/provisioning/external_eval_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/ias_type_step.go
  components/kyma-environment-broker/internal/process/provisioning/ias_type_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/internal_eval_updater_test.go
  components/kyma-environment-broker/internal/process/provisioning/manager.go
  components/kyma-environment-broker/internal/process/provisioning/manager_test.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds_test.go
  components/kyma-environment-broker/internal/process/provisioning/runtime_tags_step.go
  components/kyma-environment-broker/internal/process/provisioning/runtime_tags_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/staged_manager.go
  components/kyma-environment-broker/internal/process/provisioning/staged_manager_test.go
  components/kyma-environment-broker/internal/process/provisioning/start_step.go
  components/kyma-environment-broker/internal/process/provisioning/start_step_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/suspension/handler.go
  docs/kyma-environment-broker/03-03-runtime-operations.md
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
  resources/kcp/values.yaml
Labels: lgtm, size/XXL

#615 add e2e test for aws
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-aws.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: lgtm

#701 Make auditlog optional
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/auditlog/config.go
  components/kyma-environment-broker/internal/process/provisioning/audit_log_step.go
  components/kyma-environment-broker/internal/process/provisioning/audit_log_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/audit_log.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/audit_log_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: lgtm, size/M

#715 Fix Installation status checking while provisioning a Runtime
  components/provisioner/go.sum
  components/provisioner/internal/installation/installation.go
  components/provisioner/internal/operations/stages/provisioning/install_kyma.go
  components/provisioner/internal/operations/stages/provisioning/install_kyma_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_installation.go
  resources/kcp/values.yaml
Labels: area/control-plane, bug, lgtm, size/S

#723 Bump alpine base image to 3.13.5
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.sac
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#724 Fix image tags in jobs
  resources/kcp/values.yaml
  tests/e2e/provisioning/Dockerfile
Labels: lgtm, size/S

#721 upgrade kcp clusters to kyma 1.21.1
  installation/resources/KYMA_VERSION
Labels: lgtm, size/XS

#725 Fix e2e provisioning test
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
Labels: lgtm, size/XS

#726 Expose upgrade cluster operation results in metrics
  components/kyma-environment-broker/internal/metrics/metrics.go
  components/kyma-environment-broker/internal/metrics/operation_result.go
  resources/kcp/values.yaml
Labels: lgtm, size/M

#680 Cluster upgrade orchestration - cli implementation
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/orchestration.go
  tools/cli/pkg/command/upgrade.go
  tools/cli/pkg/command/upgrade_cluster.go
Labels: lgtm, size/L

#727 Shell flag
  tools/cli/pkg/command/taskrun.go
Labels: lgtm, size/S

#729 Fix broker provision test
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#731 Update codeowners
  CODEOWNERS
Labels: area/community, lgtm, size/S

#732 Cluster cli backlog
  tools/cli/pkg/command/upgrade_cluster.go
Labels: lgtm, size/XS

#733 Bump cloudsql-proxy image in KEB
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#730 Distinguish recoverable vs. unrecoverable Kyma installation errors
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/operations/stages/provisioning/wait_for_installation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_installation_test.go
  components/provisioner/internal/operations/stages/upgrade/upgrade_kyma.go
  components/provisioner/internal/operations/stages/upgrade/upgrade_kyma_test.go
  resources/kcp/values.yaml
Labels: area/control-plane, lgtm, size/M

#738 Fix unsuspension process
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#739 Remove the usage of Azure/Event-Hub
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/azure/event_hub.go
  components/kyma-environment-broker/internal/process/deprovisioning/event_hub_activation.go
  components/kyma-environment-broker/internal/process/deprovisioning/event_hub_activation_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/event_hub_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/event_hub_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/enable_for_trial_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_activation.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_activation_test.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/nats_activation_step.go
  components/kyma-environment-broker/internal/process/provisioning/nats_activation_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/natss_step.go
  components/kyma-environment-broker/internal/process/provisioning/natss_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/event_hub_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/event_hub_step_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/XXL

#736 Return NotFound on KEB instance updates when instance is missing
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/instance_update_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/M

#742 E2e free AWS testing pipeline
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-free-aws.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
Labels: lgtm, size/L

#744 Add logs to e2e tests
  resources/kcp/values.yaml
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
Labels: lgtm, size/XS

#745 Fix e2e pipeline KEB client
  resources/kcp/values.yaml
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
Labels: lgtm, size/XS

#747 Provisioning will not fail when Gardener returns limit rate exceeded error
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/L

#750 Fix post action in deprovisioning functionality
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  installation/resources/KYMA_VERSION
  resources/kcp/values.yaml
Labels: lgtm, size/S

#743 Migrate KEB from dep to gomod
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/Dockerfile.sac
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/Gopkg.toml
  components/kyma-environment-broker/Makefile
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/appinfo/runtime_info_test.go
  components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/XXL

#752 Fix azure HA schema
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema.json
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#757 Bugfix for /runtimes endpoint displaying zeroed deprovisioning operation
  components/kyma-environment-broker/internal/runtime/handler.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#722 KEB Resolve user (email) of the runtime creator
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/cmd/main.go
  components/provisioner/internal/model/kyma_config.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202117051400_add_administrators.down.sql
  components/schema-migrator/migrations/provisioner/202117051400_add_administrators.up.sql
  docs/kyma-environment-broker/08-01-provisioning-kyma-environment.md
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
  tests/e2e/provisioning/test/test_suite.go
Labels: lgtm, size/L

#759 Change alpine-kubectl image to k8s-tools
  components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml
  resources/kcp/templates/registration-job.yaml
Labels: lgtm, size/XS

#761 KEB Resolve user (email) of the runtime creator - migration
  components/schema-migrator/migrations/provisioner/202127051400_add_administrators.down.sql
  components/schema-migrator/migrations/provisioner/202127051400_add_administrators.up.sql
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#754 Added configurable timeout for upgrade triggering
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
Labels: lgtm, size/S

#766 KEB Resolve user (email) of the runtime creator
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#767 KEB Resolve user (email) of the runtime creator (#766) - go.mod
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: lgtm, size/S

#768 Bump e2e-provisioning test image
  resources/kcp/values.yaml
Labels: lgtm, size/XS

#762 Bump Provisioner
  resources/kcp/values.yaml
Labels: area/control-plane, lgtm, size/XS

#763 Fix for issues seen during AVS deprovisioning step
  components/kyma-environment-broker/internal/avs/client.go
  components/kyma-environment-broker/internal/avs/client_test.go
  components/kyma-environment-broker/internal/avs/mock_server.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  resources/kcp/values.yaml
Labels: lgtm, size/S

#770 Retry operation when shoot upgrade encounters rate limit exceeded error
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade_test.go
  components/provisioner/internal/util/testkit/shoot.go
  resources/kcp/values.yaml
Labels: lgtm, size/M

#771 Bump Provisioners alpine
  components/provisioner/Dockerfile
  components/provisioner/go.sum
  resources/kcp/values.yaml
Labels: area/control-plane, lgtm, size/XS

#755 Update /info/runtimes endpoint
  components/kyma-environment-broker/internal/appinfo/runtime_info.go
  components/kyma-environment-broker/internal/appinfo/runtime_info_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/storage/dbmodel/instance.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/values.yaml
Labels: lgtm, size/XL

#756 Added instanceID to data target and resolver
  components/kyma-environment-broker/common/orchestration/dto.go
  components/kyma-environment-broker/common/orchestration/resolver.go
  components/kyma-environment-broker/common/orchestration/resolver_test.go
Labels: lgtm, size/S

#753 Return NotFound on KEB instance get when instance is missing
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/instance_get.go
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  resources/kcp/values.yaml
Labels: lgtm, size/L
