Repository kyma-project/control-plane, pull requests merged in 2021-03, with the labels that each got.

#550 KEB: Implement SQL storage for CLS
  components/kyma-environment-broker/internal/cls/automock/deprovisioner_storage.go
  components/kyma-environment-broker/internal/cls/automock/provisioner_storage.go
  components/kyma-environment-broker/internal/cls/client_test.go
  components/kyma-environment-broker/internal/cls/config_test.go
  components/kyma-environment-broker/internal/cls/deprovisioner.go
  components/kyma-environment-broker/internal/cls/deprovisioner_test.go
  components/kyma-environment-broker/internal/cls/provisioner.go
  components/kyma-environment-broker/internal/cls/provisioner_test.go
  components/kyma-environment-broker/internal/cls/service_manager_utils_test.go
  components/kyma-environment-broker/internal/cls_instance.go
  components/kyma-environment-broker/internal/cls_instance_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/cls_deprovision_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/cls_deprovision_step_test.go
  components/kyma-environment-broker/internal/storage/dbmodel/cls.go
  components/kyma-environment-broker/internal/storage/driver/memory/cls_instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/cls_instance.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/init.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  components/kyma-environment-broker/internal/storage/postsql/write.go
  components/kyma-environment-broker/internal/storage/storage.go
  components/kyma-environment-broker/internal/storage/storage_test.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
  components/schema-migrator/migrations/kyma-environment-broker/202101131045_add_cls_instances.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202101131045_add_cls_instances.up.sql
Labels: area/logging

#574 Upgrade 'jwt-go' in subscription-cleanup-job
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
  resources/kcp/values.yaml
Labels: area/control-plane, area/security

#578 Remove unnecessary test cases from Resolver tests
  components/provisioner/internal/api/resolver_integration_test.go
Labels: area/control-plane

#594 Improve CLS log messages
  components/kyma-environment-broker/internal/cls/client.go
  components/kyma-environment-broker/internal/cls/config.go
  components/kyma-environment-broker/internal/cls/config_test.go
  components/kyma-environment-broker/internal/cls/deprovisioner.go
  components/kyma-environment-broker/internal/cls/kyma_version_check.go
  components/kyma-environment-broker/internal/cls/overrides.go
  components/kyma-environment-broker/internal/cls/provisioner.go
  components/kyma-environment-broker/internal/process/provisioning/cls_audit_log_step.go
  components/kyma-environment-broker/internal/process/provisioning/cls_audit_log_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/cls_binding_step.go
  components/kyma-environment-broker/internal/process/provisioning/cls_offering_step.go
  components/kyma-environment-broker/internal/process/provisioning/cls_provision_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_audit_log.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_audit_log_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_binding.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_offering.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_provision.go
Labels: area/logging

#554 Add version parameters to KCP CLI on Kyma upgrade
  docs/cli/commands/kcp_upgrade_kyma.md
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/upgrade_kyma.go
Labels: area/cli

#563 KEB: Combine CLS steps
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/auditlog/templates/extra_conf_kyma.go
  components/kyma-environment-broker/internal/auditlog/templates/extra_conf_kyma_1_19.go
  components/kyma-environment-broker/internal/cls/client.go
  components/kyma-environment-broker/internal/cls/client_test.go
  components/kyma-environment-broker/internal/cls/config.go
  components/kyma-environment-broker/internal/cls/deprovisioner.go
  components/kyma-environment-broker/internal/cls/deprovisioner_test.go
  components/kyma-environment-broker/internal/cls/overrides_test.go
  components/kyma-environment-broker/internal/cls/provisioner.go
  components/kyma-environment-broker/internal/cls/provisioner_test.go
  components/kyma-environment-broker/internal/cls/service_manager_utils.go
  components/kyma-environment-broker/internal/cls/service_manager_utils_test.go
  components/kyma-environment-broker/internal/cls/templates/extra_conf_kyma.go
  components/kyma-environment-broker/internal/process/deprovisioning/automock/cls_deprovisioner.go
  components/kyma-environment-broker/internal/process/deprovisioning/cls_deprovision_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/cls_deprovision_step_int_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/cls_deprovision_step_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/cls_unbinding_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/cls_unbinding_step_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/manager.go
  components/kyma-environment-broker/internal/process/provisioning/automock/cls_binding_provider.go
  components/kyma-environment-broker/internal/process/provisioning/automock/cls_provisioner.go
  components/kyma-environment-broker/internal/process/provisioning/cls_audit_log_step.go
  components/kyma-environment-broker/internal/process/provisioning/cls_audit_log_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/cls_binding_step.go
  components/kyma-environment-broker/internal/process/provisioning/cls_binding_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/cls_offering_step.go
  components/kyma-environment-broker/internal/process/provisioning/cls_provision_int_test.go
  components/kyma-environment-broker/internal/process/provisioning/cls_provision_step.go
  components/kyma-environment-broker/internal/process/provisioning/cls_provision_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/enable_for_trial_step.go
  components/kyma-environment-broker/internal/process/provisioning/enable_for_trial_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/event_hub_activation_test.go
  components/kyma-environment-broker/internal/process/provisioning/skip_for_trial_step.go
  components/kyma-environment-broker/internal/process/provisioning/skip_for_trial_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/automock/step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_audit_log.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_audit_log_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_binding.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_binding_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_offering.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_provision.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/cls_provision_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/skip_for_trial_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/skip_for_trial_step_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: area/logging

#568 Move HAP to SecretBindings
  components/kyma-environment-broker/Gopkg.lock
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/gardener/client.go
  components/kyma-environment-broker/common/hyperscaler/account_pool.go
  components/kyma-environment-broker/common/hyperscaler/account_pool_test.go
  components/kyma-environment-broker/common/hyperscaler/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/account_provider_test.go
  components/kyma-environment-broker/common/hyperscaler/automock/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/shared_pool.go
  components/kyma-environment-broker/common/hyperscaler/shared_pool_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
  components/subscription-cleanup-job/cmd/main.go
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
  components/subscription-cleanup-job/internal/job/cleaner.go
  components/subscription-cleanup-job/internal/job/cleaner_test.go
  resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/rbac.yaml
  resources/kcp/values.yaml
  tests/e2e/provisioning/Gopkg.lock
  tests/e2e/provisioning/Gopkg.toml
  tests/e2e/provisioning/internal/hyperscaler/account_pool.go
  tests/e2e/provisioning/internal/hyperscaler/account_provider.go
  tests/e2e/provisioning/test/test_suite.go
Labels: area/control-plane, bug

#623 Add update secretbindings rbac for KEB
  resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
Labels: WIP, area/control-plane
