Repository kyma-project/control-plane, pull requests merged in 2022-04, with the labels that each got.

#1437 scrapeTimeout added
  resources/kcp/charts/kyma-environment-broker/templates/service-monitor.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1506 Add option to configure features in component reconciler deployment
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1481 Fix DNS config in DB
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/schema-migrator/migrations/provisioner/202203222101_add_dns_config.down.sql
  components/schema-migrator/migrations/provisioner/202203222101_add_dns_config.up.sql
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1488 feat: enable new cleaner script on mothership
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
Labels: size/XS, lgtm

#1512 Simple Retries Mechanism, Condition Based Processing & Refactoring
  tools/cli/go.sum
  tools/cli/pkg/ers/client/http.go
  tools/cli/pkg/ers/command/logs.go
  tools/cli/pkg/ers/command/migrate_all.go
  tools/cli/pkg/ers/command/stats.go
  tools/cli/pkg/ers/command/status.go
  tools/cli/pkg/ers/model.go
Labels: size/M, lgtm

#1517 Revert "Fix DNS config in DB (#1481)"
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/schema-migrator/migrations/provisioner/202203222101_add_dns_config.down.sql
  components/schema-migrator/migrations/provisioner/202203222101_add_dns_config.up.sql
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1524 Missing Nil Check
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/ers/command/migrate_all.go
Labels: size/L, lgtm

#1520 append cluster env when sending slack msg
  tools/cli/pkg/command/send_slack_notification.go
Labels: size/S, lgtm

#1531 ERS CLI - Increased Timeout
  tools/cli/pkg/ers/command/migrate_all.go
Labels: size/XS, lgtm

#1532 Regex Logs Correction
  tools/cli/pkg/ers/command/status.go
Labels: size/XS, lgtm

#1535 Corrected Unnecessary WaitGroup Calls
  tools/cli/pkg/ers/command/migrate_all.go
Labels: size/XS, lgtm

#1534 bump dependencies in kmc
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1539 Values Update
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1541 replace helm to newest 2.17 version
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
Labels: size/S, lgtm

#1542 fix security vulnerability in kmc
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: area/control-plane, approved, size/M, lgtm

#1474 Subscription Cleanup Job moved to KEB
  components/kyma-environment-broker/Dockerfile.scj
  components/kyma-environment-broker/Makefile
  components/kyma-environment-broker/cmd/subscriptioncleanup/cloudprovider/aws.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/cloudprovider/azure.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/cloudprovider/factory.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/cloudprovider/gcp.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/cloudprovider/mocks/ProviderFactory.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/job/cleaner.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/job/cleaner_test.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/main.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/model/types.go
  components/subscription-cleanup-job/Dockerfile
  components/subscription-cleanup-job/Makefile
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
  resources/kcp/values.yaml
  scripts/generic_make_go.mk
Labels: size/XXL, lgtm

#1521 Add remove service instance step to deprovisioning queue
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance_test.go
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1547 bump gardener deps
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: area/control-plane, security/high, size/S, lgtm

#1551 Fix remove service instance step
  components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1552 Version Bumps
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.sac
  components/schema-migrator/Dockerfile
Labels: size/S, lgtm

#1555 fix: Mothership Reconciler Values: increase connMaxIdleTime to not immediately close the connection
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#1549 Schema Migrator Go Upgrade
  components/schema-migrator/Dockerfile
  components/schema-migrator/Gopkg.lock
  components/schema-migrator/Gopkg.toml
  components/schema-migrator/Makefile
  components/schema-migrator/go.mod
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1558 Downgrade mothership reconciler to be3fe478
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1511 feature: customer notification
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/orchestration/dto.go
  components/kyma-environment-broker/internal/notification/builder.go
  components/kyma-environment-broker/internal/notification/bundle.go
  components/kyma-environment-broker/internal/notification/bundle_test.go
  components/kyma-environment-broker/internal/notification/client.go
  components/kyma-environment-broker/internal/notification/client_test.go
  components/kyma-environment-broker/internal/notification/fake_client.go
  components/kyma-environment-broker/internal/notification/mocks/Bundle.go
  components/kyma-environment-broker/internal/notification/mocks/BundleBuilder.go
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/send_notification.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/send_notification_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/send_notification.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/send_notification_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#1565 Values Update & Cli Tidy
  resources/kcp/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/S, lgtm

#1527 Remove Gardener dependency from KEB
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/environmentscleanup/main.go
  components/kyma-environment-broker/common/gardener/client.go
  components/kyma-environment-broker/common/gardener/dynamic_fake.go
  components/kyma-environment-broker/common/hyperscaler/account_pool.go
  components/kyma-environment-broker/common/hyperscaler/account_pool_test.go
  components/kyma-environment-broker/common/hyperscaler/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/account_provider_test.go
  components/kyma-environment-broker/common/hyperscaler/shared_pool.go
  components/kyma-environment-broker/common/hyperscaler/shared_pool_test.go
  components/kyma-environment-broker/common/orchestration/resolver.go
  components/kyma-environment-broker/common/orchestration/resolver_test.go
  components/kyma-environment-broker/internal/environmentscleanup/automock/GardenerClient.go
  components/kyma-environment-broker/internal/environmentscleanup/service.go
  components/kyma-environment-broker/internal/environmentscleanup/service_test.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#1566 Align DEV/STAGE with reconciler on PROD + Disable new cleaner feature (old cleaner stays)
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1573 Compare the k8s versions correctly in Provisioner
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/validator_test.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/service.go
  resources/kcp/values.yaml
Labels: area/control-plane, size/M, lgtm

#1580 Do not call Provisioner in case of svcat migration
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1584 Use dynamic interface for gardener api
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/taskrun.go
Labels: size/S, lgtm

#1586 Fix ERS switch command
  tools/cli/pkg/ers/client/client.go
  tools/cli/pkg/ers/client/http.go
  tools/cli/pkg/ers/command/broker.go
Labels: size/XS, lgtm

#1585 bump dependencies in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#1591 Fix condition for upgrade shoot step in the update queue
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1592 fix protecode on kubeconfig-service
  components/kubeconfig-service/Dockerfile
Labels: size/XS, lgtm

#1581 Errors categorization for deprovisioning - changes for provisioner
  components/provisioner/internal/apperrors/apperrors.go
  components/provisioner/internal/director/directorclient.go
  components/provisioner/internal/installation/installation.go
  components/provisioner/internal/installation/resource_cleanup.go
  components/provisioner/internal/operations/executor.go
  components/provisioner/internal/operations/executor_test.go
  components/provisioner/internal/operations/stages/deprovisioning/cleanup_cluster.go
  components/provisioner/internal/operations/stages/deprovisioning/cleanup_cluster_test.go
  components/provisioner/internal/operations/stages/deprovisioning/delete_cluster.go
  components/provisioner/internal/operations/stages/deprovisioning/delete_cluster_test.go
  components/provisioner/internal/operations/stages/deprovisioning/trigger_kyma_uninstall.go
  components/provisioner/internal/operations/stages/deprovisioning/trigger_kyma_uninstall_test.go
  components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion.go
  components/provisioner/internal/operations/stages/deprovisioning/wait_for_cluster_deletion_test.go
  components/provisioner/internal/operations/stages/provisioning/install_kyma.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1589 Create extended l2-operator ClusterRole for L2 support team
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1567 Update kubernetes dependencies
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1607 add new users to CODEWONERS for resources/kcp/values.yaml
  CODEOWNERS
Labels: size/XS, lgtm

#1599 Remove ClusterID override from BTP-Operator upgrade queue
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/internal/component_input_helpers.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/btp_operator_overrides.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1608 Bump dependencies in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#1579 Errors categorization - meaningful alerting for deprovisioning functionality
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/avs/client.go
  components/kyma-environment-broker/internal/edp/client.go
  components/kyma-environment-broker/internal/edp/errors.go
  components/kyma-environment-broker/internal/error/errors_test.go
  components/kyma-environment-broker/internal/metrics/operation_result.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/manager.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1610 Add plans to compass_keb_operations_provisioning_<state>_total metrics to support all plans
  components/kyma-environment-broker/internal/metrics/operations_collector.go
  resources/kcp/charts/kyma-environment-broker/files/dashboard.json
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1622 Update kcp-kyma-environment-broker-dashboard to have error category and reason
  resources/kcp/charts/kyma-environment-broker/files/dashboard.json
Labels: size/L, lgtm

#1605 Update externalEvalCreator target URL
  components/kyma-environment-broker/internal/process/provisioning/external_eval_step.go
Labels: size/XS, lgtm

#1600 Remove gardener for subscriptioncleanup job
  components/kyma-environment-broker/cmd/subscriptioncleanup/job/cleaner.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/job/cleaner_test.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/main.go
  components/kyma-environment-broker/common/gardener/client.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1624 replace k8s.io/helm to 2.16.1 in go.mod
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1623 Extend RMA reconciler permissions
  resources/kcp/charts/component-reconcilers/charts/rma/templates/rbac.yaml
Labels: size/XS, lgtm

#1629 bumps reconciler images with log level decrease
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1628 bugfix: remove extra shootName from external evaluation targetURL
  components/kyma-environment-broker/internal/process/provisioning/external_eval_step.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1630 feat: cleaner config helm values
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/S, lgtm

#1571 Replace legacy console URL with Kyma Dashboard
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/instance_update_test.go
  components/kyma-environment-broker/internal/dashboard/config.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1638 kubeconfig-service: fix vulnerabilities
  components/kubeconfig-service/Dockerfile
  components/kubeconfig-service/Makefile
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XXL, lgtm

#1561 Enable NAT Gateway in Provisioner
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/model/infrastructure.go
  components/provisioner/internal/model/infrastructure/azure/infrastructure.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1634 bump gardender extension aws
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1650 Fix the wrong numbers on kcp-kyma-environment-broker-dashboard for upgraded clusters
  resources/kcp/charts/kyma-environment-broker/files/dashboard.json
Labels: size/L, lgtm

#1654 Change the version of the connectivity-proxy reconciler
  resources/kcp/values.yaml
Labels: size/XS, lgtm
