Repository kyma-project/control-plane, pull requests merged in 2022-10, with the labels that each got.

#2083 Use provided shootdomain for own cluster
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
Labels: size/S, lgtm

#2067 Update docs
  docs/kyma-environment-broker/03-03-runtime-operations.md
Labels: area/documentation, size/S, lgtm

#2096 Feature/stage steps docs
  docs/kyma-environment-broker/03-03-runtime-operations.md
Labels: area/documentation, size/S, lgtm

#1840 Created AWS cleanup script
  components/kyma-environment-broker/cmd/subscriptioncleanup/cloudprovider/aws.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: area/documentation, size/L, lgtm, ok-to-test

#2104 Save AvS data in the deprovisioning step, add more logs to AvS stuff
  components/kyma-environment-broker/internal/avs/client.go
  components/kyma-environment-broker/internal/avs/delegator.go
  components/kyma-environment-broker/internal/avs/eval_assistant.go
  components/kyma-environment-broker/internal/avs/external_eval_assistant.go
  components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2105 Schema corrected for own cluster plan
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/testdata/own-cluster-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/own-cluster-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-own-cluster-schema-additional-params.json
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2110 Hide some data in the response of get instance endpoint.
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/broker/instance_get.go
  components/kyma-environment-broker/internal/dto.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2101 Handle own_cluster plan in update
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/process/update/conditions.go
  components/kyma-environment-broker/internal/process/update/init_kyma_step.go
  components/kyma-environment-broker/internal/process/update/initialisation_step.go
  components/kyma-environment-broker/internal/process/update/manager.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2095 Use regular mutex instead of nsync
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/input.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2094 Tracing events proposal for KEB operations
  components/kyma-environment-broker/cmd/accountcleanup/main.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/environmentscleanup/main.go
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  components/kyma-environment-broker/internal/cis/e2e/account_cleanup_test.go
  components/kyma-environment-broker/internal/process/staged_manager.go
  components/kyma-environment-broker/internal/storage/dbmodel/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/conflict_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/events/events.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/orchestration_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtimestate_test.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/write.go
  components/kyma-environment-broker/internal/storage/storage.go
  components/schema-migrator/migrations/kyma-environment-broker/202209211320_events.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202209211320_events.up.sql
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#2117 Fix swallowing gardener client error in KEB
  components/kyma-environment-broker/common/gardener/client.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2113 Prompt_User_Enchancement
  tools/cli/pkg/command/orchestration.go
Labels: size/M, lgtm

#2118 Skipping cluster upgrade for own cluster plan
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/log_skipping_upgrade.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/manager.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/manager_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2125 Fix setting failed state for suspend failed runtimes in /runtimes response
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/runtime/converter_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2132 Fix false nil errors for KEB events
  components/kyma-environment-broker/internal/storage/postsql/write.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2124 Allow to retrigger suspension of expired instance
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/instance_update_test.go
  components/kyma-environment-broker/internal/suspension/handler.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2139 More logging for errors added for instance removal step
  components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2140 Remove references from evetns table
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/schema-migrator/migrations/kyma-environment-broker/202210121025_drop_events_references.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202210121025_drop_events_references.up.sql
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#2141 KEB bump alpine img in Dockerfiles to 3.16.2
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/Dockerfile.sac
  components/kyma-environment-broker/Dockerfile.tcj
Labels: size/XS, lgtm

#2134 Kubeconfig validation for own cluster plan
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2129 resourcePolicy keep
  resources/kcp/charts/provisioner/templates/gardener-creds-secret.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#2135 Add SslRootCert, Fix SslMode for DB
  components/kyma-environment-broker/README.md
  components/kyma-environment-broker/internal/storage/config.go
  docs/kyma-environment-broker/03-07-environments-cleanup.md
  docs/kyma-environment-broker/03-09-subaccount-cleanup-cronjob.md
  docs/kyma-environment-broker/03-15-trial-cleanup-cronjob.md
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/configure-managed-gcp-postgresql.md
  resources/kcp/templates/managed-postgresql-secret.yaml
  resources/kcp/values.yaml
Labels: area/documentation, size/L, lgtm

#2138 Update KEB architecture diagram
  docs/kyma-environment-broker/02-01-architecture.md
  docs/kyma-environment-broker/assets/keb-architecture.svg
Labels: area/documentation, size/S, lgtm

#2144 Change env variables
  docs/kyma-environment-broker/03-05-authorization.md
Labels: area/documentation, size/XS, lgtm

#2150 add annotation for gardener-credentials secret allowing argoCD to skip
  resources/kcp/charts/provisioner/templates/gardener-creds-secret.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#2143 Redact sensitive data from pivotal library logs
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2152 Update of go libraries and basic docker image
  components/provisioner/Dockerfile
  components/provisioner/go.mod
  components/provisioner/go.sum
Labels: size/M, lgtm

#2147 Logs db connection failures for kyma-environment-broker
  components/kyma-environment-broker/internal/storage/postsql/init.go
Labels: size/XS, lgtm, ok-to-test

#2153 Update of dependencies for provisioner library
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/L, lgtm

#2114 API for KEB tracing events
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/events/handler.go
  components/kyma-environment-broker/internal/storage/dbmodel/events.go
  components/kyma-environment-broker/internal/storage/dbmodel/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/events/events.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  components/kyma-environment-broker/internal/storage/storage.go
  resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2157 Use StagedManager for updating process
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/update/apply_reconciler_configuration.go
  components/kyma-environment-broker/internal/process/update/automock/runtime_version_configurator_for_updating.go
  components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/update/check_step.go
  components/kyma-environment-broker/internal/process/update/check_step_test.go
  components/kyma-environment-broker/internal/process/update/conditions.go
  components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/update/init_kyma_step.go
  components/kyma-environment-broker/internal/process/update/initialisation_step.go
  components/kyma-environment-broker/internal/process/update/initialisation_step_test.go
  components/kyma-environment-broker/internal/process/update/sc_migration_check_step.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step_test.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2163 Swagger for events API in KEB
  resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
Labels: size/M, lgtm

#2142 Enable GraphQL introspection
  components/provisioner/cmd/main.go
Labels: hacktoberfest, size/XS, lgtm

#2115 bump build image in Dockerfile to golang1.19.2-alpine3.16 in KMC
  components/kyma-metrics-collector/Dockerfile
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2162 fixing security vulnerability
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/L, lgtm

#2170 Hanngos Codeowners Removal
  CODEOWNERS
Labels: size/S, lgtm

#2171 Bump golang.org/x/text to v0.4.0 in KEB
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/charts/kyma-environment-broker/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/S, lgtm

#2165 KEB istio config for events api
  resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
Labels: size/S, lgtm

#2175 Bump KEB and schema-migrator to go v1.19.2
  components/kyma-environment-broker/Makefile
  components/kyma-environment-broker/go.mod
  components/schema-migrator/Dockerfile
  components/schema-migrator/Makefile
  components/schema-migrator/go.mod
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#2176 Remove myself from CODEOWNERS
  CODEOWNERS
Labels: lgtm

#2154 Update deprovisioning docs
  docs/kyma-environment-broker/03-03-runtime-operations.md
Labels: area/documentation, size/L, lgtm

#2177 update reconciler images after kyma-incubator/reconciler#1205
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2178 Remove hanngos from OWNERS
  OWNERS
  resources/kcp/OWNERS
Labels: size/XS, lgtm

#2174 Added Own_cluster Plan to the Docs
  docs/kyma-environment-broker/03-01-service-description.md
Labels: area/documentation, size/S, lgtm

#2180 Update CODEOWNERS
  CODEOWNERS
Labels: size/S, lgtm

#2187 Update KCP README
  README.md
Labels: area/documentation, area/control-plane, size/S, lgtm

#2126 KCP: option to display KEB tracing events
  components/kyma-environment-broker/common/events/client.go
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/events/handler.go
  components/kyma-environment-broker/internal/storage/dbmodel/events.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/runtime.go
  tools/cli/pkg/printer/table.go
Labels: size/L, lgtm

#2189 Update KEB docs
  docs/kyma-environment-broker/03-01-service-description.md
  docs/kyma-environment-broker/03-03-runtime-operations.md
  docs/kyma-environment-broker/03-11-swagger.md
Labels: area/documentation, area/control-plane, size/M, lgtm

#2190 KCP: deduplicate KEB tracing events
  tools/cli/pkg/printer/table.go
Labels: size/M, lgtm

#2200 Enhance staged manager tracing events in KEB
  components/kyma-environment-broker/internal/process/staged_manager.go
  components/kyma-environment-broker/internal/storage/driver/postsql/events/events.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2198 Remove varbanv from CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#2204 Remove kwiatekus from reconciler charts
  CODEOWNERS
Labels: size/XS, lgtm

#2205 Remove myself from codeowners
  CODEOWNERS
  OWNERS
  resources/kcp/OWNERS
Labels: size/S, lgtm

#2210 Dropping tobiscr from` values.yaml` ownership
  CODEOWNERS
Labels: size/XS, lgtm

#2207 Remove myself from owners
  CODEOWNERS
Labels: size/XS, lgtm

#2179 Enable Preview plan in KEB
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/metrics/operations_collector.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/update/conditions.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/conditions.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/runtime/disabled_components.go
Labels: size/M, lgtm

#2156 Inject credentials into runtime
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/process/provisioning/conditions.go
  components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_test.go
  components/kyma-environment-broker/internal/process/provisioning/inject_btp_operator_credentials_step.go
  components/kyma-environment-broker/internal/process/provisioning/inject_btp_operator_credentials_step_test.go
  docs/kyma-environment-broker/03-03-runtime-operations.md
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: area/documentation, size/XL, lgtm, microdelivery-request

#2221 Secret injection omitted for time of investigation
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2188 Director dependency updated
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/director/directorclient.go
  components/provisioner/internal/director/directorclient_test.go
  components/provisioner/internal/director/mocks/DirectorClient.go
  components/provisioner/internal/director/query.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain.go
  resources/kcp/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/L, lgtm

#2224 Add the port forward option in the instruction on how to provision an…
  docs/kyma-control-plane/01-01-overview.md
  docs/kyma-environment-broker/08-01-provisioning-kyma-environment.md
Labels: area/documentation, area/control-plane, size/S, lgtm

#2223 Creating namespace before secret creation - fixing PR#2156
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/provisioning/inject_btp_operator_credentials_step.go
  components/kyma-environment-broker/internal/process/provisioning/inject_btp_operator_credentials_step_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2203 KEB tracing events refactor
  components/kyma-environment-broker/cmd/accountcleanup/main.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/environmentscleanup/main.go
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  components/kyma-environment-broker/common/events/client.go
  components/kyma-environment-broker/internal/events/handler/handler.go
  components/kyma-environment-broker/internal/events/interface.go
  components/kyma-environment-broker/internal/process/staged_manager.go
  components/kyma-environment-broker/internal/storage/dbmodel/events.go
  components/kyma-environment-broker/internal/storage/driver/postsql/conflict_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/events/events.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/orchestration_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtimestate_test.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  components/kyma-environment-broker/internal/storage/postsql/write.go
  components/kyma-environment-broker/internal/storage/storage.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm
