Repository kyma-project/control-plane, pull requests merged in 2022-03, with the labels that each got.

#1394 Remove unneeded, outdated KCP CLI docs
  docs/cli/01-01-overview.md
  docs/cli/02-01-usage.md
  docs/cli/commands/kcp.md
  docs/cli/commands/kcp_completion.md
  docs/cli/commands/kcp_kubeconfig.md
  docs/cli/commands/kcp_login.md
  docs/cli/commands/kcp_orchestrations.md
  docs/cli/commands/kcp_runtimes.md
  docs/cli/commands/kcp_taskrun.md
  docs/cli/commands/kcp_upgrade.md
  docs/cli/commands/kcp_upgrade_kyma.md
Labels: size/XL, lgtm

#1402 Update CODEOWNERS
  CODEOWNERS
Labels: size/S, lgtm

#1406 Remove RuntimeID from KEB metrics
  components/kyma-environment-broker/internal/metrics/operation_duration.go
  components/kyma-environment-broker/internal/metrics/operation_result.go
  components/kyma-environment-broker/internal/metrics/step_result.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1412 remove users from CODEOWNERS to fix errors
  CODEOWNERS
Labels: size/S, lgtm

#1407 Bump cloudsql-proxy to v1.29.0
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1393 modify codeowners for KMC
  CODEOWNERS
  OWNERS_ALIASES
  components/kyma-metrics-collector/OWNERS
  resources/kcp/charts/kyma-metrics-collector/OWNERS
Labels: size/M, lgtm

#1418 Resuse cluster name for reconciler calls
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/automock/provisioner_input_creator.go
  components/kyma-environment-broker/internal/process/provisioning/base_provision_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1421 Json output in ers tool
  tools/cli/pkg/ers/command/instances.go
Labels: size/S, lgtm

#1425 upgrade packages for kmc
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: area/eventing, size/M, lgtm

#1417 KEB bump gardener dependency to v1.41.1
  components/kyma-environment-broker/Makefile
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/cis/e2e/account_cleanup_test.go
  components/kyma-environment-broker/internal/reconciler/client_int_test.go
  components/kyma-environment-broker/internal/servicemanager/client_int_test.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1318 Register sc-migration reconciler
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1432 Update OWNERS and CODEOWNERS files
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
  resources/kcp/OWNERS
Labels: size/M, lgtm

#1408 Change the level of logs regarding "cluster kubeconfig is nil" error
  components/provisioner/internal/operations/executor.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
Labels: area/quality, area/control-plane, size/XS, lgtm

#1441 Remove obsoleted avs-bridge related code from KEB
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/avs/config.go
  components/kyma-environment-broker/internal/avs/delegator.go
  components/kyma-environment-broker/internal/avs/eval_assistant.go
  components/kyma-environment-broker/internal/avs/external_eval_assistant.go
  components/kyma-environment-broker/internal/avs/internal_eval_assistant.go
  components/kyma-environment-broker/internal/process/provisioning/internal_eval_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/internal_eval.go
Labels: size/M, lgtm

#1405 Errors categorization - changes for provisioner and schema-migrator
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/tenant_updater.go
  components/provisioner/internal/apperrors/apperrors.go
  components/provisioner/internal/apperrors/presenter.go
  components/provisioner/internal/apperrors/presenter_test.go
  components/provisioner/internal/director/directorclient.go
  components/provisioner/internal/gardener/kubeconfig_provider.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/installation/release/provider.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/oauth/client.go
  components/provisioner/internal/operations/executor.go
  components/provisioner/internal/operations/executor_test.go
  components/provisioner/internal/operations/stages/provisioning/connect_agent.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
  components/provisioner/internal/operations/stages/provisioning/install_kyma.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_installation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_installation_test.go
  components/provisioner/internal/operations/types.go
  components/provisioner/internal/persistence/dberrors/types.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/runtime/configurator.go
  components/provisioner/internal/util/errors.go
  components/provisioner/internal/util/k8s/client_provider.go
  components/provisioner/internal/util/k8s/k8s.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202202241500_operation_last_error.down.sql
  components/schema-migrator/migrations/provisioner/202202241500_operation_last_error.up.sql
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#1443 Set provisioning parameters when processing deprovisioning operation
  components/kyma-environment-broker/internal/metrics/operation_result.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1424 Add GIT CLONE TOKEN environment variable to the Component Reconciler
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
Labels: area/control-plane, size/XS, lgtm

#1452 Disable SQL validator
  resources/kcp/charts/mothership-reconciler/files/reconciler.yaml
Labels: size/XS, lgtm

#1455 KEB Libraries Upgrade
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
Labels: size/L, lgtm

#1454 Reduce retention of reconciliations to 4days
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
Labels: size/XS, lgtm

#1463 Bump Provisioners base images
  components/provisioner/Dockerfile
  resources/kcp/values.yaml
Labels: area/control-plane, size/XS, lgtm

#1428 add service monitor to component reconciler
  resources/kcp/charts/component-reconcilers/charts/rma/templates/deployment.yaml
  resources/kcp/charts/component-reconcilers/templates/authorization.yaml
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/charts/component-reconcilers/templates/policy.yaml
  resources/kcp/charts/component-reconcilers/templates/service-monitor.yaml
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/M, lgtm

#1444 KCP CLI: update dependencies, get token compatible with SKR operator kubeconfig
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/credential/manager.go
  tools/cli/pkg/logger/logger.go
Labels: size/XXL, approved, lgtm

#1473 Normalise user input for isserURL
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
Labels: size/M, lgtm

#1475 Remane istio component
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/XS, lgtm

#1476 Normalize user input for isserURL - image bump
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1462 Fix bug in last error "converting NULL to string is unsupported"
  components/provisioner/assets/database/provisioner.sql
  components/schema-migrator/migrations/provisioner/202203171600_operation_alter_last_error.down.sql
  components/schema-migrator/migrations/provisioner/202203171600_operation_alter_last_error.up.sql
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1479 Point to the new provisioner version in KEB
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1482 add PeerAuthentication ServiceMonitor for rma
  resources/kcp/charts/component-reconcilers/charts/rma/templates/policy.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/templates/service-monitor.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/values.yaml
Labels: size/M, lgtm

#1483 Bump KMC dependencies
  components/kyma-metrics-collector/Dockerfile
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1487 remove duplicate manifest in rma
  resources/kcp/charts/component-reconcilers/charts/rma/templates/authorization.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/templates/policy.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/templates/service-monitor.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/values.yaml
  resources/kcp/charts/component-reconcilers/templates/authorization.yaml
Labels: size/M, lgtm

#1491 Do not use empty region
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider_test.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  components/kyma-environment-broker/internal/provider/openstack_provider.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1495 Template for reconciler when reconciling Kyma2.1.x
  tools/reconciler/e2e-test/template-kyma-2-1-x.json
Labels: size/L, lgtm

#1494 Enable dependabot for KEB
  .github/dependabot-config.yaml
  .github/dependabot.yml
Labels: size/M, lgtm

#1436 ERS CLI - Migration and Logs Commands
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/ers/client/api.go
  tools/cli/pkg/ers/client/client.go
  tools/cli/pkg/ers/client/http.go
  tools/cli/pkg/ers/command/broker.go
  tools/cli/pkg/ers/command/client_utils.go
  tools/cli/pkg/ers/command/colors.go
  tools/cli/pkg/ers/command/instances.go
  tools/cli/pkg/ers/command/logs.go
  tools/cli/pkg/ers/command/migrate_all.go
  tools/cli/pkg/ers/command/migration.go
  tools/cli/pkg/ers/command/root.go
  tools/cli/pkg/ers/command/status.go
  tools/cli/pkg/ers/fetcher/file.go
  tools/cli/pkg/ers/model.go
  tools/cli/pkg/ers/options.go
Labels: size/XXL, lgtm

#1504 Fake ers client in ers tool
  tools/cli/pkg/ers/client/fake.go
  tools/cli/pkg/ers/command/migrate_all.go
Labels: size/L, lgtm

#1505 Remove unnecessary messages in ers tool
  tools/cli/pkg/ers/client/http.go
  tools/cli/pkg/ers/command/instances.go
Labels: size/S, lgtm

#1507 Simple Stats
  tools/cli/pkg/ers/command/migrate_all.go
  tools/cli/pkg/ers/command/stats.go
Labels: size/M, lgtm

#1431 kcp-cli orchestration sends slack info message
  tools/cli/pkg/command/options.go
  tools/cli/pkg/command/send_slack_notification.go
  tools/cli/pkg/command/upgrade_cluster.go
  tools/cli/pkg/command/upgrade_kyma.go
Labels: size/L, lgtm

#1480 update dashboard
  resources/kcp/charts/mothership-reconciler/files/dashboard.json
Labels: size/XXL, lgtm

#1478 Add Shoot Networking Filter Extension to the Provisioners API
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/util/pointers.go
  components/provisioner/internal/util/testkit/shoot.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202203231500_add_shoot_networking_filter_disabled.down.sql
  components/schema-migrator/migrations/provisioner/202203231500_add_shoot_networking_filter_disabled.up.sql
  resources/kcp/values.yaml
Labels: area/control-plane, size/XL, lgtm

#1513 Fix aws lite regions
  components/kyma-environment-broker/internal/provider/aws_provider.go
  resources/kcp/values.yaml
Labels: size/S, lgtm
