Repository kyma-project/control-plane, pull requests merged in 2022-08, with the labels that each got.

#1902 Trial cleaner job with dummy logic
  components/kyma-environment-broker/Dockerfile.tcj
  components/kyma-environment-broker/Makefile
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  scripts/generic_make_go.mk
Labels: size/M, lgtm

#1862 Newest Versions of Schema Migrator
  components/schema-migrator/main.go
  resources/kcp/templates/migrator-job.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1900 Add expiredAt
  components/kyma-environment-broker/common/runtime/client.go
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/runtime/handler.go
  components/kyma-environment-broker/internal/storage/dbmodel/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  components/kyma-environment-broker/internal/storage/postsql/write.go
  components/schema-migrator/migrations/kyma-environment-broker/202207281547_add_expired_at.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202207281547_add_expired_at.up.sql
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
  tools/cli/pkg/command/runtime.go
Labels: size/M, lgtm

#1904 Plain Cloud Sql Proxy Image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1914 Ignoring No Migration Changes Error
  components/schema-migrator/main.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1916 Additional Info Logs
  components/schema-migrator/main.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1881 Incorporate ConfigProvider in the queue
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/orchestration_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/input/automock/component_list_provider.go
  components/kyma-environment-broker/internal/process/input/automock/configuration_provider.go
  components/kyma-environment-broker/internal/process/input/automock/creator_for_plan.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/builder_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/automock/provisioner_input_creator.go
  components/kyma-environment-broker/internal/process/provisioning/base_provision_test.go
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration_test.go
  components/kyma-environment-broker/internal/process/update/automock/runtime_version_configurator_for_updating.go
  components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/update/initialisation_step.go
  components/kyma-environment-broker/internal/process/update/initialisation_step_test.go
  components/kyma-environment-broker/internal/process/update/manager.go
  components/kyma-environment-broker/internal/process/update/sc_migration.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/automock/creator_for_plan.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/simple_provisioner_input_creator_test.go
  components/kyma-environment-broker/internal/runtime/components_provider.go
  components/kyma-environment-broker/internal/runtime/components_provider_fake.go
  components/kyma-environment-broker/internal/runtime/components_provider_test.go
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XXL, lgtm

#1918 Volume for Reading Cloudsql PID
  components/schema-migrator/main.go
  resources/kcp/templates/migrator-job.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1921 Fix migrator yaml file
  resources/kcp/templates/migrator-job.yaml
Labels: size/XS, lgtm

#1923 Schema Migrator Revert
  components/schema-migrator/Dockerfile
  components/schema-migrator/Makefile
  components/schema-migrator/doc.go
  components/schema-migrator/go.mod
  components/schema-migrator/main.go
  components/schema-migrator/run.sh
  resources/kcp/templates/migrator-job.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1915 Listing trial jobs to expire
  components/kyma-environment-broker/Dockerfile.tcj
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  components/kyma-environment-broker/internal/storage/dbmodel/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#1928 Added Not Reverted Image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1932 Dry run based on env
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1930 Fix getting last kyma version
  components/kyma-environment-broker/cmd/broker/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
  components/kyma-environment-broker/internal/storage/driver/memory/runtime_state.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#1933 Kill sql proxy in trial cleaner job
  components/kyma-environment-broker/Dockerfile.tcj
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1935 Fixes for logic and image in trial cleaner job
  components/kyma-environment-broker/Dockerfile.tcj
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#1934 Add dependabot helper for KEB
  scripts/dependabot_helper.bash
Labels: size/S, lgtm

#1941 Update Framefrog OWNERS
  CODEOWNERS
  OWNERS
  resources/kcp/OWNERS
Labels: area/control-plane, size/S, lgtm

#1940 Bump alpine image in Provisioner
  components/provisioner/Dockerfile
  resources/kcp/values.yaml
Labels: area/control-plane, area/security, size/XS, lgtm

#1936 Extraction of Gcloud/Istio Proxy Halt Methods
  components/schema-migrator/Makefile
  components/schema-migrator/cleaner/halt.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1922 Consume expired
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/instance_update_test.go
  components/kyma-environment-broker/internal/dto.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#1692 Add deprovision command to kcp cli
  tools/cli/pkg/command/deprovision.go
  tools/cli/pkg/command/options.go
  tools/cli/pkg/command/root.go
Labels: size/L, lgtm

#1945 Allow to expire failed instsances
  components/kyma-environment-broker/internal/broker/instance_update.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#1950 Fix update endpoint, error must not be null
  components/kyma-environment-broker/internal/broker/instance_update.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1949 Changed Schema Migrator Module Declaration Path
  components/schema-migrator/go.mod
Labels: size/XS, lgtm

#1937 Configurable interval for expiration evaluation
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#1863 Add prompting on cancel and retry operations on kcp cli
  tools/cli/pkg/command/orchestration.go
Labels: size/M, lgtm

#1951 Setting expiration period in hours
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1947 n2-standard-48 restored since gardener allows this machine type at last
  components/kyma-environment-broker/internal/broker/plans.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1955 Add telemetry component to reconciler e2e-test template
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/S, lgtm

#1925 Corrected Version of Go Migrator
  components/kyma-environment-broker/cmd/accountcleanup/main.go
  components/kyma-environment-broker/cmd/environmentscleanup/main.go
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/schema-migrator/Dockerfile
  components/schema-migrator/Makefile
  components/schema-migrator/doc.go
  components/schema-migrator/main.go
  components/schema-migrator/run.sh
  components/schema-migrator/validate.sh
  resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/templates/migrator-job.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1946 KEB config for given Kyma version and plan docs
  docs/kyma-environment-broker/03-14-broker-configuration-for-given-version-and-plan.md
Labels: area/documentation, size/M, lgtm

#1953 Require succeeded suspension to call unsuspension
  components/kyma-environment-broker/internal/process/provisioning/check_runtime_step.go
  components/kyma-environment-broker/internal/process/update/check_step.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation.go
  components/kyma-environment-broker/internal/suspension/handler.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#1956 Remove UAA cleanup from deprovisioning queue
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XL, lgtm

#1963 Remove sc-migration reconciler
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1961 Send patch to broker for to be expired instances
  components/kyma-environment-broker/Dockerfile.tcj
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  components/kyma-environment-broker/internal/broker/client.go
  components/kyma-environment-broker/internal/broker/client_test.go
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#1944 Feature/kcp cli allows to get keb operation details
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/runtime/converter_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#1967 Delete oauth2 config from required list of params
  tools/cli/pkg/command/options.go
Labels: size/XS, lgtm

#1962 Removed Shell from Env Cleanup Job
  resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
Labels: size/XS, lgtm

#1970 Feature/kcp cli allows to get keb operation details
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/runtime/converter_test.go
Labels: size/M, lgtm

#1971 Newest Images in KEB
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1972 KEB Trial expiration labels
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/instance_get.go
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  components/kyma-environment-broker/internal/broker/response_labels.go
  components/kyma-environment-broker/internal/broker/response_labels_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#1966 Update request to make trial expire
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  components/kyma-environment-broker/internal/broker/client.go
  components/kyma-environment-broker/internal/broker/client_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#1978 Added Missing Connection Closure
  components/kyma-environment-broker/cmd/accountcleanup/main.go
  components/kyma-environment-broker/cmd/environmentscleanup/main.go
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#1977 bump deps in `kyma-metrics-collector`
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1979 Expiration labels fix
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/instance_get.go
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  components/kyma-environment-broker/internal/broker/response_labels.go
  components/kyma-environment-broker/internal/broker/response_labels_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#1981 Bump KEB img to the latest ver
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1849 KEB: add support for multiple availability zones in AWS, Azure and GCP plans
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/common/hyperscaler/azure/env.go
  components/kyma-environment-broker/common/hyperscaler/azure/env_test.go
  components/kyma-environment-broker/internal/avs/model.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/services_test.go
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema.json
  components/kyma-environment-broker/internal/broker/testdata/openstack-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/openstack-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-ha-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-ha-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema.json
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/metrics/operations_collector.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/builder_test.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
  components/kyma-environment-broker/internal/process/provisioning/edp_registration_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/aws_provider_test.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider_test.go
  components/kyma-environment-broker/internal/provider/common.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  components/kyma-environment-broker/internal/provider/gcp_provider_test.go
  components/kyma-environment-broker/internal/provider/openstack_provider.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  components/kyma-environment-broker/internal/runtime/disabled_components.go
  docs/kyma-environment-broker/03-01-service-description.md
  resources/kcp/charts/kyma-environment-broker/files/catalog.yaml
  resources/kcp/charts/kyma-environment-broker/files/dashboard.json
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: area/documentation, size/XXL, lgtm

#1982 KEB add a label with trial docs
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  components/kyma-environment-broker/internal/broker/response_labels.go
  components/kyma-environment-broker/internal/broker/response_labels_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#1969 Add New Machine Type for Azure
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema.json
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#1988 Approve dependabot PRs
  scripts/dependabot_helper.bash
Labels: size/XS, lgtm

#1985 enhancement: kubeconfig service slow start
  components/kubeconfig-service/cmd/generator/main.go
  components/kubeconfig-service/pkg/runtime/runtime.go
  components/kubeconfig-service/pkg/runtime/runtime_kcp.go
  resources/oidc-kubeconfig-service/templates/deployment.yaml
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/M, lgtm

#1974 BTP-Operator cleanup for suspensions
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup.go
  components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XL, lgtm

#1938 improve orchestration retry cmd
  components/kyma-environment-broker/common/orchestration/client_test.go
  components/kyma-environment-broker/common/orchestration/dto.go
  components/kyma-environment-broker/common/orchestration/strategies/parallel.go
  components/kyma-environment-broker/internal/orchestration/handlers/cluster_retry.go
  components/kyma-environment-broker/internal/orchestration/handlers/kyma_retry.go
  components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler_test.go
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/storage/dbmodel/operation.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
  tools/cli/pkg/command/orchestration.go
  tools/cli/pkg/command/orchestration_test.go
Labels: size/XXL, lgtm

#1958 Fix kubeconfig-service errors and L2 operator permissions
  CODEOWNERS
  components/kubeconfig-service/pkg/runtime/runtime.go
  components/kubeconfig-service/pkg/runtime/runtime_test.go
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/L, lgtm

#1989 Trial cleanup job logging enhanced and summary fixed
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  components/kyma-environment-broker/internal/broker/client.go
  components/kyma-environment-broker/internal/broker/client_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#1991 Trial expire info for trial plans only
  components/kyma-environment-broker/internal/broker/instance_get.go
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#1995 Fix missing quote around .Values.gardener.kubernetesVersion
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
Labels: size/XS, lgtm

#1960 update fluent bit for reconciler sidecar
  resources/kcp/charts/mothership-reconciler/templates/auditlog-config.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1999 Improve dependabot PR filter
  scripts/dependabot_helper.bash
Labels: size/XS, lgtm

#2000 Kubeconfig field added to provisioning request
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/dto.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#1723 Remove sc-migration code
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/last_operation_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/testdata/additional-runtime-components.yaml
  components/kyma-environment-broker/cmd/broker/testdata/kyma-components.yaml
  components/kyma-environment-broker/cmd/broker/testdata/managed-runtime-components.yaml
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_cluster_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/component_input_helpers.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/conditions.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/start_step.go
  components/kyma-environment-broker/internal/process/update/btp_operator_check.go
  components/kyma-environment-broker/internal/process/update/btp_operator_check_test.go
  components/kyma-environment-broker/internal/process/update/conditions.go
  components/kyma-environment-broker/internal/process/update/init_kyma_step.go
  components/kyma-environment-broker/internal/process/update/initialisation_step.go
  components/kyma-environment-broker/internal/process/update/sc_migration.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/conditions.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/runtime/components_provider_test.go
  components/kyma-environment-broker/internal/runtime/testdata/additional-runtime-components.yaml
  components/kyma-environment-broker/internal/runtime/testdata/kyma-components.yaml
  components/kyma-environment-broker/internal/runtime/testdata/managed-runtime-components.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XXL, lgtm

#1666 Drop rafter reconciler from control-plane configuration
  .github/ISSUE_TEMPLATE/documentation-improvement.md
  .kyma-project-io/build-preview.sh
  .kyma-project-io/docs-kcp-cag.yaml
  .kyma-project-io/docs-keb.cag.yaml
  .kyma-project-io/docs-provisioner-cag.yaml
  docs/internal/runtime-upgrade.md
  resources/kcp/charts/mothership-reconciler/files/dashboard.json
  resources/kcp/values.yaml
  tools/cli/pkg/command/testdata/configVersionResponse.json
  tools/cli/pkg/command/testdata/reconciliationInfoResponse.json
  tools/reconciler/e2e-test/template-kyma-2-0-x.json
  tools/reconciler/e2e-test/template-kyma-2-1-x.json
Labels: area/documentation, size/L, lgtm

#2001 KEB returns http 200 for an update of expired instances
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/instance_update_test.go
  components/kyma-environment-broker/internal/suspension/handler.go
  components/kyma-environment-broker/internal/suspension/handler_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#1992 keb: introduce new operations metrics compass_keb_operation_result
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/cloudprovider/factory.go
  components/kyma-environment-broker/cmd/subscriptioncleanup/cloudprovider/mocks/ProviderFactory.go
  components/kyma-environment-broker/common/director/automock/GraphQLClient.go
  components/kyma-environment-broker/common/director/client.go
  components/kyma-environment-broker/common/hyperscaler/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/automock/account_provider.go
  components/kyma-environment-broker/common/orchestration/automock/runtime_resolver.go
  components/kyma-environment-broker/common/orchestration/automock/strategy.go
  components/kyma-environment-broker/common/orchestration/runtime_lister_mock.go
  components/kyma-environment-broker/internal/appinfo/automock/instance_finder.go
  components/kyma-environment-broker/internal/appinfo/runtime_info.go
  components/kyma-environment-broker/internal/broker/automock/plan_validator.go
  components/kyma-environment-broker/internal/broker/automock/queue.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/cis/account_cleanup.go
  components/kyma-environment-broker/internal/cis/automock/BrokerClient.go
  components/kyma-environment-broker/internal/cis/automock/CisClient.go
  components/kyma-environment-broker/internal/environmentscleanup/automock/BrokerClient.go
  components/kyma-environment-broker/internal/environmentscleanup/automock/GardenerClient.go
  components/kyma-environment-broker/internal/environmentscleanup/automock/ProvisionerClient.go
  components/kyma-environment-broker/internal/environmentscleanup/service.go
  components/kyma-environment-broker/internal/environmentscleanup/service_test.go
  components/kyma-environment-broker/internal/ias/automock/bundle.go
  components/kyma-environment-broker/internal/ias/automock/bundle_builder.go
  components/kyma-environment-broker/internal/ias/builder.go
  components/kyma-environment-broker/internal/ias/bundle.go
  components/kyma-environment-broker/internal/kubeconfig/automock/kc_builder.go
  components/kyma-environment-broker/internal/kubeconfig/handler.go
  components/kyma-environment-broker/internal/metrics/operations_db_collector.go
  components/kyma-environment-broker/internal/process/deprovisioning/automock/edp_client.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration.go
  components/kyma-environment-broker/internal/process/input/automock/components_disabler.go
  components/kyma-environment-broker/internal/process/input/automock/optional_component_service.go
  components/kyma-environment-broker/internal/process/provisioning/automock/director_client.go
  components/kyma-environment-broker/internal/process/provisioning/automock/edp_client.go
  components/kyma-environment-broker/internal/process/provisioning/automock/runtime_version_configurator_for_provisioning.go
  components/kyma-environment-broker/internal/process/provisioning/edp_registration.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/automock/runtime_version_configurator_for_upgrade.go
  components/kyma-environment-broker/internal/provisioner/automock/client.go
  components/kyma-environment-broker/internal/provisioner/client.go
  components/kyma-environment-broker/internal/reconciler/client.go
  components/kyma-environment-broker/internal/storage/automock/operations.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XL, lgtm

#2006 Use runtime scheme per unit test thread
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup_test.go
  components/kyma-environment-broker/internal/test_utils.go
Labels: size/S, lgtm
