Repository kyma-project/control-plane, pull requests merged in 2022-05, with the labels that each got.

#1655 Fix shootName fetch
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/suspension/handler_test.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1633 Expose Detailed Metrics for Reconciler Audit Log Sidecar
  resources/kcp/charts/mothership-reconciler/templates/authorization.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/service-monitor.yaml
  resources/kcp/charts/mothership-reconciler/templates/service.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/S, lgtm

#1658 Skip GetKubeconfig step in deprovisioning when kubeconfig is not provided
  components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/utils.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1243 Extraction of PollImmediate Functions
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
Labels: size/L, lgtm, lifecycle/stale

#1651 Overrides for btp-operator v0.2.3
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/component_input_helpers.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1659 bump dependencies in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1611 ERS CLI changes
  .gitignore
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/ers/client/fake.go
  tools/cli/pkg/ers/command/metadata.go
  tools/cli/pkg/ers/command/migrate_all.go
  tools/cli/pkg/ers/command/root.go
  tools/cli/pkg/ers/metadata/storage.go
  tools/cli/pkg/ers/metadata/storage_test.go
  tools/cli/pkg/ers/model.go
Labels: size/L, lgtm

#1669 Bump reconciler to f342be0b
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1664 KMC bump gardener
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1673 bump gardener/gardener-extension-provider-azure
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1667 Fix list instances query
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/runtime/handler.go
  components/kyma-environment-broker/internal/runtime/handler_test.go
  components/kyma-environment-broker/internal/storage/dbmodel/instance.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  components/kyma-environment-broker/internal/suspension/handler.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1674 Update btp-operator overrides on KEB update operation
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1676 KEB manages cluster-id in cluster-config ConfigMap in SKR
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/component_input_helpers.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
  components/kyma-environment-broker/internal/process/update/apply_reconciler_configuration.go
  components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/btp_operator_overrides.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1683 fix error in codeowners
  CODEOWNERS
Labels: size/XS, lgtm

#1672 ERS cli changes, block already migrated
  tools/cli/pkg/ers/command/migrate_all.go
  tools/cli/pkg/ers/model.go
Labels: size/S, lgtm

#1682 bump the build image to golang 1.18.2 in EC
  components/kyma-metrics-collector/Dockerfile
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1689 bump dependency github.com/gardener/gardener to 1.46.1 in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1694 Do not spam ers
  tools/cli/pkg/ers/command/migrate_all.go
Labels: size/XS, lgtm

#1695 fix kubeconfig-service checkmarx issue
  components/kubeconfig-service/pkg/endpoints/endpoint.go
Labels: size/XS, lgtm

#1693 Increase concurrency for KEB processing update operations
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/update/manager.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1696 bump prometheus/client_golang to 1.12.2 in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1685 Handle migration for suspended SKRs
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/suspension/handler.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1701 bump gardener to 1.46.2
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1706 Bump cloudsql-proxy image to v1.30.1
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1702 Update dependencies and base docker images for provisioner
  components/provisioner/Dockerfile
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1700 Comparing modifiedAt before and after migration and finish earlier wh…
  tools/cli/.gitignore
  tools/cli/pkg/ers/command/migrate_all.go
  tools/cli/pkg/ers/command/stats.go
  tools/cli/pkg/ers/model.go
Labels: size/M, lgtm

#1707 Update opencontainers/runc in Kyma Runtime Provisioner to latest version v1.1.2
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1710 Map last operation state to compliant OSB operation states
  components/kyma-environment-broker/internal/broker/instance_last_operation.go
  components/kyma-environment-broker/internal/broker/instance_last_operation_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1708 Add error categorization for deprovision step Remove_ServiceInstance
  components/kyma-environment-broker/internal/error/errors.go
  components/kyma-environment-broker/internal/error/errors_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1719 Update docker dependency to v20.10.16
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
Labels: size/XS, lgtm

#1705 Enable debug logs for KCP CLI
  components/reconciler/makefile
  components/reconciler/pkg/automock/client.go
  components/reconciler/pkg/client_gen.go
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/operation.go
  tools/cli/pkg/command/operation_debug_logs.go
  tools/cli/pkg/command/operation_debug_logs_test.go
  tools/cli/pkg/command/reconciliation_debug_logs.go
  tools/cli/pkg/command/reconciliation_debug_logs_test.go
  tools/cli/pkg/command/reconciliations.go
Labels: size/XL, lgtm

#1711 bump gardener/gardener-extension-provider-gcp to 1.22.1 in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1714 parsing oidc token to differentiate the L2L3 operators
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  components/kubeconfig-service/pkg/authn/middleware.go
  components/kubeconfig-service/pkg/authn/middleware_test.go
  components/kubeconfig-service/pkg/authn/oidc.go
  components/kubeconfig-service/pkg/endpoints/endpoint.go
  components/kubeconfig-service/pkg/runtime/runtime.go
  components/kubeconfig-service/pkg/runtime/runtime_test.go
  components/kubeconfig-service/pkg/transformer/kubeconfig.go
  components/kubeconfig-service/pkg/transformer/transformer.go
  components/kubeconfig-service/pkg/transformer/transformer_test.go
Labels: size/XXL, lgtm

#1726 update to go1.18.2 for kubeconfig-service
  components/kubeconfig-service/Dockerfile
Labels: size/XS, lgtm

#1729 Fix GetKubeconfig step in deprovisioning queue
  components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_service_instance.go
  components/kyma-environment-broker/internal/process/deprovisioning/utils.go
  resources/kcp/values.yaml
Labels: size/L, lgtm
