Repository kyma-project/control-plane, pull requests merged in 2022-12, with the labels that each got.

#2322 Expose the EU Access field in the Provisioner schema
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/schema-migrator/migrations/provisioner/202212051431_eu_access.down.sql
  components/schema-migrator/migrations/provisioner/202212051431_eu_access.up.sql
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-04-runtime-status.md
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
Labels: area/documentation, area/control-plane, size/L, lgtm

#2326 KCP remove replace in go modules for KEB dependency
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/XS, lgtm

#2330 kcp-migration-broker and provisioner - change on helm hook annotations
  resources/kcp/templates/migrator-job.yaml
Labels: size/XS, lgtm, ok-to-test

#2332 remove eventing reconciler
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2334 enhancement: add retry for RBAC deletion
  components/kubeconfig-service/pkg/runtime/runtime.go
Labels: size/S, lgtm

#2337 Bump subscription cleanup job go to 1.19.4
  components/kyma-environment-broker/Dockerfile.scj
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2338 Bump reconciler image to panic fix in Istio reconciler
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2329 Enchance kcp events
  tools/cli/pkg/command/runtime.go
  tools/cli/pkg/printer/table.go
Labels: size/M, lgtm

#2327 EU Access parameter passed to provisioner
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_step.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
  components/kyma-environment-broker/internal/process/provisioning/enable_for_trial_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/internal_eval_updater_test.go
  components/kyma-environment-broker/internal/process/staged_manager.go
  components/kyma-environment-broker/internal/process/update/manager.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  resources/kcp/charts/kyma-environment-broker/files/dashboard.json
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm, microdelivery-request

#2335 bump golang-runtime version
  .github/dependabot.yml
  CODEOWNERS
  components/kubeconfig-service/Dockerfile
  components/kubeconfig-service/Makefile
  components/kubeconfig-service/pkg/authn/oidc.go
  components/kubeconfig-service/pkg/caller/caller.go
  components/kubeconfig-service/pkg/endpoints/endpoint.go
  components/kubeconfig-service/pkg/reload/reload.go
  components/kubeconfig-service/pkg/reload/watch.go
  components/kubeconfig-service/pkg/transformer/transformer.go
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/L, lgtm

#2363 Explicit err check before err wrapping
  components/kyma-environment-broker/cmd/environmentscleanup/main.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2353 Bump Golang in Provisioner and SCJ
  components/kyma-environment-broker/Dockerfile.scj
  components/provisioner/Dockerfile
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
Labels: area/control-plane, size/L, lgtm

#2366 Connectivity Proxy Image bump
  resources/kcp/charts/component-reconcilers/values.yaml
Labels: size/XS, lgtm

#2315 Hap eu access
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/hyperscaler/account_pool.go
  components/kyma-environment-broker/common/hyperscaler/account_pool_test.go
  components/kyma-environment-broker/common/hyperscaler/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/account_provider_test.go
  components/kyma-environment-broker/common/hyperscaler/automock/account_provider.go
  components/kyma-environment-broker/common/hyperscaler/shared_pool.go
  components/kyma-environment-broker/common/hyperscaler/shared_pool_test.go
  components/kyma-environment-broker/internal/component_input_helpers.go
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds.go
  components/kyma-environment-broker/internal/process/provisioning/resolve_creds_test.go
  docs/kyma-environment-broker/03-04-hyperscaler-account-pool.md
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: area/documentation, size/XXL, lgtm, microdelivery-request

#2302 Change Application Connector secret namespace to kyma-system
  components/kyma-environment-broker/cmd/broker/testdata/kyma-installer-cluster.yaml
  components/kyma-environment-broker/internal/runtime/testdata/kyma-components.yaml
  components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/installation/installation_test.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter_test.go
  docs/internal/runtime-upgrade.md
  tests/provisioner-tests/test/testkit/inputs.go
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: area/documentation, size/M, lgtm

#2306 Add configmaps for new migrations
  components/schema-migrator/README.md
  components/schema-migrator/create_migration.sh
  components/schema-migrator/validate.sh
  resources/kcp/charts/kyma-environment-broker/templates/keb-migrations.yaml
  resources/kcp/charts/provisioner/templates/provisioner-migrations.yaml
  resources/kcp/templates/migrator-job.yaml
Labels: area/documentation, size/M, lgtm

#2341 Do not Log kubeconfig hash
  components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2368 EU Access in KEB - documentation update
  docs/eu_access.md
  docs/kyma-environment-broker/02-02-broker-endpoints.md
  docs/kyma-environment-broker/03-01-service-description.md
Labels: area/documentation, size/M, lgtm

#2370 EU Access in KEB - handling default regions
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/aws_provider_test.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2369 Change events flag var type
  components/kyma-environment-broker/common/runtime/model.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2351 Add event filtering
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/runtime.go
  tools/cli/pkg/printer/table.go
Labels: size/M, lgtm
