Repository kyma-project/control-plane, pull requests merged in 2022-06, with the labels that each got.

#1736 [testing]feature: kcp runtime functions for kubeconfig-serivce
  components/kubeconfig-service/cmd/generator/main.go
  components/kubeconfig-service/pkg/endpoints/endpoint.go
  components/kubeconfig-service/pkg/runtime/runtime.go
  components/kubeconfig-service/pkg/runtime/runtime_kcp.go
  components/kubeconfig-service/pkg/runtime/runtime_test.go
Labels: size/L, lgtm

#1740 Store ERS context on kyma upgrade
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/process/update/initialisation_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1745 Fix KCP CLI prow jobs
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/S, lgtm

#1721 reduce redention of reconciliation from 150 to 100
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#1748 Disable flaky TestKymaUpgrade_UpgradeAfterMigrationWithNetworkPolicy
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
Labels: size/XS, lgtm

#1712 Preview Plan Removal
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/metrics/operations_collector.go
  components/kyma-environment-broker/internal/orchestration/config.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/runtime/disabled_components.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion_test.go
  docs/kyma-environment-broker/03-01-service-description.md
  docs/kyma-environment-broker/03-08-kyma-versions.md
  resources/kcp/charts/kyma-environment-broker/files/dashboard.json
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: area/documentation, size/L, lgtm

#1750 Version Bumps
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
Labels: size/L, lgtm

#1751 Reduce flakiness on ERS context unit test
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_cluster_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1758 SC components must be always disabled
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1749 Handle not existing runtimes in provisioner by environments cleaner
  components/kyma-environment-broker/internal/environmentscleanup/service.go
  components/kyma-environment-broker/internal/provisioner/client.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1752 bump dependencies in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1763 Add runtimeID to log message
  components/kyma-metrics-collector/pkg/cache/record.go
  components/kyma-metrics-collector/pkg/logger/logger.go
  components/kyma-metrics-collector/pkg/process/process.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1764 bump the golang image to golang1.18.3:alpine3.16 in KMC
  components/kyma-metrics-collector/Dockerfile
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1765 Bump dependencies kmc
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1769 Version Bumps
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
Labels: size/XS, lgtm

#1766 Remove unnecessary Kyma versions conditions
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/process/update/conditions.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1773 Speed up orchestration for tests
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/orchestration/ext.go
  components/kyma-environment-broker/common/orchestration/strategies/parallel.go
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
Labels: size/M, lgtm

#1686 New additional components provider
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/iosafety/iosafety.go
  components/kyma-environment-broker/internal/process/input/automock/component_list_provider.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/builder_test.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/update/manager.go
  components/kyma-environment-broker/internal/process/update/sc_migration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/upgrade_kyma_step_test.go
  components/kyma-environment-broker/internal/runtime/components_provider.go
  components/kyma-environment-broker/internal/runtime/components_provider_fake.go
  components/kyma-environment-broker/internal/runtime/components_provider_test.go
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
  components/kyma-environment-broker/internal/runtime/testdata/additional-runtime-components.yaml
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1768 bump gardener to 1.48.1 in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1767 Simplify Dependabot config
  .github/dependabot-config.yaml
  .github/dependabot.tmpl
  .github/dependabot.yml
Labels: size/M, lgtm

#1738 Exclude canceled and retrying operation states when treating last operation
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1746 Disable ShootNetworkingFilter by default
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/gardener/shoot_provider.go
  components/provisioner/internal/gardener/shoot_provider_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/mocks/KubernetesVersionProvider.go
  components/provisioner/internal/provisioning/mocks/ShootProvider.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/pkg/gqlschema/schema.graphql
  resources/kcp/values.yaml
Labels: area/control-plane, size/XL, lgtm

#1774 Btp operator creds in docs
  docs/kyma-environment-broker/08-01-provisioning-kyma-environment.md
Labels: area/documentation, size/M, lgtm

#1744 Kubeconfig service refactor
  components/kubeconfig-service/cmd/generator/main.go
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  components/kubeconfig-service/pkg/authn/middleware.go
  components/kubeconfig-service/pkg/authn/middleware_test.go
  components/kubeconfig-service/pkg/authn/oidc.go
  components/kubeconfig-service/pkg/endpoints/endpoint.go
  components/kubeconfig-service/pkg/runtime/runtime.go
  components/kubeconfig-service/pkg/runtime/runtime_kcp.go
  components/kubeconfig-service/pkg/runtime/runtime_test.go
  components/kubeconfig-service/pkg/transformer/kubeconfig.go
  components/kubeconfig-service/pkg/transformer/transformer.go
  components/kubeconfig-service/pkg/transformer/transformer_test.go
  installation/resources/installer-cr.yaml.tpl
  resources/oidc-kubeconfig-service/templates/rbac.yaml
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XXL, lgtm

#1778 bump dependencies in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1772 License type sync to KEB
  tools/license_type_sync.bash
Labels: size/M, lgtm

#1782 Return state suspended for all suspended runtimes
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/runtime/converter_test.go
  components/kyma-environment-broker/internal/runtime/handler.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1789 Add replace dependency emicklei/restful with v3.8.0
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1791 Bump dependencies in kmc
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1799 Remove rafter component from main e2e test template
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/S, lgtm

#1803 Remove deprecated components from reconciler e2e test for kyma main
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/M, lgtm

#1796 enable feature flag for reconciler debug logging
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1784 Log provisioner kubeconfig parameters
  components/kyma-environment-broker/internal/process/deprovisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/get_kubeconfig_step.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1802 Feature - KEB endpoints exposed with Istio Authorization Policies
  resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
  resources/kcp/charts/kyma-environment-broker/templates/oathkeeper-rule.yaml
  resources/kcp/charts/kyma-environment-broker/templates/request-authentication.yaml
  resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1785 Removal of testcontainers-go Dependency
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/storage/driver/postsql/conflict_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/initialization_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/orchestration_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/postsql_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtimestate_test.go
  components/kyma-environment-broker/internal/storage/tests_utils.go
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1788 Remove SM PLatform credentials support
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/broker/instance_update_test.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/skip_for_trial_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/sm_overrides_test.go
  components/kyma-environment-broker/internal/process/update/conditions.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/sm_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/sm_overrides_test.go
  components/kyma-environment-broker/internal/servicemanager/automock/client.go
  components/kyma-environment-broker/internal/servicemanager/client.go
  components/kyma-environment-broker/internal/servicemanager/client_int_test.go
  components/kyma-environment-broker/internal/servicemanager/client_test.go
  components/kyma-environment-broker/internal/servicemanager/config.go
  components/kyma-environment-broker/internal/servicemanager/factory.go
  components/kyma-environment-broker/internal/servicemanager/factory_test.go
  components/kyma-environment-broker/internal/servicemanager/fake.go
  components/kyma-environment-broker/internal/servicemanager/metadata.go
  components/kyma-environment-broker/internal/servicemanager/types.go
  components/kyma-environment-broker/internal/storage/encrypt.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#1809 extract reconciler image values to different value file
  resources/kcp/values-reconciler-image.yaml
  resources/kcp/values.yaml
  tools/reconciler/Makefile
Labels: size/XS, lgtm

#1816 bring back mothership reconciler image in default value file
  resources/kcp/values-reconciler-image.yaml
  resources/kcp/values.yaml
  tools/reconciler/Makefile
Labels: size/XS, lgtm

#1820 enhancement: increase initialDelaySeconds for kubeconfig-service
  resources/oidc-kubeconfig-service/templates/deployment.yaml
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/S, lgtm
