Repository kyma-project/control-plane, pull requests merged in 2022-11, with the labels that each got.

#2225 Move Cleanup Jobs to Scratch
  components/kyma-environment-broker/Dockerfile.sac
  components/kyma-environment-broker/Dockerfile.tcj
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2233 Fix preview plan id
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2181 Create Kyma step
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/config/provider_test.go
  components/kyma-environment-broker/internal/config/testdata/keb-config.yaml
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2236 Update GCE Proxy image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2232 Add Assertion for newly created Step
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
Labels: size/S, lgtm

#2238 Bump dependencies for kmc
  components/kyma-metrics-collector/Dockerfile
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/L, lgtm

#2217 Delete Kyma resource step
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2216 KEB lifecycle manager kubeconfig sync
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager_kubeconfig.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager_kubeconfig_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2243 Implementation of in memory tracing events sink for tests
  components/kyma-environment-broker/internal/storage/storage.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2212 Added cloudsqlproxy.enabled configurability
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/templates/migrator-job.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm, ok-to-test

#2248 Disable LM integration for regular plans
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: area/documentation, size/S, lgtm

#2247 Reorder steps in deprovisioning
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2209 Change the administrator binding label to something more appropriate
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#2239 Tracing events helper on operation struct in KEB
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/staged_manager.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2250 Initialize kyma template
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
  components/kyma-environment-broker/internal/process/steps/kyma_template.go
  components/kyma-environment-broker/internal/process/steps/kyma_template_test.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2261 KEB RBAC to manage secrets for lifecycle manager
  resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
Labels: size/XS, lgtm

#2254 Hook legacy deprovisioning duration metric to staged manager
  components/kyma-environment-broker/internal/metrics/metrics.go
  components/kyma-environment-broker/internal/metrics/operation_duration.go
  components/kyma-environment-broker/internal/process/events.go
  components/kyma-environment-broker/internal/process/staged_manager.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2166 Enhance upgrade command to promt the user to continue
  tools/cli/pkg/command/orchestration.go
  tools/cli/pkg/command/upgrade.go
  tools/cli/pkg/command/upgrade_cluster.go
  tools/cli/pkg/command/upgrade_kyma.go
Labels: size/L, lgtm

#2260 fix CVE-2022-32149
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
Labels: size/S, lgtm

#2218 Move image definitions to subcharts
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/kyma-metrics-collector/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm

#2251 KEB config defaults for missing custom Kyma version configs
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/config/provider.go
  components/kyma-environment-broker/internal/config/provider_test.go
  components/kyma-environment-broker/internal/config/reader.go
  components/kyma-environment-broker/internal/config/reader_test.go
  components/kyma-environment-broker/internal/config/testdata/keb-config.yaml
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration_test.go
  docs/kyma-environment-broker/03-14-broker-configuration-for-given-version-and-plan.md
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: area/documentation, size/L, lgtm

#2265 Fix Apply kyma step - more logging
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
  resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2270 KEB should pass provisioning parameters for suspension operations
  components/kyma-environment-broker/internal/model.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2275 Remove pPrecel, m00g3n and moelsayed from the CODEOWNERS file
  CODEOWNERS
Labels: size/S, lgtm

#2276 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#2281 Update Reconciler images as necessary (Manual)
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2282 Adjust timeouts in deletion kyma
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2277 Assert the removal of service binding and instances during trial deprovisioning
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2283 Option for KCP to display at least partial information for deprovisioned instances
  components/kyma-environment-broker/common/runtime/client.go
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/events/interface.go
  components/kyma-environment-broker/internal/runtime/handler.go
  components/kyma-environment-broker/internal/storage/dbmodel/instance.go
  components/kyma-environment-broker/internal/storage/dbmodel/operation.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
  tools/cli/pkg/command/runtime.go
Labels: size/M, lgtm

#2257 Update Dockerfile for kubeconfig-service to use scratch image
  components/kubeconfig-service/Dockerfile
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/S, lgtm

#2285 Apply annotations for kyma CR
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager_kubeconfig.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2286 Change KCP runtime flag `--include-deleted` to `--only-deleted`
  components/kyma-environment-broker/common/runtime/client.go
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/runtime/handler.go
  components/kyma-environment-broker/internal/storage/dbmodel/instance.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
  tools/cli/pkg/command/runtime.go
Labels: size/M, lgtm

#2287 remove Maja from codeowners
  CODEOWNERS
  OWNERS_ALIASES
Labels: size/XS, lgtm

#2298 Fix Update for preview
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_step.go
  components/kyma-environment-broker/internal/process/update/conditions.go
  components/kyma-environment-broker/internal/process/update/init_kyma_step.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2288 KCP skip fetching events for too many instances
  tools/cli/pkg/command/runtime.go
Labels: size/S, lgtm

#2249 Change migrator script
  components/schema-migrator/go.mod
  components/schema-migrator/go.sum
  components/schema-migrator/main.go
  components/schema-migrator/main_test.go
  components/schema-migrator/mocks/FileSystem.go
  components/schema-migrator/mocks/MyFileInfo.go
Labels: size/XL, lgtm

#2296 Update KEB service plan documentation
  docs/kyma-environment-broker/03-01-service-description.md
Labels: area/documentation, size/XS, lgtm

#2196 Feature/upgrade in future maintenance window
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/orchestration_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/common/orchestration/client_test.go
  components/kyma-environment-broker/common/orchestration/dto.go
  components/kyma-environment-broker/common/orchestration/strategies/parallel.go
  components/kyma-environment-broker/common/orchestration/strategies/parallel_test.go
  components/kyma-environment-broker/internal/orchestration/handlers/cluster_handler.go
  components/kyma-environment-broker/internal/orchestration/handlers/cluster_handler_test.go
  components/kyma-environment-broker/internal/orchestration/handlers/handlers.go
  components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler.go
  components/kyma-environment-broker/internal/orchestration/handlers/kyma_handler_test.go
  components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler_test.go
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  tools/cli/pkg/command/taskrun.go
  tools/cli/pkg/command/upgrade.go
Labels: size/L, lgtm

#2307 Bump schema-migrator image
  resources/kcp/values.yaml
Labels: size/XS, lgtm
