Repository kyma-project/control-plane, pull requests merged in 2022-01, with the labels that each got.

#1245 Cleans up OWNERS and CODEOWNERS
  CODEOWNERS
  OWNERS
Labels: size/M, lgtm

#1247 Suspension process cleans the ClusterConfigVersion
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
  components/kyma-environment-broker/internal/reconciler/fake.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1248 Clean CLustertConfigurationVersion after the deletion is completed
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
  components/kyma-environment-broker/internal/reconciler/fake.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1249 Cluster deregistration must clean ClusterConfigurationVersion if done.
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1204 Add kcp orchestration retry command
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/common/orchestration/automock/strategy.go
  components/kyma-environment-broker/common/orchestration/client.go
  components/kyma-environment-broker/common/orchestration/client_test.go
  components/kyma-environment-broker/common/orchestration/dto.go
  components/kyma-environment-broker/common/orchestration/ext.go
  components/kyma-environment-broker/common/orchestration/strategies/parallel.go
  components/kyma-environment-broker/internal/metrics/operation_result.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/orchestration/handlers/cluster_retry.go
  components/kyma-environment-broker/internal/orchestration/handlers/handlers.go
  components/kyma-environment-broker/internal/orchestration/handlers/kyma_retry.go
  components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler.go
  components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler_test.go
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  resources/kcp/charts/kyma-environment-broker/templates/oathkeeper-rule.yaml
  resources/kcp/values.yaml
  tools/cli/go.sum
  tools/cli/pkg/command/orchestration.go
  tools/cli/pkg/command/orchestration_test.go
Labels: size/XXL, lgtm

#1250 Bump schema-migrator to v4.15.1
  components/schema-migrator/Dockerfile
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1201 Make KEB upgrade kyma queue aware of BTP Operator credentials
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/process/update/initialisation_step.go
  components/kyma-environment-broker/internal/process/update/sc_migration_check_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1253 Set maxSurge = 1 for least disruptive Gardener upgrades
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  components/kyma-environment-broker/internal/provider/openstack_provider.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1255 add flag to display subscription-global-account-id to kcp-cli
  tools/cli/pkg/command/runtime.go
Labels: size/S, lgtm

#1232 Do not use dirty Secret Bindings
  components/kyma-environment-broker/common/hyperscaler/account_pool.go
  components/kyma-environment-broker/common/hyperscaler/account_pool_test.go
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
  resources/kcp/values.yaml
Labels: bug, area/control-plane, size/M, lgtm

#1256 Fail update operation, if the instance is already deprovisioned
  components/kyma-environment-broker/internal/process/update/initialisation_step.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1258 Move check cluster configuration to the begining
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/check_cluster_configuration.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1221 Removing e2e TestDefinitions
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-aws.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-azure.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-free-aws.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-gcp.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-ha-aws.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-skr.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-provisioning-suspension.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/e2e-upgrade-azure.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/rbac.yaml
  resources/kcp/charts/kyma-environment-broker/templates/tests/upg-tst-aws-prov.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XXL, lgtm

#1263 Disable SVCAT related components for migration
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/process/update/sc_migration.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1265 Change kyma upgrade from main to 2.0.2 in `periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade`
  tools/reconciler/e2e-test/template.json
Labels: size/XS, lgtm

#1251 Add the `state` command
  components/reconciler/makefile
  components/reconciler/pkg/automock/client.go
  components/reconciler/pkg/client_gen.go
  components/reconciler/pkg/types_gen.go
  tools/cli/pkg/command/operation_stop.go
  tools/cli/pkg/command/reconciliations.go
  tools/cli/pkg/command/reconciliations_disable.go
  tools/cli/pkg/command/reconciliations_enable.go
  tools/cli/pkg/command/reconciliations_state.go
  tools/cli/pkg/command/reconciliations_state_test.go
  tools/cli/pkg/command/reconciliations_test.go
Labels: size/XL, lgtm

#1267 Fix Kyma version placement in RuntimeStateDTO
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtimestate_test.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1269 KEB: Use configurable reconciler timeout in upgrade Check_Cluster_Configuration step
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1272 Add grego952 as a documentaion CODEOWNER in KCP
  CODEOWNERS
Labels: area/documentation, area/community, size/XS, lgtm

#1276 Bump golang builder image to 1.17.6
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/Dockerfile.sac
  components/schema-migrator/Dockerfile
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1279 Update containerd dependency to v1.5.9
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1260 KEB Console Removal
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/common/director/client.go
  components/kyma-environment-broker/common/director/client_test.go
  components/kyma-environment-broker/common/director/fake.go
  components/kyma-environment-broker/common/director/query.go
  components/kyma-environment-broker/internal/broker/response_labels_test.go
  components/kyma-environment-broker/internal/ias/bundle.go
  components/kyma-environment-broker/internal/process/provisioning/automock/director_client.go
  components/kyma-environment-broker/internal/process/provisioning/initialisation.go
Labels: size/L, lgtm

#1282 Upgrade reconciler after merging pr 701
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1275 Corrected Redirection to Busola
  tests/e2e/provisioning/pkg/client/runtime/dashboard_checker.go
  tests/e2e/provisioning/test/e2e_provisioning_test.go
  tests/e2e/provisioning/test/e2e_suspension_test.go
  tests/e2e/provisioning/test/test_suite.go
Labels: size/M, lgtm

#1280 add nodeSelector in the deployment.yaml of mothership/component-reconciler
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
Labels: size/S, lgtm

#1268 Bump Golang Runtime in Provisioner and SCJ
  components/provisioner/Dockerfile
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/subscription-cleanup-job/Dockerfile
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
  resources/kcp/values.yaml
Labels: area/control-plane, size/L, lgtm

#1288 Upgrade reconciler
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1292 Fix KEB timouet on deprovisioning
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1289 Fix of the db persistence layer for saving cluster configuration during shoot upragde
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
Labels: bug, area/control-plane, size/L, lgtm

#1283 Configurability of reconciler replicas, worker-count and verbose
  resources/kcp/charts/component-reconcilers/charts/rma-component-reconciler/templates/deployment.yaml
  resources/kcp/charts/component-reconcilers/charts/rma-component-reconciler/values.yaml
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/service-monitor.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1287 Explicitly disable BTP Operator for upgrade queue
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/internal/component_input_helpers.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/sm_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/sm_overrides_test.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1297 Use installHint in generated kubeconfig
  components/kubeconfig-service/pkg/transformer/kubeconfig.go
  components/kubeconfig-service/pkg/transformer/transformer_test.go
  components/kyma-environment-broker/internal/kubeconfig/builder_test.go
  components/kyma-environment-broker/internal/kubeconfig/kubeconfig.go
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/M, lgtm

#1285 interval updated
  components/kyma-environment-broker/internal/avs/model.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1293 add pdb for component-reconcilers and mothership-reconciler
  resources/kcp/charts/component-reconcilers/templates/pdb.yaml
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/templates/pdb.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/M, lgtm

#1277 Prevent SC migration if BTP operator exists
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/update/btp_operator_check.go
  components/kyma-environment-broker/internal/process/update/btp_operator_check_test.go
  components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1303 Fix the `pre-main-control-plane-reconciler-e2e` pipeline
  tools/reconciler/e2e-test/template.json
Labels: size/S, lgtm

#1300 Update reconciler images
  resources/kcp/values.yaml
Labels: area/eventing, size/XS, lgtm

#1304 Bump reconciler version
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1291 Fix the nil pointer crash in KEB orchestration manager waitForCompletion
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1309 Add "cleaner" component reconciler
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1308 Fix resetting autoscaler params in cluster upgrade operation
  components/kyma-environment-broker/internal/process/upgrade_cluster/initialisation.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1315 Some more debug info
  tools/reconciler/e2e-test/request-reconcile.sh
Labels: size/XS, lgtm

#1281 Reconciler Timeout Note
  docs/kyma-environment-broker/03-03-runtime-operations.md
Labels: size/XS, lgtm
