Repository kyma-project/control-plane, pull requests merged in 2022-09, with the labels that each got.

#2011 Documentation for trial cleaner job
  docs/kyma-environment-broker/03-15-trial-cleanup-cronjob.md
Labels: area/documentation, size/M, lgtm

#2013 removing oidc-kubeconfig-service as it will be managed by argo-cd
  installation/resources/installer-cr.yaml.tpl
Labels: size/XS, lgtm

#2009 add userID when sending upgrade nofication msg
  components/kubeconfig-service/pkg/authn/middleware.go
  resources/oidc-kubeconfig-service/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/send_slack_notification.go
  tools/cli/pkg/command/upgrade_cluster.go
  tools/cli/pkg/command/upgrade_kyma.go
  tools/cli/pkg/credential/manager.go
Labels: size/L, lgtm

#2021 Add Jaroslaw Pieszka to codeowners
  CODEOWNERS
Labels: size/S, lgtm

#2015 Improve trial expiry labels
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/instance_get.go
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  components/kyma-environment-broker/internal/broker/response_labels.go
  components/kyma-environment-broker/internal/broker/response_labels_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2028 Display machine type details in KEB catalog
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema.json
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2025 Deprovisioning init step
  components/kyma-environment-broker/internal/process/deprovisioning/init.go
  components/kyma-environment-broker/internal/process/deprovisioning/init_test.go
Labels: size/L, lgtm

#2027 Release hyperscaler subscription step
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step_test.go
Labels: size/L, lgtm

#2036 Bump GOLANG to 1.19 for KMC
  components/kyma-metrics-collector/Dockerfile
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#2038 Restoring missing metrics
  components/kyma-environment-broker/internal/metrics/operation_result.go
  components/kyma-environment-broker/internal/metrics/step_result.go
  components/kyma-environment-broker/internal/process/staged_manager.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2039 Register compass_keb_provisioning_result metrics to generic operations manager
  components/kyma-environment-broker/internal/metrics/metrics.go
  components/kyma-environment-broker/internal/metrics/operation_result.go
Labels: size/S, lgtm

#2031 Remove busola-migrator from control-plane
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/instance_update_test.go
  components/kyma-environment-broker/internal/dashboard/config.go
  components/kyma-environment-broker/internal/process/provisioning/busola_migrator_overrides.go
  components/kyma-environment-broker/internal/process/provisioning/busola_migrator_overrides_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/busola_migrator_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/busola_migrator_overrides_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
  tests/e2e/provisioning/pkg/client/runtime/dashboard_checker.go
Labels: size/L, lgtm

#2041 correct comparison introduced
  components/kyma-environment-broker/internal/metrics/operation_duration.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2035 Configure btp-operator priorityClass
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/component_input_helpers.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2042 Provisioner - change client_golang to 1.11.1 due to CVE in 1.11.0
  components/provisioner/Dockerfile
  components/provisioner/go.mod
  components/provisioner/go.sum
Labels: size/XS, lgtm

#2029 Remove obsolete codeowner - life0215
  CODEOWNERS
Labels: size/XS, lgtm

#2033 Remove instance permanently step
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step_test.go
Labels: size/L, lgtm

#2032 Check removal runtime step
  components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step_test.go
Labels: size/L, lgtm

#2044 Enhance KEB compass_keb_operation_result with error_category and error_reason
  components/kyma-environment-broker/internal/metrics/operations_db_collector.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2050 Update Provisioner to most recent image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2043 Configurability of reconcile interval
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2054 Fix plans schema
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-trial-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/free-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/free-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/openstack-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-trial-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema-additional-params.json
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2053 Build ERS cli by tools Makefile
  tools/cli/.gitignore
  tools/cli/Makefile
Labels: size/S, lgtm

#2058 Run go fmt with 1.19 fixes
  tools/cli/pkg/credential/manager.go
  tools/cli/pkg/ers/command/migrate_all.go
  tools/cli/pkg/printer/custom.go
Labels: size/S, lgtm

#2055 Bump lib versions in KMC component
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#2063 remove all traces of auditlog
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/auditlog/config.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#2065 Non-repetitive definition of build targets for CLI tools
  tools/cli/Makefile
Labels: size/XS, lgtm

#2064 Logging improved for trial cleanup job
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2061 Update CODEOWNERS
  CODEOWNERS
Labels: size/XS, lgtm

#2068 bumping go & k8s version for kubeconfig-service
  components/kubeconfig-service/Dockerfile
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  resources/oidc-kubeconfig-service/values.yaml
  tools/cli/go.mod
Labels: size/L, lgtm

#2046 Install Kyma on your own cluster amended
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/last_operation_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_cluster_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/common/gardener/shoot_name.go
  components/kyma-environment-broker/common/hyperscaler/azure/testing/testing.go
  components/kyma-environment-broker/common/orchestration/ext.go
  components/kyma-environment-broker/common/orchestration/resolver.go
  components/kyma-environment-broker/internal/broker/bind_create.go
  components/kyma-environment-broker/internal/broker/bind_delete.go
  components/kyma-environment-broker/internal/broker/bind_get.go
  components/kyma-environment-broker/internal/broker/bind_last_operation.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_deprovision.go
  components/kyma-environment-broker/internal/broker/instance_last_operation.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/logging.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/services.go
  components/kyma-environment-broker/internal/broker/testdata/own-cluster-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/own-cluster-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-own-cluster-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-own-cluster-schema.json
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/httputil/response.go
  components/kyma-environment-broker/internal/metrics/instances_collector.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/create_cluster_configuration.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_for_own_cluster_step.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_for_own_cluster_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_step.go
  components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/queue.go
  components/kyma-environment-broker/internal/provider/owncluster_provider.go
  components/kyma-environment-broker/internal/provisioner/query.go
  components/kyma-environment-broker/internal/reconciler/client.go
  components/kyma-environment-broker/internal/reconciler/client_int_test.go
  components/kyma-environment-broker/internal/reconciler/fake.go
  components/kyma-environment-broker/internal/runtime/components/components.go
  components/kyma-environment-broker/internal/runtime/components_provider.go
  components/kyma-environment-broker/internal/runtime/disabled_components.go
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/storage/driver/postsql/ext.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/storage/encrypt.go
  components/kyma-environment-broker/internal/third_party/machinebox/graphql/graphql.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XXL, lgtm

#2069 Aggregate error from operation manager when marking operation as failed
  components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step_test.go
  components/kyma-environment-broker/internal/process/operation_manager.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2049 Use common staged manager
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/appinfo/runtime_info_test.go
  components/kyma-environment-broker/internal/avs/delegator.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/kubeconfig/handler_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations.go
  components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup.go
  components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/ias_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/ias_deregistration_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/init.go
  components/kyma-environment-broker/internal/process/deprovisioning/init_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation.go
  components/kyma-environment-broker/internal/process/deprovisioning/initialisation_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/utils.go
  components/kyma-environment-broker/internal/process/operation_manager.go
  components/kyma-environment-broker/internal/process/update/initialisation_step.go
  components/kyma-environment-broker/internal/runtime/handler_test.go
  components/kyma-environment-broker/internal/storage/dberr/errors_test.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  components/kyma-environment-broker/internal/suspension/handler_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XL, lgtm

#2072 Revert KEB operation manager to legacy error wrapping
  components/kyma-environment-broker/internal/process/operation_manager.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2074 REvert reconciler to valid image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2075 Fix Remove runtime step
  components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2077 Fix check removal step
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2070 Bring you own cluster - kubeconfig in base64 in request body
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2081 Do not provide kubeconfig for owncluster
  components/kyma-environment-broker/internal/kubeconfig/handler.go
  components/kyma-environment-broker/internal/kubeconfig/handler_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2082 DAshboard url for own cluster
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/response_labels.go
  components/kyma-environment-broker/internal/broker/response_labels_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2078 Support Shoot HA in provisioner
  components/provisioner/Makefile
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/hack/gqlgen.go
  components/provisioner/internal/api/fake/shoots/gardener_client.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/testdata/crd/seed.crd.yaml
  components/provisioner/internal/api/testdata/crd/shoot.crd.yaml
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/installation/release/gcs_downloader.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_agent_to_connect.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain.go
  components/provisioner/internal/persistence/dberrors/types.go
  components/provisioner/internal/provider-config-migrator/migrator.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/util/retry_test.go
  components/provisioner/internal/util/testkit/worker.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/provisioner/third_party/machinebox/graphql/graphql.go
  components/schema-migrator/migrations/provisioner/202209191503_control_plane_ha.down.sql
  components/schema-migrator/migrations/provisioner/202209191503_control_plane_ha.up.sql
  resources/kcp/values.yaml
  tools/cli/go.sum
Labels: priority/high, size/XXL, lgtm

#2089 Make Avs more verbose, fix remove-runtime
  components/kyma-environment-broker/internal/avs/client.go
  components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_runtime.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2088 Support Shoot control plane HA in KEB
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/aws_provider_test.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider_test.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  components/kyma-environment-broker/internal/provider/gcp_provider_test.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/L, lgtm

#2066 fix the failed data occasionally not list in `kcp o id operaitons -s failed`
  components/kyma-environment-broker/common/orchestration/client.go
  components/kyma-environment-broker/common/orchestration/client_test.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  tools/cli/go.sum
Labels: size/L, lgtm

#2090 Owncluster Rename
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/provider/own_cluster_provider.go
Labels: size/S, lgtm

#2091 Fix remove instance step
  components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2093 Skip Runtime removal check if there is no provisioner operation
  components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_runtime_removal_step_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm
