Repository kyma-project/control-plane, pull requests merged in 2022-02, with the labels that each got.

#1312 Improvement of checking Kyma version before starting cluster deprovision
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  resources/kcp/values.yaml
Labels: bug, area/control-plane, size/L, lgtm

#1319 Add new scope to registration job
  resources/kcp/templates/registration-job.yaml
Labels: size/XS, lgtm

#1320 Adjust query function to get latest Runtimestate with Kyma version
  components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtimestate_test.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1310 Upgrade process uses correct gardener params
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1323 Prepare two templates for different kyma version
  tools/reconciler/e2e-test/template-kyma-2-0-x.json
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/L, lgtm

#1328 Deprovision fix - selecting correct operation to be created
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/provisioning/mocks/Provisioner.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1331 KCP CLI: fix go mod tidy failing in CI
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/S, lgtm

#1313 Uniform component reconciler chart naming
  resources/kcp/charts/component-reconcilers/charts/rma/Chart.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/templates/authorization.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/templates/deployment.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/templates/rbac.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/templates/service.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/values.yaml
  resources/kcp/charts/component-reconcilers/templates/authorization.yaml
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/charts/component-reconcilers/templates/rbac.yaml
  resources/kcp/charts/component-reconcilers/templates/service.yaml
  resources/kcp/charts/mothership-reconciler/templates/authorization.yaml
  resources/kcp/charts/mothership-reconciler/templates/policy.yaml
Labels: size/S, lgtm

#1322 Add new code owners
  CODEOWNERS
Labels: size/S, lgtm

#1324 Log incoming requests in KEB
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/logging.go
  components/kyma-environment-broker/internal/broker/logging_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1326 Hide authorization headers in logs
  components/provisioner/third_party/machinebox/graphql/graphql.go
  components/provisioner/third_party/machinebox/graphql/graphql_json_test.go
  components/provisioner/third_party/machinebox/graphql/graphql_multipart_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1317 deploy-cloudsql-proxy-in-a-separate-mothershipreconciler-subchart
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/.helmignore
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/Chart.yaml
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/templates/_helpers.tpl
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/templates/authorization.yaml
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/templates/service.yaml
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/templates/serviceaacount.yaml
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/values.yaml
  resources/kcp/charts/mothership-reconciler/files/reconciler.yaml
  resources/kcp/charts/mothership-reconciler/templates/authorization.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
Labels: size/L, lgtm

#1334 Allow to deprovision Kyma runtime without kubeconfig in the database
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  resources/kcp/values.yaml
Labels: bug, area/control-plane, size/L, lgtm

#1278 Add structured logging for KMC
  components/kyma-metrics-collector/cmd/main.go
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/options/options.go
  components/kyma-metrics-collector/pkg/edp/client.go
  components/kyma-metrics-collector/pkg/edp/client_test.go
  components/kyma-metrics-collector/pkg/keb/client.go
  components/kyma-metrics-collector/pkg/keb/client_test.go
  components/kyma-metrics-collector/pkg/logger/logger.go
  components/kyma-metrics-collector/pkg/process/process.go
  components/kyma-metrics-collector/pkg/process/process_test.go
  components/kyma-metrics-collector/pkg/service/server.go
Labels: size/L, lgtm

#1337 Introduce separate stage for update sc-migration finalization process
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1338 fixed mothership reconciler pgHost value
  resources/kcp/charts/mothership-reconciler/files/reconciler.yaml
Labels: size/XS, lgtm

#1305 Control Order
  components/kyma-environment-broker/internal/appinfo/runtime_info.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/plans_test.go
  components/kyma-environment-broker/internal/broker/services.go
  components/kyma-environment-broker/internal/broker/services_test.go
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/aws-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-trial-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-trial-schema.json
  components/kyma-environment-broker/internal/broker/testdata/free-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/free-aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/free-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/free-azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema.json
  components/kyma-environment-broker/internal/broker/testdata/openstack-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/openstack-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-ha-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-ha-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-ha-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-trial-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-trial-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema.json
  components/kyma-environment-broker/internal/broker/utils.go
Labels: size/XXL, lgtm

#1335 Keb add kyma version
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step.go
  components/kyma-environment-broker/internal/runtimeversion/runtimeversion.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtime_state.go
  components/kyma-environment-broker/internal/storage/driver/postsql/runtimestate_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1339 Install openssl from edge
  components/kyma-environment-broker/Dockerfile.sac
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1340 Bump CloudSQL proxy image to 1.28.1
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1342 Revert to sidecar cloudsql-proxy
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/.helmignore
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/Chart.yaml
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/templates/_helpers.tpl
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/templates/authorization.yaml
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/templates/service.yaml
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/templates/serviceaacount.yaml
  resources/kcp/charts/mothership-reconciler/charts/cloudsql-proxy/values.yaml
  resources/kcp/charts/mothership-reconciler/files/reconciler.yaml
  resources/kcp/charts/mothership-reconciler/templates/authorization.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
Labels: size/L, lgtm

#1343 Bump schema-migrator base image to 3.15.0
  components/schema-migrator/Dockerfile
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1347 mothersip-reconciler: configurable liveness/readiness probes
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/S, lgtm

#1351 Fix shoot filter response
  tools/cli/pkg/command/reconciliations.go
  tools/cli/pkg/command/reconciliations_test.go
Labels: size/S, lgtm

#1352 Deprovisioning operations should be created as Pending
  components/kyma-environment-broker/internal/broker/instance_deprovision_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1348 Install OpenSSL lib from edge in various KEB components
  components/kyma-environment-broker/Dockerfile.sac
  components/schema-migrator/Dockerfile
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1345 Fix dockerfile linting - 1
  components/kubeconfig-service/Dockerfile
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XS, lgtm

#1353 Update CODEOWNERS (gophers)
  CODEOWNERS
Labels: size/S, lgtm

#1354 Bump reconciler: reconcile/delete race condition
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1361 Upgrade Kyma Environemnt Broker dependency in subscription cleanup job
  components/subscription-cleanup-job/Makefile
  components/subscription-cleanup-job/go.mod
  components/subscription-cleanup-job/go.sum
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1360 Bump docker in provisioner
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1359 Add a startupProbe
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#1368 Bump third party images containing latest OpenSSL release
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1306 Bump compass director
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/gqlgen.sh
  components/provisioner/internal/apperrors/presenter.go
  components/provisioner/internal/director/directorclient.go
  components/provisioner/internal/director/directorclient_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema_gen.go
  resources/kcp/values.yaml
Labels: size/XXL, lgtm

#1370 Fix setting/restoring AVS maintenance during Kyma 2 upgrade
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/avs_maintenance.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/check_cluster_configuration.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1373 enable dependabot for kmc
  .github/dependabot-config.yaml
  .github/dependabot.tmpl
  .github/dependabot.yml
Labels: area/security, area/ci, size/L, lgtm

#1380 Bump prometheus 1.12.0, go 1.17.7 and alpine versions 3.15.0
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/Dockerfile.sac
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1381 Bump Reconciler Image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1371 Update stale.yml
  .github/stale.yml
Labels: size/XS, lgtm

#1384 upgrade to latest reconciler version
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1372 Bump dependencies and fix tests on KMC
  components/kyma-metrics-collector/Dockerfile
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/pkg/skr/node/client_test.go
  components/kyma-metrics-collector/pkg/skr/node/fake.go
  components/kyma-metrics-collector/pkg/skr/pvc/client_test.go
  components/kyma-metrics-collector/pkg/skr/pvc/fake.go
  components/kyma-metrics-collector/pkg/skr/svc/client_test.go
  components/kyma-metrics-collector/pkg/skr/svc/fake.go
  components/kyma-metrics-collector/pkg/testing/helpers.go
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1388 Fix handling AVS evaluation statuses during Kyma 2 upgrade
  components/kyma-environment-broker/internal/process/upgrade_kyma/check_cluster_configuration.go
  resources/kcp/values.yaml
Labels: priority/critical, size/M, lgtm

#1386 Bump prometheus client_golang
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1391 Updated codeowners for KMC
  CODEOWNERS
Labels: size/XS, lgtm

#1387 Enable service-mesh for KMC
  resources/kcp/charts/kyma-metrics-collector/templates/policy.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/service.yaml
  resources/kcp/charts/kyma-metrics-collector/values.yaml
Labels: size/S, lgtm

#1398 Send empty administrator list if user_id was not set
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration.go
  resources/kcp/values.yaml
Labels: size/S, lgtm

#1399 Add OIDC input validation
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/instance_update_test.go
  components/kyma-environment-broker/internal/dto.go
  resources/kcp/values.yaml
Labels: size/M, lgtm
