Repository kyma-project/control-plane, pull requests merged in 2022-07, with the labels that each got.

#1827 Allow authenticated access to KEB /runtimes to specified principals
  resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: priority/high, size/S, lgtm

#1815 provisioner: add support for Azure multi AZ, having dedicated subnet per zone
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/model/infrastructure.go
  components/provisioner/internal/model/infrastructure/azure/infrastructure.go
  components/provisioner/internal/provider-config-migrator/migrator_db_integration_test.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  resources/kcp/values.yaml
Labels: size/XL, lgtm

#1829 Introducing body template for Kyma2.4.x
  tools/reconciler/e2e-test/template-kyma-2-4-x.json
Labels: size/L, lgtm

#1807 Prow Triggering Change
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: area/documentation, size/S, lgtm

#1834 Fix pre-main-control-plane-reconciler-e2e-latest-release
  tools/reconciler/e2e-test/template-kyma-2-4-x.json
Labels: size/S, lgtm

#1837 provisioner: fix azureZones input to be optional
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  resources/kcp/values.yaml
Labels: size/M, lgtm

#1691 Create deprovision package
  components/kyma-environment-broker/common/deprovision/client.go
  components/kyma-environment-broker/common/deprovision/model.go
Labels: size/M, lgtm

#1844 Updated Cloudsql Version
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1846 Enable logging region which comes to KEB as param
  components/kyma-environment-broker/internal/broker/instance_create.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#1848 Old Image Revert
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1850 Update value of kyma_environments_subaccount_cleanup_job
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1851 Change golang version
  components/schema-migrator/Dockerfile
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1831 Introduce license_type aggregated metric
  components/kyma-environment-broker/internal/metrics/instances_collector.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/storage/dbmodel/operation.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#1856 Update value of kyma_environments_cleanup_job
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1857 Move getkubeconfig step before btp overrides step in the upgrade kyma…
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#1854 Elimination of Bash from Schema Migrator
  components/schema-migrator/Dockerfile
  components/schema-migrator/Makefile
  components/schema-migrator/doc.go
  components/schema-migrator/go.mod
  components/schema-migrator/go.sum
  components/schema-migrator/main.go
  components/schema-migrator/run.sh
Labels: size/XXL, lgtm

#1853 KEB: EnableNatGateway
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider_test.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#1830 Fix: reconciliation and operation debug logging bug
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/operation_debug_logs.go
  tools/cli/pkg/command/reconciliation_debug_logs.go
Labels: size/XXL, lgtm

#1869 keb: adjust name in graphQL payload
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1864 Stop reporting error metrics from KMC if secrets or shoots are not found
  components/kyma-metrics-collector/README.md
  components/kyma-metrics-collector/dev/deployment.yaml
  components/kyma-metrics-collector/pkg/gardener/secret/client.go
  components/kyma-metrics-collector/pkg/gardener/secret/client_test.go
  components/kyma-metrics-collector/pkg/gardener/shoot/client.go
  components/kyma-metrics-collector/pkg/gardener/shoot/client_test.go
  components/kyma-metrics-collector/pkg/logger/logger.go
  components/kyma-metrics-collector/pkg/process/process.go
  resources/kcp/values.yaml
Labels: area/documentation, area/control-plane, size/L, lgtm

#1874 Bump dependencies kmc 2022 jul 18
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/L, lgtm

#1872 Operations Methods for Refactoring
  components/kyma-environment-broker/internal/storage/automock/operations.go
  components/kyma-environment-broker/internal/storage/driver/memory/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/storage/ext.go
  components/kyma-environment-broker/internal/storage/postsql/factory.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
Labels: size/L, lgtm

#1884 Revert "Update Reconciler images as necessary"
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1882 Change Alpine version in Provisioner - OpenSSL security vulnerability fix
  components/provisioner/Dockerfile
  resources/kcp/values.yaml
Labels: area/security, size/XS, lgtm

#1887 Test Change
  components/kyma-environment-broker/cmd/broker/main.go
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/M, lgtm

#1888 Corrected Hidden Error & Invalid Rm Command
  components/kyma-environment-broker/internal/storage/tests_utils.go
Labels: size/XS, lgtm

#1870 All necessary fields moved from XXXOperation to Operation type
  components/kyma-environment-broker/internal/appinfo/runtime_info_test.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/orchestration/handlers/orchestration_handler_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/process/provisioning/internal_eval_updater_test.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides_test.go
  components/kyma-environment-broker/internal/process/update/check_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/manager_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/secret_cm_overrides_test.go
  components/kyma-environment-broker/internal/runtime/converter_test.go
  components/kyma-environment-broker/internal/runtime/handler_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/suspension/handler_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#1859 KEB configuration for given Kyma version and plan
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/internal/config/converter.go
  components/kyma-environment-broker/internal/config/provider.go
  components/kyma-environment-broker/internal/config/provider_test.go
  components/kyma-environment-broker/internal/config/reader.go
  components/kyma-environment-broker/internal/config/reader_test.go
  components/kyma-environment-broker/internal/config/testdata/keb-config.yaml
  components/kyma-environment-broker/internal/config/validator.go
  components/kyma-environment-broker/internal/config/validator_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/input/automock/component_list_provider.go
  components/kyma-environment-broker/internal/process/input/builder.go
  components/kyma-environment-broker/internal/process/input/builder_test.go
  components/kyma-environment-broker/internal/process/input/input_test.go
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration_test.go
  components/kyma-environment-broker/internal/process/update/manager.go
  components/kyma-environment-broker/internal/runtime/components_provider.go
  components/kyma-environment-broker/internal/runtime/components_provider_test.go
  components/kyma-environment-broker/internal/runtime/provider.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
Labels: size/XL, lgtm

#1868 Change environments-cleanup-job from alpine to scratch
  components/kyma-environment-broker/Dockerfile.cleanup
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1890 Always explicitly enable or disable network filter in KEB
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/update_test.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/upgrade_cluster_step_test.go
  components/kyma-environment-broker/internal/provisioner/client_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#1891 Remove support for Kyma < 2.1 with old istio-configuration component
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#1878 Generic storage helper
  components/kyma-environment-broker/internal/process/operation_manager.go
  components/kyma-environment-broker/internal/process/operation_manager_test.go
Labels: size/L, lgtm

#1897 temporarily removed n2-standard-48
  components/kyma-environment-broker/internal/broker/plans.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#1898 Unit tests for new storage methods
  components/kyma-environment-broker/internal/storage/driver/postsql/conflict_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm
