Repository kyma-project/control-plane, pull requests merged in 2023-10, with the labels that each got.

#3099 Bump KEB images to v20231003-7756a730
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#3100 workload identity disables cloudsql credential
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/runtime-reconciler-deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/templates/managed-postgresql-secret.yaml
  resources/kcp/templates/migrator-job.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#3101 Add option for additional gateways
  resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
  resources/kcp/charts/mothership-reconciler/templates/virtualservice.yaml
  resources/kcp/charts/provisioner/templates/virtual-service.yaml
  resources/oidc-kubeconfig-service/templates/virutalservice.yaml
Labels: size/M, lgtm

#3102 Fix typo in kubeconfig virtualservice
  resources/oidc-kubeconfig-service/templates/virutalservice.yaml
Labels: size/XS, lgtm

#3116 Make all kcp servicemonitors conditional
  resources/kcp/charts/kyma-environment-broker/templates/service-monitor.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/service-monitor.yaml
  resources/kcp/charts/kyma-metrics-collector/values.yaml
  resources/kcp/charts/mothership-reconciler/templates/service-monitor.yaml
  resources/kcp/charts/provisioner/templates/service-monitor.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/S, lgtm

#3112 extend AvS integration with KEB
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#3103 Remove monitoring component from reconciler e2e test
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: area/monitoring, size/S, lgtm, kind/cleanup

#3119 Bump images
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#3118 Disabled Pruning for KEB Resources Migration
  resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml
  resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
  resources/kcp/charts/kyma-environment-broker/templates/dashboard.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/gardener-dashboard.yaml
  resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/keb-migrations.yaml
  resources/kcp/charts/kyma-environment-broker/templates/policy.yaml
  resources/kcp/charts/kyma-environment-broker/templates/profiler-pvc.yaml
  resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
  resources/kcp/charts/kyma-environment-broker/templates/request-authentication.yaml
  resources/kcp/charts/kyma-environment-broker/templates/runtime-reconciler-deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml
  resources/kcp/charts/kyma-environment-broker/templates/service-monitor.yaml
  resources/kcp/charts/kyma-environment-broker/templates/service.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
Labels: size/M, lgtm

#3120 Fix typo error
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
Labels: size/S, lgtm

#3121 Typo Correction
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
Labels: size/XS, lgtm

#3113 Bump Go in provisioner
  components/provisioner/Dockerfile
  components/provisioner/go.mod
  components/provisioner/go.sum
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/M, lgtm

#3117 update jellyfish codeowner
  CODEOWNERS
Labels: size/S, lgtm

#3123 Fix typo in subaccount cleanup job image tag
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#3124 Bump provisioner image after #3113
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#3128 KEB: don't provide GardenerShootName AvS tag
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#3130 Bump KEB images to v20231019-e8cdf9dc
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#3131 Moving Dashboard to New Repository
  resources/kcp/charts/kyma-environment-broker/files/dashboard.json
  resources/kcp/charts/kyma-environment-broker/templates/dashboard.yaml
Labels: size/XXL, lgtm

#3136 Skip Eventing
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: area/eventing, size/XS, lgtm, area/reconciler

#3138 Bump KEB images to v20231023-ebbc2f78
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#3137 Adding applicationconnector to the list of CRDs detected by the mothtership reconciller
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#3091 Remove rma resources
  resources/kcp/charts/component-reconcilers/charts/rma/Chart.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/templates/deployment.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/templates/rbac.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/templates/service.yaml
  resources/kcp/charts/component-reconcilers/charts/rma/values.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#3141 Bump KEB images to v20231026-da3a18d9
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#3145 Revert "gomod(deps): bump go.uber.org/zap from 1.24.0 to 1.26.0 in /components/kyma-metrics-collector"
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
Labels: size/S, lgtm

#3115 Add FF env for mandatory region
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm
