Repository kyma-project/control-plane, pull requests merged in 2023-03, with the labels that each got.

#2540 Assignment Correction
  components/kyma-environment-broker/common/setup/builder.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2544 Fix 'kcp rt status -c shoot' returning random runtime status
  tools/cli/pkg/command/reconciliations_state.go
Labels: size/XS, lgtm

#2546 Handle own cluster subscription release
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2553 Change image reference for trial cleanup job
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2555 Fix Kyma deprovisioning test
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2554 Commands corrected in deployments
  components/kyma-environment-broker/cmd/trialcleanup/main.go
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#2559 Update gce proxy image version to v1.33.4
  resources/kcp/charts/component-reconcilers/values.yaml
Labels: size/XS, lgtm

#2570 Add unit tests for redeprovisioning
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2572 Subaccount cleanup job securityfix
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2563 KEB /runtime endpoint deprovision incomplete filter
  components/kyma-environment-broker/common/runtime/client.go
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/runtime/handler.go
  components/kyma-environment-broker/internal/storage/dbmodel/instance.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2564 KCP list runtime deprovision incomplete
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/runtime.go
Labels: size/L, lgtm

#2577 Fix flaky redeprovision tests
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/internal/provisioner/fake_client.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2583 Missing Cloudsql Proxy Version
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2580 Added vmprobes to rma reconciler clusterrole
  resources/kcp/charts/component-reconcilers/charts/rma/templates/rbac.yaml
Labels: size/XS, lgtm

#2590 Dependabot merge script simplification
  scripts/dependabot_helper.bash
Labels: size/M, lgtm

#2591 Document usage of 'kcp rt --state=deprovisioned,deprovisionIncomplete'
  tools/cli/pkg/command/runtime.go
Labels: size/XS, lgtm

#2581 Send event if reconciler creates cluster too long
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2594 Update documentation of 'kcp rt --state'
  tools/cli/pkg/command/runtime.go
Labels: size/XS, lgtm

#2579 Add `-` in DB name support to KCP database
  resources/kcp/charts/postgresql/templates/init-db-config-map.yaml
Labels: size/XS, lgtm, area/charts

#2601 Bump reconciler to include Istio duplicated webhook cleanup
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2603 secure KEB endpoints with IAS
  resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
Labels: size/XS, lgtm

#2604 Update gophers owners and codeowners
  CODEOWNERS
  OWNERS
  resources/kcp/OWNERS
Labels: size/S, lgtm

#2599 Convert subaccountID to lowercase in EDP steps
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration.go
  components/kyma-environment-broker/internal/process/provisioning/edp_registration.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2476 More Generic Job YAML Definition
  components/kyma-environment-broker/Dockerfile.job
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#2459 Continuation of Cleanup Despite Errors & Adding Removal of Unused Gardener Shoots
  components/kyma-environment-broker/internal/environmentscleanup/automock/GardenerClient.go
  components/kyma-environment-broker/internal/environmentscleanup/service.go
  components/kyma-environment-broker/internal/environmentscleanup/service_test.go
Labels: size/L, lgtm

#2589 Missing CloudSql Proxy Param for Provisioner and Migrator
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2606 Gardener version bumped to v1.65.2
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/gardener/provisioner.go
  resources/kcp/charts/provisioner/values.yaml
  tools/cli/go.sum
Labels: size/L, lgtm

#2618 Cleanup Service Corrections
  components/kyma-environment-broker/common/setup/builder.go
  components/kyma-environment-broker/internal/environmentscleanup/automock/GardenerClient.go
  components/kyma-environment-broker/internal/environmentscleanup/service.go
  components/kyma-environment-broker/internal/environmentscleanup/service_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2616 Introduced Bool Type for Incorrect DB Values
  components/kyma-environment-broker/common/orchestration/dto.go
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  components/kyma-environment-broker/internal/storage/dbmodel/orchestration_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2630 bump the reconciler image
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/S, lgtm

#2622 Avs evaluations deprovision cleanup
  components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations.go
  components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2632 Undo the changes done to service monitor.
  resources/kcp/charts/component-reconcilers/values.yaml
Labels: size/XS, lgtm
