Repository kyma-project/control-plane, pull requests merged in 2023-12, with the labels that each got.

#3203 Bump kubeconfig service image to v20231128-21b583e5
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XS, lgtm, cla: yes

#3201 Ory Hydra cleanup
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3204 Bump reconciler images after latest fixes to connectivity-proxy-reconciler
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm, cla: yes

#3194 Add compassRuntimeID to OperationStatus GraphQL struct to return information if the runtime is registered in Compass
  components/provisioner/Dockerfile
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/L, lgtm, cla: yes

#3209 Update provisioner image to v20231207-70b43c2b prod
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3210 Removal of KEB Leftovers
  resources/kcp/charts/kyma-environment-broker/files/catalog.yaml
  resources/kcp/charts/kyma-environment-broker/files/gardener-dashboard.json
  resources/kcp/charts/kyma-environment-broker/files/swagger.yaml
  resources/kcp/charts/kyma-environment-broker/templates/NOTES.txt
  resources/kcp/charts/kyma-environment-broker/templates/_helpers.tpl
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XXL, lgtm, cla: yes

#3212 Removed Broker Migrator from CP
  resources/kcp/templates/migrator-job.yaml
Labels: size/L, lgtm, cla: yes

#3199 Add RBAC for mothership reconciler
  resources/kcp/charts/mothership-reconciler/templates/serviceaccount.yaml
  resources/kcp/values.yaml
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/M, lgtm, cla: yes

#3214 Remove all components from Reconcile request, since they do not exist
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/M, lgtm, cla: yes

#3218 Update reconciler image to version v20231213-0a99672a
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm, cla: yes

#3223 Change KMC image as used in Prod
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3221 bump reconciler image
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/values.yaml
Labels: size/XS, lgtm, release blocker, cla: yes

#3217 Moved Subscription Cleanup to Provisioner
  resources/kcp/charts/kyma-environment-broker/.helmignore
  resources/kcp/charts/kyma-environment-broker/Chart.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/charts/provisioner/templates/subscription-cleanup-job.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/M, lgtm, cla: yes

#3227 Update Chart.yaml remove kyma-environment-broker from dependency
  resources/kcp/Chart.yaml
Labels: size/XS, lgtm, cla: yes

#3231 Migrations Cleanup
  components/schema-migrator/migrations/kyma-environment-broker/202001221020_initialize_schema.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202001221020_initialize_schema.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202001231030_add_datetimes_to_instances.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202001231030_add_datetimes_to_instances.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202002121000_add_operations.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202002121000_add_operations.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202002201000_add_lms_tenants.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202002201000_add_lms_tenants.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202004032115_add_additonal_runtime_info.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202004032115_add_additonal_runtime_info.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202004201217_fix-delated-typo.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202004201217_fix-delated-typo.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202008241000_add_orchestrations.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202008241000_add_orchestrations.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202009171000_add_runtime_states.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202009171000_add_runtime_states.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202009230900_add_orchestration_id_to_operation.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202009230900_add_orchestration_id_to_operation.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202010131417_add_provider_region_to_instance.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202010131417_add_provider_region_to_instance.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202012150900_add_provisioning_parameters_to_operation.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202012150900_add_provisioning_parameters_to_operation.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202012151612_add_version_to_instance.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202012151612_add_version_to_instance.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202101131044_add_not_null_provisioning_parameters.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202101131044_add_not_null_provisioning_parameters.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202101131045_add_cls_instances.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202101131045_add_cls_instances.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202103011331_orchestration_type.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202103011331_orchestration_type.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202103251452_add_indexes.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202103251452_add_indexes.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202104010820_add_finished_stages.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202104010820_add_finished_stages.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202105191350_add_instance_provider.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202105191350_add_instance_provider.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202141251610_add_reconciler_input.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202141251610_add_reconciler_input.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202143071502_add_instance_subscriptionGAID.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202143071502_add_instance_subscriptionGAID.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202207281547_add_expired_at.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202207281547_add_expired_at.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202209211320_events.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202209211320_events.up.sql
  components/schema-migrator/migrations/kyma-environment-broker/202210121025_drop_events_references.down.sql
  components/schema-migrator/migrations/kyma-environment-broker/202210121025_drop_events_references.up.sql
  components/schema-migrator/validate.sh
Labels: size/L, lgtm, cla: yes

#3232 Update main.go
  components/schema-migrator/main.go
Labels: size/XS, lgtm, cla: yes

#3228 Bump KMC dependencies
  components/kyma-metrics-collector/Dockerfile
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/pkg/keb/client.go
  components/kyma-metrics-collector/pkg/keb/client_test.go
  components/kyma-metrics-collector/pkg/process/process.go
  components/kyma-metrics-collector/pkg/process/process_test.go
  components/kyma-metrics-collector/pkg/testing/helpers.go
Labels: size/XL, lgtm, cla: yes

#3234 Bump KMC image to fix security issues
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3245 remove duplicated entry in provisioner values.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3247 Added machine types for sap-converged-cloud in KMC
  resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
Labels: size/M, lgtm, cla: yes

#3250 Clean up and bump dependencies
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/pkg/edp/client.go
  components/kyma-metrics-collector/pkg/keb/client.go
  components/kyma-metrics-collector/pkg/keb/client_test.go
  components/kyma-metrics-collector/pkg/process/event_stream.go
  components/kyma-metrics-collector/pkg/skr/pvc/client_test.go
  components/kyma-metrics-collector/pkg/skr/svc/client_test.go
  components/kyma-metrics-collector/pkg/testing/helpers.go
Labels: size/L, lgtm, cla: yes

#3256 fixes appdash dependency in provisioner-tests
  tests/provisioner-tests/go.mod
  tests/provisioner-tests/go.sum
Labels: size/XS, lgtm, cla: yes

#3251 KEB Cleanup
  .github/dependabot.yml
  CODEOWNERS
  components/kyma-metrics-collector/README.md
  scripts/dependabot_helper.bash
  tests/e2e/provisioning/README.md
  tests/e2e/provisioning/go.mod
  tests/e2e/provisioning/go.sum
  tests/e2e/provisioning/pkg/client/runtime/runtime_client.go
  tests/e2e/provisioning/test/test_suite.go
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/automock/keb_client.go
  tools/cli/pkg/command/deprovision.go
  tools/cli/pkg/command/kubeconfig.go
  tools/cli/pkg/command/options.go
  tools/cli/pkg/command/orchestration.go
  tools/cli/pkg/command/orchestration_test.go
  tools/cli/pkg/command/reconciliations.go
  tools/cli/pkg/command/reconciliations_disable.go
  tools/cli/pkg/command/reconciliations_disable_test.go
  tools/cli/pkg/command/reconciliations_enable.go
  tools/cli/pkg/command/reconciliations_enable_test.go
  tools/cli/pkg/command/reconciliations_state_test.go
  tools/cli/pkg/command/reconciliations_test.go
  tools/cli/pkg/command/runtime.go
  tools/cli/pkg/command/taskrun.go
  tools/cli/pkg/command/upgrade.go
  tools/cli/pkg/command/upgrade_cluster.go
  tools/cli/pkg/command/upgrade_kyma.go
  tools/cli/pkg/ers/command/client_utils.go
  tools/cli/pkg/ers/command/metadata.go
  tools/cli/pkg/ers/command/status.go
  tools/cli/pkg/printer/table.go
Labels: area/documentation, size/L, lgtm, cla: yes
