Repository kyma-project/control-plane, pull requests merged in 2023-11, with the labels that each got.

#3122 Bump `golang.org/*` dependencies in `provisioner` and `tools/cli`
  components/provisioner/go.mod
  components/provisioner/go.sum
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/L, lgtm

#3150 Add platform region to e2e tests
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
Labels: size/S, lgtm

#3154 Added Missing Prune Annotation
  resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
  resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
Labels: size/S, lgtm

#3149 Add FF env to expose schema with mandatory region
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#3157 update image
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#3158 Add missing externalTesterDisabled env to KEB chart
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#3167 Move kyma-environments-cleanup-job to KEB repo
  utils/kyma-environments-cleanup-job/README.md
  utils/kyma-environments-cleanup-job/apply.sh
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: area/documentation, size/L, lgtm

#3168 Remove application connector from reconcile request
  docs/internal/runtime-upgrade.md
  tools/reconciler/e2e-test/template-kyma-2-19.json
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: area/documentation, size/S, lgtm

#3155 Moving Config Resources to the New KEB Repo
  resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml
  resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
  resources/kcp/charts/kyma-environment-broker/templates/gardener-dashboard.yaml
  resources/kcp/charts/kyma-environment-broker/templates/keb-migrations.yaml
  resources/kcp/charts/kyma-environment-broker/templates/policy.yaml
  resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
  resources/kcp/charts/kyma-environment-broker/templates/request-authentication.yaml
  resources/kcp/charts/kyma-environment-broker/templates/secrets.yaml
  resources/kcp/charts/kyma-environment-broker/templates/swagger.yaml
Labels: size/XL, lgtm

#3173 bump images
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#3175 Reverting App Config
  resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml
Labels: size/M, lgtm

#3177 Add Subaccount Cleanup CronJob rate limiting config
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#3180 Bump KEB images to v20231115-a5b94831
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#3181 Fix maxRequestRetries value for subaccount-cleanup-job template
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#3182 Update images
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#3183 Fix Subaccount Cleanup CronJob chart template
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
Labels: size/XS, lgtm

#3186 provisioner will now create istio-system namespace
  components/provisioner/internal/runtime/configurator.go
Labels: area/control-plane, size/XS, lgtm

#3187 Update provisioner image to v20231121-fee25d8e prod
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#3185 Grant all rights to ephemeral containers for L2 Operators
  components/kubeconfig-service/pkg/runtime/runtime.go
Labels: size/XS, lgtm

#3189 Bump kubeconfig service image to v20231122-b5be2543
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XS, lgtm

#3190 Bump KEB - add Infrastructure Manager integration (provisioning steps)
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#3147 feature: kubeconfig-service secret management change
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  components/kubeconfig-service/pkg/caller/caller.go
  components/kubeconfig-service/pkg/caller/caller_test.go
  components/kubeconfig-service/pkg/caller/queryProvider.go
  components/kubeconfig-service/pkg/endpoints/endpoint.go
  components/kubeconfig-service/pkg/runtime/runtime.go
  components/kubeconfig-service/pkg/runtime/runtime_kcp.go
  components/kubeconfig-service/pkg/transformer/transformer.go
  components/kubeconfig-service/pkg/transformer/transformer_test.go
  resources/oidc-kubeconfig-service/templates/rbac.yaml
Labels: size/L, lgtm

#3198 Moved Rest of Resources
  resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/profiler-pvc.yaml
  resources/kcp/charts/kyma-environment-broker/templates/runtime-reconciler-deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/service-monitor.yaml
  resources/kcp/charts/kyma-environment-broker/templates/service.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/virtualservice.yaml
Labels: size/XXL, lgtm

#3193 Kcp-cli tool Update provisioner dependency after new release of provisioner
  tools/cli/go.mod
Labels: size/XS, lgtm, cla: yes
