Repository kyma-project/control-plane, pull requests merged in 2023-05, with the labels that each got.

#2715 use eventing group in codeowners file
  CODEOWNERS
Labels: size/S, lgtm

#2578 feature: periodic resolving orchestration runtime
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/common/orchestration/dto.go
  components/kyma-environment-broker/common/orchestration/ext.go
  components/kyma-environment-broker/internal/orchestration/manager/manager.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_cluster_test.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma.go
  components/kyma-environment-broker/internal/orchestration/manager/upgrade_kyma_test.go
Labels: size/XL, lgtm

#2719 Add more details in descriptions of OIDC schema
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params-eu.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params-eu.json
  components/kyma-environment-broker/internal/broker/testdata/azure-lite-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params-eu.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-trial-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/free-aws-schema-additional-params-eu.json
  components/kyma-environment-broker/internal/broker/testdata/free-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/free-azure-schema-additional-params-eu.json
  components/kyma-environment-broker/internal/broker/testdata/free-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/openstack-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-trial-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-free-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema-additional-params.json
  docs/kyma-environment-broker/03-12-custom-oidc-configuration.md
Labels: area/documentation, size/M, lgtm

#2701 KEB e2e tests reads client ID and secret from environment variables if present
  docs/kyma-environment-broker/03-05-authorization.md
  tests/e2e/provisioning/go.sum
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
  tests/e2e/provisioning/test/test_suite.go
Labels: area/documentation, size/XXL, lgtm

#2725 Fixing logging for Kyma apply step
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
Labels: size/XS, lgtm

#2718 bumps containerd to 1.6.18 and goland.org/x/net to 0.8.0 in provisioner
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/M, lgtm

#2728 Fixed resource version
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/config/provider_test.go
  components/kyma-environment-broker/internal/config/testdata/keb-config.yaml
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go
  components/kyma-environment-broker/internal/process/steps/kyma_template_test.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
Labels: size/S, lgtm

#2733 switches provisioner image to a prod one
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#2727 Fix Kyma Environments Cleanup Job database connection
  components/kyma-environment-broker/internal/environmentscleanup/service.go
  components/kyma-environment-broker/internal/storage/postsql/init.go
Labels: size/XS, lgtm

#2734 Bump golang images to 1.20.4 ver. in KEB and E2E Provisioning test
  components/kyma-environment-broker/Dockerfile.job
  components/kyma-environment-broker/Dockerfile.keb
  tests/e2e/provisioning/Dockerfile
Labels: size/XS, lgtm

#2737 reverts to DEV PR in order to see if it will help with url duplication
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#2735 Bump KEB related images to the latest ver. (v20230509-34c5d99a)
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#2739 fixes template for the provioner image url
  components/provisioner/cmd/main.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
Labels: size/XS, lgtm

#2736 Revert issuerURL normalisation
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/input/input_test.go
Labels: size/M, lgtm

#2741 Revert issuerURL normalisation - KEB image bump
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2742 switches slash sign in provisioner template to unencoded version
  resources/kcp/charts/provisioner/templates/deployment.yaml
Labels: size/XS, lgtm

#2749 Get kyma resource version from template
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
Labels: size/XS, lgtm

#2750 Bump KEB version
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2762 Bump KEB related images to the latest ver (v20230512-1e4cab22)
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#2738 Stoping using of deprecated field EnableBasicAuthentication from shoot
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  resources/kcp/charts/provisioner/values.yaml
Labels: size/S, lgtm

#2756 restore tracing for reconciler tests
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/S, lgtm

#2764 KEB jobs without authorization requirements
  components/kyma-environment-broker/internal/broker/client.go
Labels: size/S, lgtm

#2765 KEB jobs with local url to KEB
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2766 Revert local urls in jobs
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
Labels: size/M, lgtm

#2767 Revert "restore tracing for reconciler tests (#2756)"
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/S, lgtm

#2768 Bumped chart apiVersions to v2
  resources/kcp/Chart.yaml
  resources/kcp/charts/kyma-environment-broker/Chart.yaml
  resources/kcp/charts/kyma-metrics-collector/Chart.yaml
  resources/kcp/charts/postgresql/Chart.yaml
  resources/kcp/charts/provisioner/Chart.yaml
  resources/kcp/requirements.yaml
Labels: size/M, lgtm

#2769 Using schema validator to validate update input
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/upgrade_kyma_test.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/broker/instance_update_test.go
Labels: size/L, lgtm

#2777 Enable istio for KEB jobs, use direct url to keb
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
Labels: size/M, lgtm

#2780 Enable local connections in istio auth policy
  resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
Labels: size/S, lgtm

#2784 Deploymentruntimereconciler2
  resources/kcp/charts/kyma-environment-broker/templates/runtime-reconciler-deployment.yaml
Labels: size/L, lgtm

#2786 trigger build
  components/kyma-environment-broker/cmd/runtimereconciler/main.go
Labels: size/XS, lgtm

#2787 bump kebs images
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2789 Get rid of panic in get kubeconfig step for upgrade
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/initialisation_test.go
Labels: size/L, lgtm

#2788 Stop istio after jobs completion
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#2791 Bump KEB jobs
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2794 Subscriptioncleanupjob haltistio
  components/kyma-environment-broker/cmd/subscriptioncleanup/main.go
Labels: size/S, lgtm

#2797 Bump subbaccount cleanup job - halt istio at the end
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2779 Update reconciler images versions
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2802 Bump subscription cleanup job
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2799 runtime reconciler - improvements
  components/kyma-environment-broker/internal/btpmanager/credentials/manager.go
  components/kyma-environment-broker/internal/btpmanager/credentials/manager_test.go
Labels: size/M, lgtm

#2795 Add missing error state event for deprovisioning steps
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go
  components/kyma-environment-broker/internal/process/operation_manager.go
Labels: size/M, lgtm

#2804 Bump KEB image after PR-2795
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2806 added telemetry module exclusion from reconcilation
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2807 Bump images 2505
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2714 Automatically generate documentation for prometheus-metrics
  components/kyma-metrics-collector/Makefile
  components/kyma-metrics-collector/README.md
  components/kyma-metrics-collector/hack/metrics.md.tpl
  components/kyma-metrics-collector/metrics.md
Labels: area/documentation, size/S, lgtm

#2810 Use batch/v1 for CronJobs
  resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
Labels: size/XS, lgtm

#2812 Fix leftover batch/v1beta1 CronJob
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
Labels: size/XS, lgtm

#2809 add more labels to Kyma resource
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
Labels: size/XS, lgtm
