Repository kyma-project/control-plane, pull requests merged in 2023-09, with the labels that each got.

#3039 document a follow-up for cids fields storage in provisioner db
  components/provisioner/pkg/gqlschema/schema.graphql
Labels: area/control-plane, size/XS, lgtm, kind/cleanup

#3034 Render env-var for skipped components
  resources/kcp/charts/component-reconcilers/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#3040 Adds option VMServiceScrape generation
  resources/kcp/charts/component-reconcilers/templates/service-monitor.yaml
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/kyma-environment-broker/templates/service-monitor.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/service-monitor.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/service.yaml
  resources/kcp/charts/kyma-metrics-collector/values.yaml
  resources/kcp/charts/mothership-reconciler/templates/service-monitor.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/charts/provisioner/templates/service-monitor.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/L, lgtm

#3043 Bump KEB images to the latest ver. v20230901-053636e6
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#3036 Adjust the diagram to the content guidelines
  docs/kyma-environment-broker/02-01-architecture.md
  docs/kyma-environment-broker/assets/keb-arch.drawio
  docs/kyma-environment-broker/assets/keb-arch.svg
Labels: area/documentation, size/L, lgtm

#3020 Networking params
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  components/kyma-environment-broker/internal/broker/broker.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_step.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/aws_provider_test.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider_test.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XL, lgtm

#3058 Fix AWS zones
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/aws_provider_test.go
Labels: size/S, lgtm

#3059 Bump KEB - fix AWS IP ranges in zones
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#3061 Only Node CIDR is allowe, json schemas for ip ranges
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/networking/cidr.go
  components/kyma-environment-broker/internal/process/input/input.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
  components/kyma-environment-broker/internal/provider/openstack_provider.go
  docs/kyma-environment-broker/03-01-service-description.md
Labels: area/documentation, size/L, lgtm

#3062 Bump KEB
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#3063 Ipranges in preview
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/broker/plans.go
Labels: size/S, lgtm

#3064 IP ranges in all plans JSON schemas
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/plans_test.go
Labels: size/XS, lgtm

#3065 KEB Version Bump
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#3068 Version Bump for New Keb Repo
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#3076 Typo
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/runtime-reconciler-deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
Labels: size/S, lgtm

#3026 updates provisioner readme with tips on running tests
  components/provisioner/README.md
Labels: area/documentation, area/control-plane, size/XS, lgtm, kind/cleanup

#3078 Networking params in json schema tests
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#3079 Conditionally remove helm/argo annotations in gardener-credentials
  resources/kcp/charts/provisioner/templates/gardener-creds-secret.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#3081 Update provisioner image to latest version from prod repo
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#3082 Bump KEB images to v20230915-bbc9f156
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#3069 Enable workload identity for jobs
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/keb-db-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/runtime-reconciler-deployment.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/templates/migrator-job.yaml
Labels: size/L, lgtm

#3084 Adding talszabi to kubeconfig-service and kcp-cli code owners
  CODEOWNERS
Labels: size/XS, lgtm

#3086 Bump reconciler for Ory Hydra migration
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/S, lgtm

#3087 Bumping the image in kubeconfig-service chart to v20230927-3979470d
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XS, lgtm

#3092 remove typo extra j letter
  resources/kcp/templates/migrator-job.yaml
Labels: size/XS, lgtm

#3093 Test Config Map
  resources/kcp/charts/kyma-environment-broker/templates/refactoring-config.yaml
Labels: size/XS, lgtm

#3095 Bump KEB imgs to the latest ver. v20230929-752f7838
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#3096 Testing Argo Resource Migration
  resources/kcp/charts/kyma-environment-broker/templates/refactoring-config.yaml
Labels: size/XS, lgtm

#3097 Fix for provisioned shoot DNS
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
Labels: size/XS, lgtm

#3098 Update provisioner image to latest version from prod repo
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm
