Repository kyma-project/control-plane, pull requests merged in 2023-01, with the labels that each got.

#2374 KCP CLI: fix setting maintenance window
  tools/cli/pkg/command/orchestration.go
  tools/cli/pkg/command/upgrade.go
Labels: size/M, lgtm

#2377 Revert "kcp-migration-broker and provisioner - change on helm hook annotations (#2330)"
  resources/kcp/templates/migrator-job.yaml
Labels: size/XS, lgtm

#2372 Configurable integration of KEB with LM and Reconciler
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/apply_kyma_step.go
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2375 Tests Time Refactoring
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/internal/broker/client.go
  components/kyma-environment-broker/internal/broker/client_test.go
  components/kyma-environment-broker/internal/broker/poller.go
  components/schema-migrator/main.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/L, lgtm

#2383 Fail process if overrides not found
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/secret_cm_overrides.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2391 kubeconfig-service: use SA TokenRequest API instead of secret bound token
  components/kubeconfig-service/pkg/runtime/runtime.go
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/M, lgtm

#2390 Add tests for version overrides
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/internal/process/provisioning/secret_cm_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/secret_cm_overrides.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2396 Add eu access column to runtimes command
  tools/cli/pkg/command/runtime.go
Labels: size/S, lgtm

#2399 Adjust kyma deletion timeout to 30 min
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2389 Show warning on downloading eu kubeconfig
  tools/cli/pkg/command/kubeconfig.go
  tools/cli/pkg/command/kubeconfig_test.go
Labels: size/M, lgtm

#2410 Fix scheme concurrent map write panic
  components/kyma-environment-broker/cmd/broker/main.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2402 For testing purposes always fail instance creation (EU Access story)
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2409 Remove Kiali from component lists
  components/kyma-environment-broker/cmd/broker/testdata/kyma-installer-cluster.yaml
  components/kyma-environment-broker/internal/runtime/testdata/kyma-components.yaml
  components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml
  installation/resources/installer-cr-kyma-dependencies.yaml
  installation/resources/installer-cr-kyma-kcp-dependencies.yaml
  installation/resources/kyma-components.yaml
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/S, lgtm

#2412 Store failed steps during deprovisioning
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/avs_evaluations.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/ias_deregistration.go
  components/kyma-environment-broker/internal/process/operation_manager.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager_kubeconfig.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2380 Encrypt data in Provisioners database
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/model/kyma_config.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/shootupgrade/mocks/KubeconfigProvider.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade_test.go
  components/provisioner/internal/provider-config-migrator/migrator_db_integration_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/cipher.go
  components/provisioner/internal/provisioning/persistence/dbsession/cipher_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/schema-migrator/migrations/provisioner/202301041252_is_encrypted.down.sql
  components/schema-migrator/migrations/provisioner/202301041252_is_encrypted.up.sql
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
Labels: area/control-plane, size/L, lgtm

#2417 KEB to give failed steps information for KCP
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/process/operation_manager.go
  components/kyma-environment-broker/internal/runtime/converter.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2420 KCP display failed steps for operations
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/XS, lgtm

#2422 Store failed steps for deprovisioning
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_cluster_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/deregister_cluster.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration.go
  components/kyma-environment-broker/internal/process/deprovisioning/edp_deregistration_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2431 Remove excessive log messages
  components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/get_kubeconfig_step.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2435 Bump fluentbit to latest image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2436 EU Access documentation updated with whitelisting details
  docs/eu_access.md
Labels: area/documentation, size/M, lgtm

#2445 Bump Kyma Operator in Provisioner
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/charts/provisioner/values.yaml
Labels: size/M, lgtm

#2401 Upgrade Go Image for `KMC` to `1.19.5-alpine3.17`
  components/kyma-metrics-collector/Dockerfile
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2413 Use whitelist from configuration to allow EU Access
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/cmd/broker/provisioning_test.go
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/cmd/broker/testdata/eu_access_whitelist.yaml
  components/kyma-environment-broker/common/hyperscaler/azure/env.go
  components/kyma-environment-broker/internal/broker/instance_create.go
  components/kyma-environment-broker/internal/broker/instance_create_test.go
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  components/kyma-environment-broker/internal/broker/services.go
  components/kyma-environment-broker/internal/euaccess/eu_access.go
  components/kyma-environment-broker/internal/euaccess/test/eu_access_whitelist.yaml
  components/kyma-environment-broker/internal/euaccess/whitelisted_globalaccounts.go
  components/kyma-environment-broker/internal/euaccess/whitelisted_globalaccounts_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration_test.go
  resources/kcp/charts/kyma-environment-broker/templates/app-config.yaml
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm
