Repository kyma-project/control-plane, pull requests merged in 2023-02, with the labels that each got.

#2443 Configure PSA for KMC
  resources/kcp/charts/kyma-metrics-collector/templates/deployment.yaml
  resources/kcp/charts/kyma-metrics-collector/values.yaml
Labels: area/eventing, size/M, lgtm

#2429 Mark instance as deleted_at without removing it
  components/kyma-environment-broker/internal/broker/instance_get.go
  components/kyma-environment-broker/internal/broker/instance_get_test.go
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/remove_instance_step_test.go
  components/kyma-environment-broker/internal/storage/driver/memory/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  components/kyma-environment-broker/internal/storage/postsql/write.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2447 KEB update machine type
  components/kyma-environment-broker/internal/broker/instance_update.go
  components/kyma-environment-broker/internal/dto.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/update/upgrade_shoot_step.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2440 Revert back eventing reconciler
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2464 Update Goland standard libraries to latest versions
  components/provisioner/go.mod
  components/provisioner/go.sum
  resources/kcp/charts/provisioner/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/L, lgtm

#2395 Provisioner creates secrets for Compass-Runtime-Agent in kyma-system Namespace
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/runtime/configuration_test.go
  components/provisioner/internal/runtime/configurator.go
  resources/kcp/charts/provisioner/values.yaml
Labels: area/control-plane, size/M, lgtm

#2449 Deprovision retrigger job definition
  components/kyma-environment-broker/Dockerfile.drj
  components/kyma-environment-broker/cmd/deprovisionretrigger/main.go
  components/kyma-environment-broker/internal/storage/dbmodel/instance.go
  components/kyma-environment-broker/internal/storage/driver/postsql/instance_test.go
  components/kyma-environment-broker/internal/storage/postsql/read.go
  resources/kcp/charts/kyma-environment-broker/templates/deprovision-retrigger-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2455 KEB catalog to allow machine type update
  components/kyma-environment-broker/internal/broker/plans_schema.go
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params-eu.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-lite-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-openstack-schema.json
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2471 Fix KEB runtime endpoint to list instances with incomplete deprovisioning
  components/kyma-environment-broker/internal/runtime/handler.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2468 App Builder
  components/kyma-environment-broker/cmd/environmentscleanup/main.go
  components/kyma-environment-broker/common/setup/builder.go
  components/kyma-environment-broker/common/setup/error_handlers.go
  components/kyma-environment-broker/internal/environmentscleanup/service.go
Labels: size/L, lgtm

#2474 KEB to set operation description on success
  components/kyma-environment-broker/internal/process/staged_manager.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2475 Generic Dockerfile for KEB jobs
  components/kyma-environment-broker/Dockerfile.job
Labels: size/S, lgtm

#2478 Update KMC security context
  resources/kcp/charts/kyma-metrics-collector/values.yaml
Labels: size/XS, lgtm

#2486 Update code owners
  CODEOWNERS
  OWNERS
  OWNERS_ALIASES
Labels: size/S, lgtm

#2490 Add a code owner
  CODEOWNERS
  OWNERS
Labels: size/XS, lgtm

#2485 Production plan with minimum nodes 3
  components/kyma-environment-broker/internal/broker/plans.go
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params-eu.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema-eu.json
  components/kyma-environment-broker/internal/broker/testdata/aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params-eu.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema-eu.json
  components/kyma-environment-broker/internal/broker/testdata/azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/gcp-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-aws-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-azure-schema.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema-additional-params.json
  components/kyma-environment-broker/internal/broker/testdata/update-gcp-schema.json
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2491 Allow re-deprovision after successful deprovision
  components/kyma-environment-broker/internal/broker/instance_deprovision.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2492 Use gopher group in CODEOWNERS instead of enumerating its members
  CODEOWNERS
Labels: size/S, lgtm

#2493 Additional check to skip redeprovisioning
  components/kyma-environment-broker/internal/broker/instance_deprovision.go
  docs/kyma-environment-broker/03-16-deprovision-retrigger-cronjob.md
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: area/documentation, size/M, lgtm

#2499 KEB set and read instance deleted_at field
  components/kyma-environment-broker/common/runtime/model.go
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/storage/postsql/write.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2504 Modify KCP CLI to deploy with maintenancemode flag set to true by default.
  tools/cli/pkg/command/upgrade.go
Labels: size/XS, lgtm

#2508 Kyme Environment Broker Version Updates
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2509 Adding MachineType update test
  components/kyma-environment-broker/cmd/broker/update_test.go
Labels: size/M, lgtm

#2505 Provisioner compatible with Kubernetes >= 1.25
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provider-config-migrator/migrator_db_integration_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/util/testkit/shoot.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/L, lgtm

#2513 ApllyKyma steps works if RuntimeID is empty
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2483 Remove compass-system dependencies
  components/kyma-environment-broker/cmd/broker/testdata/managed-runtime-components.yaml
  components/kyma-environment-broker/internal/runtime/components_provider_test.go
  components/kyma-environment-broker/internal/runtime/testdata/additional-runtime-components.yaml
  components/kyma-environment-broker/internal/runtime/testdata/managed-runtime-components.yaml
  docs/internal/runtime-upgrade.md
  docs/provisioner/08-02-provisioning-gardener.md
  installation/resources/installer-cr-compass-dependencies.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  tests/provisioner-tests/test/testkit/compass/director/oauth/client_test.go
  tests/provisioner-tests/test/testkit/inputs.go
Labels: area/application-connector, area/documentation, area/control-plane, size/L, lgtm

#2500 Fix for incorrect processing of empty encryption key in Provisioner
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/provider-config-migrator/migrator_db_integration_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/cipher.go
  components/provisioner/internal/provisioning/persistence/dbsession/cipher_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/M, lgtm

#2517 Revert "Modify KCP CLI to deploy with maintenancemode flag set to true by default."
  tools/cli/pkg/command/upgrade.go
Labels: size/XS, lgtm

#2520 KEB instance delete capture User-Agent header
  components/kyma-environment-broker/cmd/accountcleanup/main.go
  components/kyma-environment-broker/internal/broker/client.go
  components/kyma-environment-broker/internal/broker/instance_deprovision.go
  components/kyma-environment-broker/internal/broker/server.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/deprovisioning/btp_operator_cleanup.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2477 KEB jobs Dockerfile cleanup
  components/kyma-environment-broker/Dockerfile.cleanup
  components/kyma-environment-broker/Dockerfile.drj
  components/kyma-environment-broker/Dockerfile.sac
  components/kyma-environment-broker/Dockerfile.scj
  components/kyma-environment-broker/Dockerfile.tcj
  resources/kcp/charts/kyma-environment-broker/templates/environments-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/subscription-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2530 Remove duplicate 'command' for trial cleanup job
  resources/kcp/charts/kyma-environment-broker/templates/trial-cleanup-job.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm
