Repository kyma-project/control-plane, pull requests merged in 2023-08, with the labels that each got.

#2951 Change Kyma components URL for release version
  components/kyma-environment-broker/internal/runtime/components_provider.go
  components/kyma-environment-broker/internal/runtime/components_provider_fake.go
  components/kyma-environment-broker/internal/runtime/components_provider_test.go
  components/kyma-environment-broker/internal/runtime/provider_test.go
Labels: size/XS, lgtm

#2952 Bump KEB related images to v20230801-b6b0b483
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#2960 Check Provider in Instance before attempting to release subscription
  components/kyma-environment-broker/internal/process/deprovisioning/release_subscription_step.go
Labels: size/XS, lgtm

#2956 Workload Identity
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm

#2972 Fix a typo
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
Labels: size/XS, lgtm

#2969 Remove hydra OAuth2 endpoint from KEB
  resources/kcp/charts/kyma-environment-broker/templates/authorization-policy.yaml
Labels: size/XS, lgtm

#2981 Fix Deprovision_AVS_Evaluations step
  components/kyma-environment-broker/internal/avs/client.go
  components/kyma-environment-broker/internal/avs/delegator.go
  components/kyma-environment-broker/internal/avs/mock_server.go
Labels: size/M, lgtm

#2982 Bump golang builder to golang:1.21.0-alpine3.18 in dockerfiles
  components/kyma-environment-broker/Dockerfile.job
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/Dockerfile.runtimereconciler
Labels: size/XS, lgtm

#2966 adds git ignore for migration files generated by provisioner e2e tests
  components/provisioner/.gitignore
Labels: area/control-plane, size/XS, lgtm

#2983 Add missing bracket
  resources/kcp/charts/kyma-environment-broker/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/provisioner/templates/deployment.yaml
Labels: size/XS, lgtm

#2965 adds a check for timeout tool for provisioner e2e test
  components/provisioner/e2e_test/test.sh
Labels: size/XS, lgtm

#2980 Retry when unable to create k8sclient for operation
  components/kyma-environment-broker/internal/process/provisioning/get_kubeconfig_step.go
  components/kyma-environment-broker/internal/process/update/get_kubeconfig_step.go
Labels: size/XS, lgtm

#2984 Update KEB dependencies
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
Labels: size/L, lgtm

#2986 Bump reconciler - PVC interceptor
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2987 Bump KEB images to v20230811-cdd7db1d
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#2997 Don't stop istio reconciliation on v1alpha2
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2959 Remove Provisioning queue for Kyma 1.0 installation
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/metrics/in_progress_operations.go
  components/provisioner/internal/metrics/in_progress_operations_test.go
  components/provisioner/internal/model/types.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/persistence/dbsession/factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/Factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XL, lgtm

#3007 Update reconciler to image v20230816-6b351968 - use Istio operator as installation method for Istio
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2999 reuse compliance
  .reuse/dep5
  LICENSES/Apache-2.0.txt
  README.md
Labels: area/documentation, size/L, lgtm

#2967 Remove Deprovisioning queue for Kyma 1.0 installation
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/metrics/in_progress_operations.go
  components/provisioner/internal/metrics/in_progress_operations_test.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/provisioning/mocks/Provisioner.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/provisioning/mocks/ShootProvider.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XL, lgtm

#2978 Remove HibernateCluster operation
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/mocks/Provisioner.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XL, lgtm

#2968 Adds ip ranges fields to provisioner
  components/provisioner/assets/database/provisioner.sql
  components/provisioner/e2e_test/requests/provision.graphql
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/provisioning/graphql_converter.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/persistence/dbsession/write.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
  docs/provisioner/08-02-provisioning-gardener.md
  docs/provisioner/08-04-runtime-status.md
  resources/kcp/charts/provisioner/migrations/202308180833_add_pods_cidr_and_services_cidr_entry.down.sql
  resources/kcp/charts/provisioner/migrations/202308180833_add_pods_cidr_and_services_cidr_entry.up.sql
  resources/kcp/charts/provisioner/values.yaml
Labels: area/documentation, area/control-plane, size/L, lgtm

#3031 Use production images for kubeconfig-service
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XS, lgtm

#3021 Add internal label for Kyma resource
  components/kyma-environment-broker/internal/fixture/fixture.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
Labels: size/L, lgtm
