Repository kyma-project/control-plane, pull requests merged in 2023-06, with the labels that each got.

#2818 Added Missing ShootNetworkingFilterDisabled Field
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
Labels: size/XS, lgtm

#2821 Update values.yaml for PR-2818
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2823 Add serverless to reconciler's exclusion list
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2822 Configure maxSurge equal to the number of znoes for enterprise plan runtimes
  components/kyma-environment-broker/internal/process/provisioning/check_cluster_configuration_test.go
  components/kyma-environment-broker/internal/process/provisioning/create_runtime_without_kyma_test.go
  components/kyma-environment-broker/internal/provider/aws_provider.go
  components/kyma-environment-broker/internal/provider/azure_provider.go
  components/kyma-environment-broker/internal/provider/gcp_provider.go
Labels: priority/high, size/S, lgtm

#2824 Bump KEB to the latest version
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2811 Audit log extension
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/testdata/config.json
  components/provisioner/internal/gardener/auditlogging.go
  components/provisioner/internal/gardener/auditlogging_test.go
  components/provisioner/internal/gardener/shoot_reconciler.go
  components/provisioner/internal/gardener/testdata/config.json
Labels: size/L, lgtm

#2827 update runtime reconciler image
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2829 update go version for kubeconfig-service and KCP CLI
  components/kubeconfig-service/Dockerfile
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  resources/oidc-kubeconfig-service/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/XL, lgtm

#2828 bump dependencies in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#2831 Bump provisioner image
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2832 Revert "bump dependencies in KMC"
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  resources/kcp/values.yaml
Labels: size/M, lgtm

#2836 Update without btp operator
  components/kyma-environment-broker/cmd/broker/suite_test.go
  components/kyma-environment-broker/internal/model.go
  components/kyma-environment-broker/internal/process/provisioning/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/update/btp_operator_overrides.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/btp_operator_overrides.go
Labels: size/S, lgtm

#2837 Make the audit config change less invasive
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#2840 Fix provisioner chart
  resources/kcp/charts/provisioner/templates/deployment.yaml
Labels: size/XS, lgtm

#2841 Failing operation when panic occurs in the step
  components/kyma-environment-broker/internal/process/staged_manager.go
  components/kyma-environment-broker/internal/process/staged_manager_test.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/manager.go
  components/kyma-environment-broker/internal/process/upgrade_cluster/manager_test.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/manager.go
  components/kyma-environment-broker/internal/process/upgrade_kyma/manager_test.go
Labels: size/L, lgtm

#2846 Bump KEB to the newest version
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2842 Update reconciler images after changes for connectivity proxy version 2.9.2
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2796 Include shoot info in data sent to edp from KMC
  components/kyma-metrics-collector/pkg/edp/consumption_metrics.go
  components/kyma-metrics-collector/pkg/process/process.go
  components/kyma-metrics-collector/pkg/process/process_test.go
Labels: size/S, lgtm

#2848 Bumped KMC image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2855 Goland Update
  components/kyma-environment-broker/Dockerfile.job
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/Dockerfile.runtimereconciler
  tests/e2e/provisioning/Dockerfile
Labels: size/XS, lgtm

#2856 Fixed KMC image name
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2857 Image Bump
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#2854 Provisioner audit logs: Change region, add logging fields
  components/provisioner/internal/api/testdata/config.json
  components/provisioner/internal/gardener/auditlogging.go
  components/provisioner/internal/gardener/auditlogging_test.go
  resources/kcp/charts/provisioner/values.yaml
Labels: size/M, lgtm

#2863 bump go version to 1.20.5 in /components/kubeconfig-service
  components/kubeconfig-service/Dockerfile
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XS, lgtm

#2869 Restores schema migrator version
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2873 Fix NodePort conflict with internal docker registry
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2866 Stop using label "type=admin" for ClusterRuleBindins created by Provisioner
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#2874 Add ShootNetworkingFilterDisabled to upgrade shoot body graphql
  components/kyma-environment-broker/internal/provisioner/graphqlizer.go
  components/kyma-environment-broker/internal/provisioner/graphqlizer_test.go
Labels: size/XS, lgtm

#2875 Bump KEB
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2880 Bump reconciler to deliver fix for nodeport conflict bug in serverless
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2885 Update reconciler images after fixes to connectivity proxy reconciler
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2889 Bump reconciler images after latest fixes to connectivity proxy reconciler
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2892 Bump fb to latest image to fix CVE
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2894 Bug fix for not handled error in KMC
  components/kyma-metrics-collector/pkg/process/process.go
Labels: size/XS, lgtm

#2895 Image bump for KMC
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2897 Hydra removal
  resources/kcp/charts/kyma-environment-broker/templates/oauth-client.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm
