Repository kyma-project/control-plane, pull requests merged in 2023-04, with the labels that each got.

#2598 Correct runtime state when op state is pending
  components/kyma-environment-broker/internal/runtime/converter.go
  components/kyma-environment-broker/internal/runtime/converter_test.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/M, lgtm

#2638 More logs for Kyma resource handling
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2657 bumps provisioner golang to 1.20.3 and alpine to 3.17.3
  components/provisioner/Dockerfile
  components/provisioner/go.mod
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#2677 Logging for staged manager
  components/kyma-environment-broker/internal/process/queue.go
  components/kyma-environment-broker/internal/process/staged_manager.go
  components/kyma-environment-broker/internal/storage/driver/postsql/operation.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2661 bumps golang to 1.20.3-alpine3.17 and switches go.mod to 1.20 in subscription-cleanup-job
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/go.mod
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/XS, lgtm

#2680 bump golang-runtime from 1.20.2 to 1.20.3 in keb
  components/kyma-environment-broker/Dockerfile.job
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2682 Add KCP cli to dependabot
  .github/dependabot.yml
Labels: size/S, lgtm

#2694 Remove obsolete KCP installation
  README.md
  installation/README.md
  installation/cmd/run.sh
  installation/resources/COMPASS_VERSION
  installation/resources/KYMA2_VERSION
  installation/resources/KYMA_VERSION
  installation/resources/README.md
  installation/resources/installer-config-local.yaml.tpl
  installation/resources/installer-cr-compass-dependencies.yaml
  installation/resources/installer-cr-kyma-dependencies.yaml
  installation/resources/installer-cr-kyma-kcp-dependencies.yaml
  installation/resources/installer-cr.yaml.tpl
  installation/resources/installer-overrides-compass.yaml
  installation/resources/installer-overrides-kyma.yaml
  installation/resources/installer.yaml
  installation/resources/kyma-components.yaml
  installation/scripts/build-kcp-installer.sh
  installation/scripts/concat-yamls.sh
  installation/scripts/configure-components.sh
  installation/scripts/create-cr.sh
  installation/scripts/extract-kcp-installer-image.sh
  installation/scripts/generate-installer-artifacts.sh
  installation/scripts/installer.sh
  installation/scripts/is-installed.sh
  installation/scripts/is-kyma-installed.sh
  installation/scripts/is-ready.sh
  installation/scripts/kyma-scripts/testing-common.sh
  installation/scripts/kyma-scripts/utils.sh
  installation/scripts/run-compass-installer.sh
  installation/scripts/run-kcp-installer.sh
  tools/kcp-installer/Makefile
  tools/kcp-installer/kcp.Dockerfile
Labels: area/documentation, size/XXL, lgtm

#2691 Sanity check for deprovision retrigger redone
  components/kyma-environment-broker/cmd/deprovisionretrigger/main.go
  components/kyma-environment-broker/internal/broker/client.go
  components/kyma-environment-broker/internal/broker/client_test.go
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/L, lgtm

#2695 Set new image for registration-job
  resources/kcp/templates/registration-job.yaml
Labels: size/XS, lgtm

#2678 Dashbaord Redirect Assertion - Status Correction
  resources/kcp/values.yaml
  tests/e2e/provisioning/Dockerfile
  tests/e2e/provisioning/Gopkg.lock
  tests/e2e/provisioning/Gopkg.toml
  tests/e2e/provisioning/Makefile
  tests/e2e/provisioning/README.md
  tests/e2e/provisioning/go.mod
  tests/e2e/provisioning/go.sum
  tests/e2e/provisioning/pkg/client/runtime/dashboard_checker.go
  tests/e2e/provisioning/test/e2e_provisioning_test.go
  tests/e2e/provisioning/test/e2e_suspension_test.go
  tests/e2e/provisioning/test/test_suite.go
Labels: area/documentation, size/XXL, lgtm

#2699 Bump Golang and Alpine image versions in provisioner-tests
  resources/kcp/values.yaml
  tests/provisioner-tests/Dockerfile
Labels: size/XS, lgtm

#2706 Generate production images on new Artifact Registry for Provisioner tests
  resources/kcp/values.yaml
  tests/provisioner-tests/Dockerfile
Labels: size/XS, lgtm

#2708 remove tracing component
  components/kyma-environment-broker/cmd/broker/testdata/kyma-installer-cluster.yaml
  components/kyma-environment-broker/internal/runtime/testdata/kyma-components.yaml
  components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: size/S, lgtm

#2712 Migrate KEB, provisioner and KMC images to artifact registry
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/charts/kyma-metrics-collector/values.yaml
  resources/kcp/charts/provisioner/values.yaml
  resources/kcp/values.yaml
Labels: size/S, lgtm

#2709 Move Kyma Environments Cleanup job out of KCP chart
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/README.md
  utils/kyma-environments-cleanup-job/apply.sh
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: area/documentation, size/L, lgtm

#2716 Update reconciler images to latest and from new registry
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm
