Repository kyma-project/control-plane, pull requests merged in 2023-07, with the labels that each got.

#2896 fix name for mothership reconciler audit log image
  resources/kcp/values.yaml
Labels: size/XS, lgtm

#2898 Upgrade mothership reconciler image
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2900 Remove logging component from tests
  components/kyma-environment-broker/cmd/broker/testdata/kyma-installer-cluster.yaml
  components/kyma-environment-broker/internal/reconciler/test/cluster.json
  components/kyma-environment-broker/internal/runtime/testdata/kyma-components.yaml
  components/kyma-environment-broker/internal/runtime/testdata/kyma-installer-cluster.yaml
  tools/reconciler/e2e-test/template-kyma-main.json
Labels: area/logging, size/M, lgtm, kind/cleanup

#2891 Keb kyma resource version independent
  components/kyma-environment-broker/cmd/broker/broker_suite_test.go
  components/kyma-environment-broker/cmd/broker/deprovisioning_suite_test.go
  components/kyma-environment-broker/cmd/broker/main.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/check_kyma_resource_deleted_step_test.go
  components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step.go
  components/kyma-environment-broker/internal/process/deprovisioning/delete_kyma_resource_step_test.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step.go
  components/kyma-environment-broker/internal/process/provisioning/apply_kyma_step_test.go
  components/kyma-environment-broker/internal/process/steps/lifecycle_manager.go
Labels: size/L, lgtm

#2906 Bump KEB images to v20230705-30c430b0
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#2912 bumps KEB's dependency to provisioner
  components/kyma-environment-broker/go.mod
  components/kyma-environment-broker/go.sum
Labels: size/XS, lgtm

#2911 Bump cloudsql-proxy image to v1.33.8-afb993b8
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#2913 Remove keb Hydra oauth client
  resources/kcp/charts/kyma-environment-broker/templates/oauth-client.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
Labels: size/S, lgtm

#2917 Fix failing cronjobs
  resources/kcp/charts/kyma-environment-broker/templates/subaccount-cleanup-job.yaml
  utils/kyma-environments-cleanup-job/apply.sh
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/M, lgtm

#2902 Change REST Update to Patch on shoot CRDs
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/gardener/mocks/Client.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/util/testkit/shoot.go
  resources/kcp/charts/provisioner/values.yaml
  tools/cli/go.mod
  tools/cli/go.sum
Labels: area/control-plane, priority/critical, size/L, lgtm

#2923 Move eu-access.md to KEB folder
  docs/kyma-environment-broker/02-02-broker-endpoints.md
  docs/kyma-environment-broker/03-18-eu-access.md
Labels: area/documentation, size/S, lgtm

#2920 Update the structure of Azure Gardener extensions
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/infrastructure/azure/infrastructure.go
  resources/kcp/charts/provisioner/values.yaml
Labels: area/control-plane, size/S, lgtm

#2927 Golang upgrade
  components/kyma-environment-broker/Dockerfile.job
  components/kyma-environment-broker/Dockerfile.keb
  components/kyma-environment-broker/Dockerfile.runtimereconciler
  tests/e2e/provisioning/Dockerfile
Labels: size/XS, lgtm

#2919 Adapt provisioner to gardener changes
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/gardener/kubeconfig_provider.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/provisioning/mocks/GardenerClient.go
  components/provisioner/internal/operations/stages/provisioning/mocks/KubeconfigProvider.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain.go
  components/provisioner/internal/operations/stages/shootupgrade/mocks/KubeconfigProvider.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade_test.go
Labels: size/L, lgtm

#2929 bump provisioner version
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm

#2930 Add versions to kcp chart deps
  resources/kcp/Chart.yaml
Labels: size/XS, lgtm

#2932 Enable static token kubeconfig in provisioner
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/gardener/kubeconfig_provider.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/provisioning/mocks/GardenerClient.go
  components/provisioner/internal/operations/stages/provisioning/mocks/KubeconfigProvider.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain.go
  components/provisioner/internal/operations/stages/shootupgrade/mocks/KubeconfigProvider.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade_test.go
  resources/kcp/charts/provisioner/values.yaml
Labels: size/L, lgtm

#2936 Bump KEB images to #2927
  resources/kcp/charts/kyma-environment-broker/values.yaml
  utils/kyma-environments-cleanup-job/kyma-environments-cleanup-job.yaml
Labels: size/S, lgtm

#2933 Make env-vars configurable
  resources/kcp/charts/mothership-reconciler/templates/deployment.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2937 Service account annotation
  resources/kcp/charts/kyma-environment-broker/templates/rbac.yaml
  resources/kcp/charts/kyma-environment-broker/values.yaml
  resources/kcp/charts/mothership-reconciler/templates/serviceaccount.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/charts/provisioner/templates/service-account.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/S, lgtm

#2918 Adapt provisioner for running local
  components/provisioner/README.md
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/oauth/client.go
  components/provisioner/internal/oauth/client_test.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: area/documentation, size/L, lgtm

#2941 Update golang builder image for Provisioner to version 1.20.6-alpine3.18
  components/provisioner/Dockerfile
Labels: size/XS, lgtm

#2945 Bump image of mothership-reconciler
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm

#2947 Bump image tag to PR-2916
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XS, lgtm

#2886 Provisioner e2e tests
  components/provisioner/e2e_test/main_test.go
  components/provisioner/e2e_test/pgsetup.go
  components/provisioner/e2e_test/requests/deprovision.graphql
  components/provisioner/e2e_test/requests/provision.graphql
  components/provisioner/e2e_test/requests/status.graphql
  components/provisioner/e2e_test/test.sh
  components/provisioner/go.mod
  components/provisioner/go.sum
Labels: area/documentation, size/L, lgtm
