Repository kyma-project/control-plane, pull requests merged in 2024-07, with the labels that each got.

#3457 fix Blocking SSH access for all provisioned and upgraded Kyma runtimes
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/util/testkit/shoot.go
Labels: area/security, size/M, lgtm, priority/critical-urgent, cla: yes

#3458 Update Provisioner image to version v20240703-110e15f7
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3454 Added Persistent Volume Claim reference
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/templates/pvc.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/M, lgtm, cla: yes

#3461 feat: Setting tolerations-field in `me-central2` region
  components/provisioner/internal/gardener/provisioner.go
Labels: size/XS, lgtm, cla: yes
