Repository kyma-project/control-plane, pull requests merged in 2024-04, with the labels that each got.

#3422 chore: removed kyma-metrics-collector source code
  .github/dependabot.yml
  components/kyma-metrics-collector/Dockerfile
  components/kyma-metrics-collector/Makefile
  components/kyma-metrics-collector/OWNERS
  components/kyma-metrics-collector/README.md
  components/kyma-metrics-collector/cmd/main.go
  components/kyma-metrics-collector/dev/deployment.yaml
  components/kyma-metrics-collector/env/config.go
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/hack/metrics.md.tpl
  components/kyma-metrics-collector/metrics.md
  components/kyma-metrics-collector/options/options.go
  components/kyma-metrics-collector/pkg/cache/kubeconfig.go
  components/kyma-metrics-collector/pkg/cache/record.go
  components/kyma-metrics-collector/pkg/edp/client.go
  components/kyma-metrics-collector/pkg/edp/client_test.go
  components/kyma-metrics-collector/pkg/edp/config.go
  components/kyma-metrics-collector/pkg/edp/consumption_metrics.go
  components/kyma-metrics-collector/pkg/edp/metrics.go
  components/kyma-metrics-collector/pkg/keb/client.go
  components/kyma-metrics-collector/pkg/keb/client_test.go
  components/kyma-metrics-collector/pkg/keb/config.go
  components/kyma-metrics-collector/pkg/keb/metrics.go
  components/kyma-metrics-collector/pkg/logger/logger.go
  components/kyma-metrics-collector/pkg/process/event_stream.go
  components/kyma-metrics-collector/pkg/process/event_stream_test.go
  components/kyma-metrics-collector/pkg/process/metrics.go
  components/kyma-metrics-collector/pkg/process/process.go
  components/kyma-metrics-collector/pkg/process/process_test.go
  components/kyma-metrics-collector/pkg/process/public_cloud_info.go
  components/kyma-metrics-collector/pkg/process/public_cloud_info_test.go
  components/kyma-metrics-collector/pkg/service/server.go
  components/kyma-metrics-collector/pkg/skr/commons/helpers.go
  components/kyma-metrics-collector/pkg/skr/commons/metrics.go
  components/kyma-metrics-collector/pkg/skr/node/client.go
  components/kyma-metrics-collector/pkg/skr/node/client_test.go
  components/kyma-metrics-collector/pkg/skr/node/config.go
  components/kyma-metrics-collector/pkg/skr/node/fake.go
  components/kyma-metrics-collector/pkg/skr/pvc/client.go
  components/kyma-metrics-collector/pkg/skr/pvc/client_test.go
  components/kyma-metrics-collector/pkg/skr/pvc/config.go
  components/kyma-metrics-collector/pkg/skr/pvc/fake.go
  components/kyma-metrics-collector/pkg/skr/svc/client.go
  components/kyma-metrics-collector/pkg/skr/svc/client_test.go
  components/kyma-metrics-collector/pkg/skr/svc/config.go
  components/kyma-metrics-collector/pkg/skr/svc/fake.go
  components/kyma-metrics-collector/pkg/testing/fixtures/runtimes_response.json
  components/kyma-metrics-collector/pkg/testing/fixtures/runtimes_response_page1.json
  components/kyma-metrics-collector/pkg/testing/fixtures/runtimes_response_page2.json
  components/kyma-metrics-collector/pkg/testing/fixtures/runtimes_response_process.json
  components/kyma-metrics-collector/pkg/testing/fixtures/static_providers.json
  components/kyma-metrics-collector/pkg/testing/helpers.go
Labels: area/documentation, size/XXL, lgtm, cla: yes

#3423 chore: removed kyma-metrics-collector helm chart
  CODEOWNERS
  resources/kcp/Chart.yaml
  resources/kcp/charts/kyma-metrics-collector/.helmignore
  resources/kcp/charts/kyma-metrics-collector/Chart.yaml
  resources/kcp/charts/kyma-metrics-collector/OWNERS
  resources/kcp/charts/kyma-metrics-collector/prometheus/alerts.yaml
  resources/kcp/charts/kyma-metrics-collector/prometheus/alerts_test.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/_helpers.tpl
  resources/kcp/charts/kyma-metrics-collector/templates/deployment.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/policy.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/prometheusrule.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/role.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/rolebinding.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/secrets.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/service-account.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/service-monitor.yaml
  resources/kcp/charts/kyma-metrics-collector/templates/service.yaml
  resources/kcp/charts/kyma-metrics-collector/values.yaml
  resources/kcp/values.yaml
Labels: size/XXL, lgtm, cla: yes

#3424 Refactor provisioner tests env
  .github/workflows/provisioner-e2e-test.yaml
  components/provisioner/Makefile
  components/provisioner/README.md
  components/provisioner/e2e_test/main_test.go
  components/provisioner/e2e_test/requests/provision.graphql
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/persistence/database/schema_initializer_test.go
  components/provisioner/internal/persistence/testutils/database.go
Labels: area/documentation, size/L, lgtm, cla: yes

#3287 Bump graphql libs
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/gqlgen.sh
  components/provisioner/hack/gqlgen.go
  components/provisioner/hack/regenerate-mocks.sh
  components/provisioner/internal/api/mocks/TenantUpdater.go
  components/provisioner/internal/api/mocks/Validator.go
  components/provisioner/internal/director/mocks/DirectorClient.go
  components/provisioner/internal/gardener/mocks/Client.go
  components/provisioner/internal/gardener/mocks/ShootClient.go
  components/provisioner/internal/graphql/mocks/Client.go
  components/provisioner/internal/metrics/mocks/OperationsStatsGetter.go
  components/provisioner/internal/oauth/mocks/Client.go
  components/provisioner/internal/operations/queue/mocks/KubeconfigProvider.go
  components/provisioner/internal/operations/queue/mocks/OperationQueue.go
  components/provisioner/internal/operations/stages/deprovisioning/mocks/GardenerClient.go
  components/provisioner/internal/operations/stages/provisioning/mocks/DynamicKubeconfigProvider.go
  components/provisioner/internal/operations/stages/provisioning/mocks/GardenerClient.go
  components/provisioner/internal/operations/stages/shootupgrade/mocks/KubeconfigProvider.go
  components/provisioner/internal/provisioning/mocks/Provisioner.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/provisioning/mocks/ShootProvider.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/Factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/runtime/mocks/Configurator.go
  components/provisioner/internal/util/k8s/mocks/K8sClientProvider.go
  components/provisioner/internal/uuid/mocks/UUIDGenerator.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema_gen.go
  components/provisioner/tools.go
Labels: size/XXL, lgtm, cla: yes

#3427 Bump provisioner image
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3429 provisioner: add support for configuring AWS IMDSv2 access method
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/model/infrastructure.go
  components/provisioner/internal/model/infrastructure/aws/worker.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
Labels: size/L, lgtm, cla: yes

#3430 Bump provisioner in kcp chart to v20240429-ea75326a
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes
