Repository kyma-project/control-plane, pull requests merged in 2024-09, with the labels that each got.

#3467 Provisioner - enable oidc extension by default for newly provisioned clusters
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
Labels: size/S, lgtm, cla: yes

#3468 Update provisioner image to version v20240903-8152ffd9 prod
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3470 docs: Add mandatory sections to README.md
  README.md
Labels: area/documentation, size/S, lgtm, cla: yes

#3471 Migrate provisioner build
  .github/workflows/provisioner.yaml
Labels: size/M, lgtm, cla: yes

#3472 Trigger provisioner build on pipeline change
  .github/workflows/provisioner.yaml
Labels: size/XS, lgtm, cla: yes

#3474 Fix provisioner build triggers
  .github/workflows/provisioner.yaml
Labels: size/XS, lgtm, cla: yes

#3475 Fix pointless dependency in provisioner workflow
  .github/workflows/provisioner.yaml
Labels: size/XS, lgtm, cla: yes

#3476 tiny log change to test new build pipelines
  components/provisioner/cmd/main.go
Labels: size/XS, lgtm, cla: yes

#3477 Remove e2e provisioning test
  tests/e2e/provisioning/Dockerfile
  tests/e2e/provisioning/Makefile
  tests/e2e/provisioning/README.md
  tests/e2e/provisioning/go.mod
  tests/e2e/provisioning/go.sum
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
  tests/e2e/provisioning/pkg/client/broker/model.go
  tests/e2e/provisioning/pkg/client/broker/upgrade_broker_client.go
  tests/e2e/provisioning/pkg/client/runtime/runtime_client.go
  tests/e2e/provisioning/pkg/client/v1_client/configmap.go
  tests/e2e/provisioning/pkg/client/v1_client/secret.go
  tests/e2e/provisioning/test/e2e_provisioning_test.go
  tests/e2e/provisioning/test/e2e_suspension_test.go
  tests/e2e/provisioning/test/e2e_upgrade_test.go
  tests/e2e/provisioning/test/test_suite.go
  tests/e2e/provisioning/test/upgrade_test_suite.go
Labels: area/documentation, size/XXL, lgtm, cla: yes

#3481 Provisioner - Update Golang version to 1.23.1
  components/provisioner/Dockerfile
  components/provisioner/go.mod
  components/provisioner/go.sum
Labels: size/M, lgtm, cla: yes

#3482 Update Provisioner image
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3483 Bump subscription cleanup job
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes
