Repository kyma-project/control-plane, pull requests merged in 2024-08, with the labels that each got.

#3460 feat: Saving Graphql mutation object to Persistent Volume
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/util/testkit/dump.go
Labels: size/L, lgtm, cla: yes

#3463 Bump Provisioner's image
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3464 Migrate schema-migrator pipelines
  .github/workflows/schema-migrator.yaml
Labels: size/M, lgtm, cla: yes

#3465 Update golang version in schema-migrator
  components/schema-migrator/Dockerfile
  components/schema-migrator/go.mod
  components/schema-migrator/validate.sh
Labels: size/XS, lgtm, cla: yes
