Repository kyma-project/control-plane, pull requests merged in 2024-03, with the labels that each got.

#3393 Remove kubeconfig-service code
  components/kubeconfig-service/Dockerfile
  components/kubeconfig-service/Makefile
  components/kubeconfig-service/README.md
  components/kubeconfig-service/cmd/generator/main.go
  components/kubeconfig-service/go.mod
  components/kubeconfig-service/go.sum
  components/kubeconfig-service/pkg/authn/middleware.go
  components/kubeconfig-service/pkg/authn/middleware_test.go
  components/kubeconfig-service/pkg/authn/oidc.go
  components/kubeconfig-service/pkg/client/client.go
  components/kubeconfig-service/pkg/client/client_test.go
  components/kubeconfig-service/pkg/endpoints/endpoint.go
  components/kubeconfig-service/pkg/env/env.go
  components/kubeconfig-service/pkg/reload/doc.go
  components/kubeconfig-service/pkg/reload/reload.go
  components/kubeconfig-service/pkg/reload/watch.go
  components/kubeconfig-service/pkg/reload/watch_test.go
  components/kubeconfig-service/pkg/runtime/runtime.go
  components/kubeconfig-service/pkg/runtime/runtime_kcp.go
  components/kubeconfig-service/pkg/runtime/runtime_test.go
  components/kubeconfig-service/pkg/transformer/kubeconfig.go
  components/kubeconfig-service/pkg/transformer/transformer.go
  components/kubeconfig-service/pkg/transformer/transformer_test.go
  components/kubeconfig-service/run.sh
Labels: area/documentation, size/XXL, lgtm, cla: yes

#3389 docs: update README with gardener removal
  components/kyma-metrics-collector/README.md
  components/kyma-metrics-collector/dev/deployment.yaml
Labels: area/documentation, size/S, lgtm, cla: yes

#3401 Add more logs to schema-migrator
  components/schema-migrator/main.go
Labels: size/M, lgtm, cla: yes

#3405 Update provsioner image to v20240312-b74ff6dd
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3409 Psp config removed
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/util/testkit/shoot.go
Labels: do-not-merge/hold, size/S, lgtm, cla: yes

#3410 Psp config removed bump
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3415 Provisioner creates "istio-system" namespace as part of "create operator bindings" step
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
Labels: size/M, lgtm, cla: yes

#3417 Update provsioner image to v20240320-dd88e90c
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3418 Use instanceID for fetching kubeconfig in e2e tests
  tests/e2e/provisioning/pkg/client/runtime/runtime_client.go
Labels: size/M, lgtm, cla: yes

#3419 Remove Director references from e2e tests
  tests/e2e/provisioning/README.md
  tests/e2e/provisioning/go.mod
  tests/e2e/provisioning/go.sum
  tests/e2e/provisioning/pkg/client/broker/broker_client.go
  tests/e2e/provisioning/pkg/client/runtime/runtime_client.go
  tests/e2e/provisioning/test/test_suite.go
Labels: area/documentation, size/L, lgtm, cla: yes
