Repository kyma-project/control-plane, pull requests merged in 2024-06, with the labels that each got.

#3444 Change to use cloudsql-proxy v2 image and cmd
  components/schema-migrator/cleaner/halt.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/templates/migrator-job.yaml
  resources/kcp/values.yaml
Labels: size/M, lgtm, cla: yes

#3446 Sending sigterm to terminate `cloud-sql-proxy`
  components/schema-migrator/cleaner/halt.go
Labels: size/XS, lgtm, cla: yes

#3447 Add --exit-zero-on-sigterm for cloudsql-proxy
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/templates/migrator-job.yaml
Labels: size/XS, lgtm, cla: yes

#3449 bump schema migrator tag to latest
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3450 Update README.md
  components/schema-migrator/README.md
Labels: area/documentation, size/XS, lgtm, cla: yes

#3433 Provisioner - Adding a feature flag to dump generated Gardener shoot spec into logs
  components/provisioner/cmd/main.go
  components/provisioner/go.mod
  components/provisioner/go.sum
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/gardener_config.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: size/L, lgtm, cla: yes
