Repository kyma-project/control-plane, pull requests merged in 2024-05, with the labels that each got.

#3432 Update provisioner image to version v20240507-ff9c0545 prod
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3426 Skip compass-runtime-agent component.
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3438 Remove obsolete L2/L3 operator bindings from provisioner
  components/provisioner/cmd/main.go
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
Labels: size/L, lgtm, cla: yes

#3440 ShootAndSeedSameRegion Field
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
Labels: size/M, lgtm, cla: yes

#3443 Correction for #344 - shootAndSeedSameRegion in GardenerConfigInput
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
Labels: size/M, lgtm, cla: yes
