Repository kyma-project/control-plane, pull requests merged in 2024-02, with the labels that each got.

#3315 Update reconciler image to version v20240201-9591c364
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm, cla: yes

#3294 OpenStack regions restrictions
  components/provisioner/cmd/main.go
  components/provisioner/e2e_test/test.sh
  components/provisioner/go.mod
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/testdata/config.json
  components/provisioner/internal/api/validator.go
  components/provisioner/internal/api/validator_test.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: area/control-plane, size/L, lgtm, cla: yes

#3318 Bump Provisioner image (CCEE regions)
  resources/kcp/charts/provisioner/values.yaml
Labels: area/control-plane, lgtm, cla: yes

#3304 Ignore Connectivity Proxy when CRD exists
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm, cla: yes

#3321 Changed machine types to lowercase in KMC
  components/kyma-metrics-collector/pkg/process/public_cloud_info.go
  components/kyma-metrics-collector/pkg/process/public_cloud_info_test.go
  components/kyma-metrics-collector/pkg/testing/fixtures/static_providers.json
  resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
Labels: size/M, lgtm, cla: yes

#3322 Bump KMC image
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3332 Fix vulnerability in runc
  components/provisioner/go.mod
  components/provisioner/go.sum
  tools/cli/go.mod
  tools/cli/go.sum
Labels: size/M, lgtm, cla: yes

#3341 Add Jellyfish for component reconcilers as CodeOwner
  CODEOWNERS
Labels: size/XS, lgtm, cla: yes

#3323 The Provisioner adds OpenStack parameters
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
Labels: area/control-plane, size/M, lgtm, cla: yes

#3346 Update Provisioner image
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3348 Fix warden reconciler image bump
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
Labels: size/XS, lgtm, cla: yes

#3347 Remove Gardener dependency and make networking optional
  components/kyma-metrics-collector/cmd/main.go
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/pkg/cache/kubeconfig.go
  components/kyma-metrics-collector/pkg/cache/record.go
  components/kyma-metrics-collector/pkg/edp/consumption_metrics.go
  components/kyma-metrics-collector/pkg/gardener/commons/helpers.go
  components/kyma-metrics-collector/pkg/gardener/commons/metrics.go
  components/kyma-metrics-collector/pkg/gardener/secret/client.go
  components/kyma-metrics-collector/pkg/gardener/secret/client_test.go
  components/kyma-metrics-collector/pkg/gardener/shoot/client.go
  components/kyma-metrics-collector/pkg/gardener/shoot/client_test.go
  components/kyma-metrics-collector/pkg/process/event_stream.go
  components/kyma-metrics-collector/pkg/process/event_stream_test.go
  components/kyma-metrics-collector/pkg/process/process.go
  components/kyma-metrics-collector/pkg/process/process_test.go
  components/kyma-metrics-collector/pkg/process/public_cloud_info.go
  components/kyma-metrics-collector/pkg/process/public_cloud_info_test.go
  components/kyma-metrics-collector/pkg/skr/commons/helpers.go
  components/kyma-metrics-collector/pkg/skr/node/client_test.go
  components/kyma-metrics-collector/pkg/skr/node/fake.go
  components/kyma-metrics-collector/pkg/skr/pvc/client_test.go
  components/kyma-metrics-collector/pkg/skr/pvc/fake.go
  components/kyma-metrics-collector/pkg/skr/svc/client_test.go
  components/kyma-metrics-collector/pkg/skr/svc/fake.go
  components/kyma-metrics-collector/pkg/testing/fixtures/static_providers.json
  components/kyma-metrics-collector/pkg/testing/helpers.go
  resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
Labels: area/control-plane, size/XXL, lgtm, cla: yes

#3351 chore: Update KMC image
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3353 Clean-up gardener secret configs references
  components/kyma-metrics-collector/options/options.go
  resources/kcp/charts/kyma-metrics-collector/templates/deployment.yaml
  resources/kcp/charts/kyma-metrics-collector/values.yaml
Labels: size/M, lgtm, cla: yes

#3354 Bump KMC image
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3342 feat: added metrics in KMC
  components/kyma-metrics-collector/pkg/cache/record.go
  components/kyma-metrics-collector/pkg/edp/client.go
  components/kyma-metrics-collector/pkg/edp/client_test.go
  components/kyma-metrics-collector/pkg/edp/metrics.go
  components/kyma-metrics-collector/pkg/keb/client.go
  components/kyma-metrics-collector/pkg/keb/client_test.go
  components/kyma-metrics-collector/pkg/keb/metrics.go
  components/kyma-metrics-collector/pkg/process/metrics.go
  components/kyma-metrics-collector/pkg/process/process.go
  components/kyma-metrics-collector/pkg/process/process_test.go
  components/kyma-metrics-collector/pkg/skr/commons/metrics.go
  components/kyma-metrics-collector/pkg/skr/node/client.go
  components/kyma-metrics-collector/pkg/skr/node/client_test.go
  components/kyma-metrics-collector/pkg/skr/node/config.go
  components/kyma-metrics-collector/pkg/skr/node/fake.go
  components/kyma-metrics-collector/pkg/skr/pvc/client.go
  components/kyma-metrics-collector/pkg/skr/pvc/client_test.go
  components/kyma-metrics-collector/pkg/skr/pvc/config.go
  components/kyma-metrics-collector/pkg/skr/pvc/fake.go
  components/kyma-metrics-collector/pkg/skr/svc/client.go
  components/kyma-metrics-collector/pkg/skr/svc/client_test.go
  components/kyma-metrics-collector/pkg/skr/svc/config.go
  components/kyma-metrics-collector/pkg/skr/svc/fake.go
  components/kyma-metrics-collector/pkg/testing/helpers.go
Labels: size/XXL, lgtm, cla: yes

#3360 Ensure that database record (ClusterConfig) are set properly
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
Labels: area/control-plane, size/M, lgtm, cla: yes

#3362 Bump Provisioner image
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3363 Generic pointer utils
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/api/validator_test.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/gardener/provisioner_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/model/infrastructure.go
  components/provisioner/internal/operations/stages/provisioning/connect_agent_test.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain_test.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/util/pointers.go
  components/provisioner/internal/util/testkit/worker.go
  components/provisioner/pkg/gqlschema/provider_config_test.go
Labels: size/XXL, lgtm, cla: yes

#3366 chore: bump KMC image
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3361 bumps golang to 1.22.0 and alpine to 3.19.1 in provisioner
  components/provisioner/Dockerfile
  tests/e2e/provisioning/Dockerfile
  tests/provisioner-tests/Dockerfile
Labels: size/S, lgtm, cla: yes

#3369 [CCEE] Set Cloud Profile as default
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/provisioning/input_converter.go
  components/provisioner/internal/provisioning/input_converter_test.go
  components/provisioner/pkg/gqlschema/models_gen.go
  components/provisioner/pkg/gqlschema/schema.graphql
  components/provisioner/pkg/gqlschema/schema_gen.go
Labels: area/control-plane, size/S, lgtm, cla: yes

#3371 Set correct parameter in Gardener object
  components/provisioner/internal/model/gardener_config.go
Labels: area/control-plane, size/XS, lgtm, cla: yes

#3374 Bump Provisioner image
  resources/kcp/charts/provisioner/values.yaml
Labels: area/control-plane, size/XS, lgtm, cla: yes

#3375 Chore: Bump Go version in mod file
  components/kyma-metrics-collector/go.mod
Labels: size/XS, lgtm, cla: yes

#3377 feat: changed buckets for histogram metrics in KMC
  components/kyma-metrics-collector/pkg/edp/metrics.go
  components/kyma-metrics-collector/pkg/keb/metrics.go
Labels: size/XS, lgtm, cla: yes

#3370 fix: changed retry policy for EDP and KEB in KMC
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/pkg/edp/client.go
  components/kyma-metrics-collector/pkg/edp/client_test.go
  components/kyma-metrics-collector/pkg/keb/client.go
  components/kyma-metrics-collector/pkg/keb/client_test.go
Labels: size/L, lgtm, cla: yes

#3359 feat: added alerts for KMC
  resources/kcp/charts/kyma-metrics-collector/prometheus/alerts.yaml
  resources/kcp/charts/kyma-metrics-collector/prometheus/alerts_test.yaml
Labels: size/L, lgtm, cla: yes

#3383 chore: bump KMC image
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3384 switches provisioner build image from alpine to scratch
  components/provisioner/Dockerfile
Labels: size/XS, lgtm, cla: yes

#3385 Bumped k8s.io/api and removed unused code
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/pkg/testing/helpers.go
Labels: size/S, lgtm, cla: yes

#3387 chore: bump KMC image
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3388 bumps provisioner image
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3386 Remove OpenStack region whitelisting in Provisioner
  components/provisioner/cmd/main.go
  components/provisioner/e2e_test/test.sh
  components/provisioner/go.mod
  components/provisioner/internal/api/resolver_integration_test.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/testdata/config.json
  components/provisioner/internal/api/validator.go
  components/provisioner/internal/api/validator_test.go
  resources/kcp/charts/provisioner/templates/deployment.yaml
  resources/kcp/charts/provisioner/values.yaml
Labels: area/control-plane, size/L, lgtm, cla: yes

#3391 Bump image in Provisioner
  resources/kcp/charts/provisioner/values.yaml
Labels: area/control-plane, size/XS, lgtm, cla: yes

#3394 chore: bump KMC image
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes
