Repository kyma-project/control-plane, pull requests merged in 2024-01, with the labels that each got.

#3264 Update subscription-cleanup-job.yaml
  resources/kcp/charts/provisioner/templates/subscription-cleanup-job.yaml
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3261 Removing support for static Kubeconfig in provisioner.
  components/provisioner/cmd/init.go
  components/provisioner/cmd/main.go
  components/provisioner/e2e_test/main_test.go
  components/provisioner/e2e_test/requests/operationstatus.graphql
  components/provisioner/internal/api/mocks/TenantUpdater.go
  components/provisioner/internal/api/mocks/Validator.go
  components/provisioner/internal/api/resolver_integration_with_gardener_test.go
  components/provisioner/internal/api/resolver_test.go
  components/provisioner/internal/director/mocks/DirectorClient.go
  components/provisioner/internal/gardener/auditlogging.go
  components/provisioner/internal/gardener/kubeconfig_provider.go
  components/provisioner/internal/gardener/mocks/Client.go
  components/provisioner/internal/gardener/mocks/ShootClient.go
  components/provisioner/internal/gardener/provisioner.go
  components/provisioner/internal/graphql/mocks/Client.go
  components/provisioner/internal/metrics/mocks/OperationsStatsGetter.go
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
  components/provisioner/internal/oauth/mocks/Client.go
  components/provisioner/internal/operations/queue/mocks/KubeconfigProvider.go
  components/provisioner/internal/operations/queue/mocks/OperationQueue.go
  components/provisioner/internal/operations/queue/queues_constructor.go
  components/provisioner/internal/operations/stages/deprovisioning/mocks/GardenerClient.go
  components/provisioner/internal/operations/stages/provisioning/create_operators_bindings_test.go
  components/provisioner/internal/operations/stages/provisioning/mocks/DynamicKubeconfigProvider.go
  components/provisioner/internal/operations/stages/provisioning/mocks/GardenerClient.go
  components/provisioner/internal/operations/stages/provisioning/mocks/KubeconfigProvider.go
  components/provisioner/internal/operations/stages/provisioning/mocks/StaticKubeconfigProvider.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_creation_test.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain.go
  components/provisioner/internal/operations/stages/provisioning/wait_for_cluster_domain_test.go
  components/provisioner/internal/operations/stages/shootupgrade/mocks/KubeconfigProvider.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_new_version.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade.go
  components/provisioner/internal/operations/stages/shootupgrade/wait_for_shoot_upgrade_test.go
  components/provisioner/internal/provisioning/graphql_converter_test.go
  components/provisioner/internal/provisioning/mocks/Provisioner.go
  components/provisioner/internal/provisioning/mocks/Service.go
  components/provisioner/internal/provisioning/mocks/ShootProvider.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/Factory.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/ReadWriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSession.go
  components/provisioner/internal/provisioning/persistence/dbsession/mocks/WriteSessionWithinTransaction.go
  components/provisioner/internal/provisioning/persistence/dbsession/read.go
  components/provisioner/internal/provisioning/service.go
  components/provisioner/internal/provisioning/service_test.go
  components/provisioner/internal/runtime/mocks/Configurator.go
  components/provisioner/internal/util/k8s/mocks/K8sClientProvider.go
  components/provisioner/internal/uuid/mocks/UUIDGenerator.go
Labels: size/XL, lgtm, cla: yes

#3267 bumps provisioner image
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3268 Corrected Invalid Values Reference
  resources/kcp/charts/provisioner/templates/subscription-cleanup-job.yaml
Labels: size/XS, lgtm, cla: yes

#3269 Corrected Image Path for Subscription Cleanup Job
  resources/kcp/values.yaml
Labels: size/S, lgtm, cla: yes

#3272 sets EnableStaticTokenKubeconfig to false during 1.27.0+ upgrades
  components/provisioner/internal/model/gardener_config.go
  components/provisioner/internal/model/gardener_config_test.go
Labels: size/M, lgtm, cla: yes

#3274 bumps provisioner
  resources/kcp/charts/provisioner/values.yaml
Labels: size/XS, lgtm, cla: yes

#3266 Use kubeconfig from secret e2etest
  tests/e2e/provisioning/pkg/client/runtime/runtime_client.go
  tests/e2e/provisioning/test/test_suite.go
Labels: area/control-plane, size/M, lgtm, cla: yes

#3260 [Provisioner E2E] The new URL to Compass System on DEV
  components/provisioner/e2e_test/test.sh
Labels: area/control-plane, size/XS, lgtm, cla: yes

#3290 Bumped KMC image
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3292 Fix KMC chart
  resources/kcp/charts/kyma-metrics-collector/templates/rolebinding.yaml
Labels: size/XS, lgtm, cla: yes

#3297 bumps subscription cleanup job
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3291 Add --gardener-config flag
  tools/cli/go.mod
  tools/cli/go.sum
  tools/cli/pkg/command/runtime.go
Labels: size/M, lgtm, cla: yes

#3298 Bump kubeconfig-service to v20240124-709e778b
  resources/oidc-kubeconfig-service/values.yaml
Labels: size/XS, lgtm, cla: yes

#3300 Bump KMC dependencies
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
Labels: size/S, lgtm, cla: yes

#3286 Added support for CCEE infra
  components/kyma-metrics-collector/go.mod
  components/kyma-metrics-collector/go.sum
  components/kyma-metrics-collector/pkg/process/event_stream.go
  components/kyma-metrics-collector/pkg/process/event_stream_test.go
  components/kyma-metrics-collector/pkg/process/public_cloud_info.go
  components/kyma-metrics-collector/pkg/process/public_cloud_info_test.go
  components/kyma-metrics-collector/pkg/testing/fixtures/static_providers.json
  components/kyma-metrics-collector/pkg/testing/helpers.go
  resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
Labels: size/XL, lgtm, cla: yes

#3302 bump KMC image
  resources/kcp/charts/kyma-metrics-collector/values.yaml
Labels: size/XS, lgtm, cla: yes

#3305 Added Azure machine types in KMC
  components/kyma-metrics-collector/pkg/process/public_cloud_info_test.go
  components/kyma-metrics-collector/pkg/testing/fixtures/static_providers.json
  resources/kcp/charts/kyma-metrics-collector/templates/public-cloud-info-config-map.yaml
Labels: size/L, lgtm, cla: yes

#3307 Bump KMC image
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes

#3309 Added comment in KMC helm chart
  resources/kcp/charts/kyma-metrics-collector/values.yaml
Labels: size/XS, lgtm, cla: yes

#3311 Warden reconciler to handle invalid certs volumemounts
  resources/kcp/charts/component-reconcilers/values.yaml
  resources/kcp/charts/mothership-reconciler/values.yaml
  resources/kcp/values.yaml
Labels: size/XS, lgtm, cla: yes
